import { ENEMIES } from './Enemies.js';
import { BOSSES } from './Bosses.js';

/** @typedef {import('./Enemies.js').EnemyEntry} EnemyEntry */

/**
 * @typedef {'Dungeon'|'World Map'} AreaType
 */

/**
 * @typedef {Object} Area
 * @property {string} name
 * @property {number} encounterRate
 * @property {AreaType} [areaType]
 * @property {EnemyEntry[][]} encounters - Possible random-encounter party compositions.
 * @property {EnemyEntry[][]} [scripted] - Fixed/forced fights tied to this area (bosses, ambushes), not part of the random encounter table.
 */

/** @satisfies {Record<string, Area>} */
export const AREAS = {
  CAVE_OF_THE_PAST: {
    name: 'Cave of the Past',
    encounterRate: 2,
    areaType: 'Dungeon',
    encounters: [
      [ENEMIES.BANSHEE],
      [ENEMIES.BANSHEE, ENEMIES.BANSHEE],
      [ENEMIES.BANSHEE, ENEMIES.BANSHEE, ENEMIES.BANSHEE],
      [ENEMIES.CLAY_DOLL],
      [ENEMIES.CLAY_DOLL, ENEMIES.CLAY_DOLL],
      [ENEMIES.CLAY_DOLL, ENEMIES.CLAY_DOLL, ENEMIES.CLAY_DOLL],
      [ENEMIES.BANSHEE, ENEMIES.CLAY_DOLL],
      [ENEMIES.BANSHEE, ENEMIES.BANSHEE, ENEMIES.CLAY_DOLL],
      [ENEMIES.RED_ELEMENTAL, ENEMIES.RED_ELEMENTAL, ENEMIES.RED_ELEMENTAL, ENEMIES.CLAY_DOLL],
      [ENEMIES.RED_ELEMENTAL, ENEMIES.RED_ELEMENTAL, ENEMIES.RED_ELEMENTAL, ENEMIES.BANSHEE],
      [ENEMIES.RED_ELEMENTAL, ENEMIES.RED_ELEMENTAL, ENEMIES.RED_ELEMENTAL, ENEMIES.BANSHEE, ENEMIES.BANSHEE],
    ],
  },

  DRAGON_KNIGHTS_AREA: {
    name: 'Dragon Knights Area',
    encounterRate: 8,
    areaType: 'World Map',
    encounters: [
      [ENEMIES.IVY],
      [ENEMIES.IVY, ENEMIES.IVY],
      [ENEMIES.IVY, ENEMIES.IVY, ENEMIES.IVY],
      [ENEMIES.SHADOW_MAN],
      [ENEMIES.SHADOW_MAN, ENEMIES.SHADOW_MAN],
      [ENEMIES.MIRAGE, ENEMIES.MIRAGE],
      [ENEMIES.MIRAGE, ENEMIES.MIRAGE, ENEMIES.MIRAGE, ENEMIES.MIRAGE],
      [ENEMIES.IVY, ENEMIES.IVY, ENEMIES.IVY, ENEMIES.SHADOW_MAN, ENEMIES.MIRAGE],
    ],
  },

  DRAGONS_DEN: {
    name: "Dragon's Den",
    encounterRate: 3,
    areaType: 'Dungeon',
    encounters: [
      [ENEMIES.SUNSHINE_KING],
      [ENEMIES.MAGIC_SHIELD],
      [ENEMIES.MAGIC_SHIELD, ENEMIES.MAGIC_SHIELD],
      [ENEMIES.MAGIC_SHIELD, ENEMIES.MAGIC_SHIELD, ENEMIES.MAGIC_SHIELD],
      [ENEMIES.MAGIC_SHIELD, ENEMIES.SUNSHINE_KING],
      [ENEMIES.BLACK_ELEMENTAL, ENEMIES.BLACK_ELEMENTAL, ENEMIES.BLACK_ELEMENTAL, ENEMIES.SUNSHINE_KING],
      [ENEMIES.BLACK_ELEMENTAL, ENEMIES.BLACK_ELEMENTAL, ENEMIES.BLACK_ELEMENTAL, ENEMIES.MAGIC_SHIELD, ENEMIES.MAGIC_SHIELD],
    ],
  },

  DWARVES_TRAIL: {
    name: 'Dwarves Trail',
    encounterRate: 2,
    areaType: 'Dungeon',
    encounters: [
      [ENEMIES.DWARF, ENEMIES.DWARF, ENEMIES.DWARF, ENEMIES.EAGLE_MAN, ENEMIES.EAGLE_MAN],
      [ENEMIES.EAGLE_MAN],
      [ENEMIES.EAGLE_MAN, ENEMIES.EAGLE_MAN],
      [ENEMIES.EAGLE_MAN, ENEMIES.EAGLE_MAN, ENEMIES.EAGLE_MAN],
      [ENEMIES.DWARF],
      [ENEMIES.DWARF, ENEMIES.DWARF],
      [ENEMIES.DWARF, ENEMIES.DWARF, ENEMIES.DWARF],
      [ENEMIES.DEATH_BOAR],
      [ENEMIES.DEATH_BOAR, ENEMIES.DEATH_BOAR],
      [ENEMIES.DEATH_BOAR, ENEMIES.DEATH_BOAR, ENEMIES.DEATH_BOAR],
      [ENEMIES.DEATH_BOAR, ENEMIES.DEATH_BOAR, ENEMIES.DEATH_BOAR, ENEMIES.EAGLE_MAN],
      [ENEMIES.DEATH_BOAR, ENEMIES.DEATH_BOAR, ENEMIES.DEATH_BOAR, ENEMIES.DWARF],
      [ENEMIES.DEATH_BOAR, ENEMIES.DEATH_BOAR, ENEMIES.DEATH_BOAR, ENEMIES.EAGLE_MAN, ENEMIES.EAGLE_MAN],
      [ENEMIES.DEATH_BOAR, ENEMIES.DEATH_BOAR, ENEMIES.DEATH_BOAR, ENEMIES.DWARF, ENEMIES.EAGLE_MAN],
    ],
  },

  DWARVES_VAULT: {
    name: 'Dwarves Vault',
    encounterRate: 2,
    areaType: 'Dungeon',
    encounters: [
      [ENEMIES.DEATH_MACHINE_SWORD],
      [ENEMIES.DEATH_MACHINE_SWORD, ENEMIES.DEATH_MACHINE_SWORD],
      [ENEMIES.DEATH_MACHINE_SWORD, ENEMIES.DEATH_MACHINE_SWORD, ENEMIES.DEATH_MACHINE_SWORD],
      [ENEMIES.DEATH_MACHINE_SPEAR],
      [ENEMIES.DEATH_MACHINE_SPEAR, ENEMIES.DEATH_MACHINE_SPEAR],
      [ENEMIES.DEATH_MACHINE_SPEAR, ENEMIES.DEATH_MACHINE_SPEAR, ENEMIES.DEATH_MACHINE_SPEAR],
      [ENEMIES.CRIMSON_DWARF],
      [ENEMIES.CRIMSON_DWARF, ENEMIES.CRIMSON_DWARF],
      [ENEMIES.CRIMSON_DWARF, ENEMIES.CRIMSON_DWARF, ENEMIES.CRIMSON_DWARF],
      [ENEMIES.DEATH_BOAR, ENEMIES.DEATH_BOAR],
      [ENEMIES.DEATH_BOAR, ENEMIES.DEATH_BOAR, ENEMIES.DEATH_BOAR],
      [ENEMIES.CRIMSON_DWARF, ENEMIES.CRIMSON_DWARF, ENEMIES.CRIMSON_DWARF, ENEMIES.DEATH_MACHINE_SWORD],
      [ENEMIES.CRIMSON_DWARF, ENEMIES.CRIMSON_DWARF, ENEMIES.CRIMSON_DWARF, ENEMIES.DEATH_MACHINE_SWORD, ENEMIES.DEATH_MACHINE_SWORD],
      [
        ENEMIES.CRIMSON_DWARF,
        ENEMIES.CRIMSON_DWARF,
        ENEMIES.CRIMSON_DWARF,
        ENEMIES.DEATH_MACHINE_SWORD,
        ENEMIES.DEATH_MACHINE_SWORD,
        ENEMIES.DEATH_MACHINE_SWORD,
      ],
    ],
    scripted: [[BOSSES.GIGANTES]],
  },

  GREAT_FOREST: {
    name: 'Great Forest',
    encounterRate: 2,
    areaType: 'Dungeon',
    encounters: [
      [ENEMIES.KOBOLD_SWORD],
      [ENEMIES.KOBOLD_SWORD, ENEMIES.KOBOLD_SWORD, ENEMIES.KOBOLD_SWORD],
      [ENEMIES.KOBOLD_SWORD, ENEMIES.KOBOLD_SWORD, ENEMIES.KOBOLD_SWORD, ENEMIES.KOBOLD_BOW, ENEMIES.KOBOLD_BOW, ENEMIES.KOBOLD_BOW],
      [ENEMIES.KOBOLD_BOW, ENEMIES.KOBOLD_BOW],
      [ENEMIES.HOLLY_BOY_2, ENEMIES.HOLLY_BOY_2, ENEMIES.HOLLY_SPIRIT],
      [ENEMIES.HOLLY_BOY_2, ENEMIES.HOLLY_BOY_2, ENEMIES.HOLLY_BOY_2, ENEMIES.HOLLY_BOY_2, ENEMIES.HOLLY_BOY_2, ENEMIES.HOLLY_SPIRIT],
      [ENEMIES.HOLLY_BOY_2, ENEMIES.HOLLY_BOY_2, ENEMIES.HOLLY_BOY_2, ENEMIES.HOLLY_SPIRIT, ENEMIES.HOLLY_SPIRIT, ENEMIES.HOLLY_SPIRIT],
      [ENEMIES.HOLLY_BOY_2, ENEMIES.HOLLY_BOY_2, ENEMIES.HOLLY_BOY_2, ENEMIES.HOLLY_BOY_2, ENEMIES.HOLLY_BOY_2, ENEMIES.HOLLY_BOY_2],
    ],
  },

  GREGMINSTER_AREA_1: {
    name: 'Gregminster Area 1',
    encounterRate: 8,
    areaType: 'World Map',
    encounters: [
      [ENEMIES.BON_BON],
      [ENEMIES.BON_BON, ENEMIES.BON_BON, ENEMIES.BON_BON],
      [ENEMIES.MOSQUITO, ENEMIES.MOSQUITO, ENEMIES.MOSQUITO, ENEMIES.MOSQUITO, ENEMIES.MOSQUITO, ENEMIES.MOSQUITO],
      [ENEMIES.CROW, ENEMIES.CROW],
      [ENEMIES.WILD_BOAR],
      [ENEMIES.RED_SOLDIER_ANT],
      [ENEMIES.RED_SOLDIER_ANT, ENEMIES.RED_SOLDIER_ANT],
      [ENEMIES.MOSQUITO, ENEMIES.MOSQUITO, ENEMIES.MOSQUITO, ENEMIES.RED_SOLDIER_ANT],
      [ENEMIES.CROW, ENEMIES.CROW, ENEMIES.WILD_BOAR],
    ],
  },

  GREGMINSTER_AREA_2: {
    name: 'Gregminster Area 2',
    encounterRate: 8,
    areaType: 'World Map',
    encounters: [
      [ENEMIES.NINJA_MASTER, ENEMIES.NINJA_MASTER, ENEMIES.NINJA_MASTER, ENEMIES.SIMURGH],
      [ENEMIES.NINJA_MASTER],
      [ENEMIES.NINJA_MASTER, ENEMIES.NINJA_MASTER],
      [ENEMIES.NINJA_MASTER, ENEMIES.NINJA_MASTER, ENEMIES.NINJA_MASTER],
      [ENEMIES.SIMURGH],
      [ENEMIES.SIMURGH, ENEMIES.SIMURGH],
      [ENEMIES.SIMURGH, ENEMIES.SIMURGH, ENEMIES.SIMURGH],
      [ENEMIES.ORC],
      [ENEMIES.ORC, ENEMIES.ORC],
      [ENEMIES.ORC, ENEMIES.ORC, ENEMIES.ORC],
      [ENEMIES.NINJA_MASTER, ENEMIES.NINJA_MASTER, ENEMIES.NINJA_MASTER, ENEMIES.ORC],
      [ENEMIES.NINJA_MASTER, ENEMIES.NINJA_MASTER, ENEMIES.NINJA_MASTER, ENEMIES.SIMURGH, ENEMIES.SIMURGH],
      [ENEMIES.NINJA_MASTER, ENEMIES.NINJA_MASTER, ENEMIES.NINJA_MASTER, ENEMIES.ORC, ENEMIES.ORC],
    ],
  },

  GREGMINSTER_PALACE: {
    name: 'Gregminster Palace',
    encounterRate: 3,
    areaType: 'Dungeon',
    encounters: [
      [ENEMIES.COLOSSUS],
      [ENEMIES.IMPERIAL_GUARDS_SABRE, ENEMIES.IMPERIAL_GUARDS_SABRE],
      [ENEMIES.IMPERIAL_GUARDS_SABRE, ENEMIES.IMPERIAL_GUARDS_SABRE, ENEMIES.IMPERIAL_GUARDS_SABRE],
      [ENEMIES.IMPERIAL_GUARDS_SWORD, ENEMIES.IMPERIAL_GUARDS_SWORD],
      [ENEMIES.PHANTOM],
      [ENEMIES.PHANTOM, ENEMIES.PHANTOM],
      [ENEMIES.PHANTOM, ENEMIES.PHANTOM, ENEMIES.PHANTOM],
      [ENEMIES.IMPERIAL_GUARDS_SABRE, ENEMIES.IMPERIAL_GUARDS_SABRE, ENEMIES.IMPERIAL_GUARDS_SABRE, ENEMIES.EKIDONNA],
      [ENEMIES.PHANTOM, ENEMIES.PHANTOM, ENEMIES.PHANTOM, ENEMIES.EKIDONNA],
      [ENEMIES.PHANTOM, ENEMIES.PHANTOM, ENEMIES.PHANTOM, ENEMIES.COLOSSUS],
      [ENEMIES.IMPERIAL_GUARDS_SABRE, ENEMIES.IMPERIAL_GUARDS_SABRE, ENEMIES.IMPERIAL_GUARDS_SWORD, ENEMIES.COLOSSUS],
    ],
    // Golden Hydra's three heads are fought together as one battle.
    scripted: [[BOSSES.GOLDEN_HYDRA_RIGHT, BOSSES.GOLDEN_HYDRA_MIDDLE, BOSSES.GOLDEN_HYDRA_LEFT]],
  },

  KALEKKA: {
    name: 'Kalekka',
    encounterRate: 4,
    areaType: 'Dungeon',
    encounters: [
      [ENEMIES.DEMON_HOUND],
      [ENEMIES.HAWK_MAN, ENEMIES.HAWK_MAN],
      [ENEMIES.HAWK_MAN, ENEMIES.HAWK_MAN, ENEMIES.HAWK_MAN],
      [ENEMIES.HAWK_MAN, ENEMIES.HAWK_MAN, ENEMIES.HAWK_MAN, ENEMIES.HAWK_MAN],
      [ENEMIES.SHADOW, ENEMIES.SHADOW],
      [ENEMIES.SHADOW, ENEMIES.SHADOW, ENEMIES.SHADOW, ENEMIES.SHADOW],
      [ENEMIES.HAWK_MAN, ENEMIES.HAWK_MAN, ENEMIES.SHADOW, ENEMIES.SHADOW],
    ],
  },

  KALEKKA_AREA: {
    name: 'Kalekka Area',
    encounterRate: 8,
    areaType: 'World Map',
    encounters: [
      [ENEMIES.DAGON],
      [ENEMIES.DAGON, ENEMIES.DAGON],
      [ENEMIES.DAGON, ENEMIES.DAGON, ENEMIES.DAGON],
      [ENEMIES.GRIZZLY_BEAR, ENEMIES.GRIZZLY_BEAR],
      [ENEMIES.GRIZZLY_BEAR, ENEMIES.GRIZZLY_BEAR, ENEMIES.GRIZZLY_BEAR],
      [ENEMIES.DAGON, ENEMIES.DAGON, ENEMIES.SIREN_1],
      [ENEMIES.GRIZZLY_BEAR],
      [ENEMIES.SIREN_1],
      [ENEMIES.SIREN_1, ENEMIES.SIREN_1],
    ],
  },

  LEPANTS_MANSION: {
    name: "Lepant's Mansion",
    encounterRate: 2,
    areaType: 'Dungeon',
    encounters: [
      [ENEMIES.SLOT_MAN],
      [ENEMIES.ROBOT_SOLDIER_SPEAR, ENEMIES.ROBOT_SOLDIER_SWORD, ENEMIES.ROBOT_SOLDIER_SWORD],
      [
        ENEMIES.ROBOT_SOLDIER_SWORD,
        ENEMIES.ROBOT_SOLDIER_SWORD,
        ENEMIES.ROBOT_SOLDIER_SWORD,
        ENEMIES.ROBOT_SOLDIER_SPEAR,
        ENEMIES.ROBOT_SOLDIER_SPEAR,
        ENEMIES.ROBOT_SOLDIER_SPEAR,
      ],
    ],
  },

  LORIMAR_AREA: {
    name: 'Lorimar Area',
    encounterRate: 8,
    areaType: 'World Map',
    encounters: [
      [ENEMIES.HELL_HOUND_1, ENEMIES.HELL_HOUND_1, ENEMIES.HELL_HOUND_1, ENEMIES.WHIP_WOLF],
      [ENEMIES.GRAVE_MASTER],
      [ENEMIES.GRAVE_MASTER, ENEMIES.GRAVE_MASTER],
      [ENEMIES.HELL_HOUND_1],
      [ENEMIES.HELL_HOUND_1, ENEMIES.HELL_HOUND_1],
      [ENEMIES.HELL_HOUND_1, ENEMIES.HELL_HOUND_1, ENEMIES.HELL_HOUND_1],
      [ENEMIES.SORCERER],
      [ENEMIES.SORCERER, ENEMIES.SORCERER],
      [ENEMIES.HELL_HOUND_1, ENEMIES.HELL_HOUND_1, ENEMIES.HELL_HOUND_1, ENEMIES.SORCERER],
      [ENEMIES.HELL_HOUND_1, ENEMIES.HELL_HOUND_1, ENEMIES.HELL_HOUND_1, ENEMIES.GRAVE_MASTER],
      [ENEMIES.HELL_HOUND_1, ENEMIES.HELL_HOUND_1, ENEMIES.HELL_HOUND_1, ENEMIES.GRAVE_MASTER, ENEMIES.GRAVE_MASTER],
    ],
  },

  MAGICIANS_ISLAND: {
    name: "Magician's Island",
    encounterRate: 4,
    areaType: 'Dungeon',
    encounters: [
      [ENEMIES.HOLLY_BOY_1, ENEMIES.HOLLY_BOY_1, ENEMIES.HOLLY_BOY_1, ENEMIES.HOLLY_BOY_1],
      [ENEMIES.HOLLY_BOY_1, ENEMIES.HOLLY_BOY_1, ENEMIES.HOLLY_BOY_1, ENEMIES.HOLLY_BOY_1, ENEMIES.HOLLY_BOY_1, ENEMIES.HOLLY_BOY_1],
      [ENEMIES.HOLLY_BOY_1, ENEMIES.HOLLY_BOY_1, ENEMIES.HOLLY_BOY_1, ENEMIES.FUR_FUR, ENEMIES.FUR_FUR],
      [ENEMIES.FUR_FUR, ENEMIES.FUR_FUR],
      [ENEMIES.HOLLY_BOY_1, ENEMIES.HOLLY_BOY_1, ENEMIES.HOLLY_BOY_1, ENEMIES.HOLLY_BOY_1],
      [ENEMIES.HOLLY_BOY_1, ENEMIES.HOLLY_BOY_1, ENEMIES.HOLLY_BOY_1, ENEMIES.HOLLY_BOY_1, ENEMIES.HOLLY_BOY_1, ENEMIES.HOLLY_BOY_1],
      [ENEMIES.HOLLY_BOY_1, ENEMIES.HOLLY_BOY_1, ENEMIES.HOLLY_BOY_1, ENEMIES.FUR_FUR, ENEMIES.FUR_FUR],
      [ENEMIES.FUR_FUR, ENEMIES.FUR_FUR],
      [ENEMIES.FUR_FUR, ENEMIES.FUR_FUR, ENEMIES.FUR_FUR],
    ],
    scripted: [[BOSSES.GOLEM]],
  },

  MORAVIA_AREA: {
    name: 'Moravia Area',
    encounterRate: 8,
    areaType: 'World Map',
    encounters: [
      [ENEMIES.RABBIT_BIRD],
      [ENEMIES.RABBIT_BIRD, ENEMIES.RABBIT_BIRD],
      [ENEMIES.RABBIT_BIRD, ENEMIES.RABBIT_BIRD, ENEMIES.RABBIT_BIRD],
      [ENEMIES.MIRAGE],
      [ENEMIES.MIRAGE, ENEMIES.MIRAGE],
      [ENEMIES.MIRAGE, ENEMIES.MIRAGE, ENEMIES.MIRAGE],
      [ENEMIES.EARTH_GOLEM],
      [ENEMIES.EARTH_GOLEM, ENEMIES.EARTH_GOLEM],
      [ENEMIES.RABBIT_BIRD, ENEMIES.RABBIT_BIRD, ENEMIES.RABBIT_BIRD, ENEMIES.EARTH_GOLEM],
      [ENEMIES.MIRAGE, ENEMIES.MIRAGE, ENEMIES.MIRAGE, ENEMIES.EARTH_GOLEM],
      [ENEMIES.RABBIT_BIRD, ENEMIES.RABBIT_BIRD, ENEMIES.RABBIT_BIRD, ENEMIES.EARTH_GOLEM, ENEMIES.EARTH_GOLEM],
      [ENEMIES.MIRAGE, ENEMIES.MIRAGE, ENEMIES.MIRAGE, ENEMIES.EARTH_GOLEM, ENEMIES.EARTH_GOLEM],
    ],
  },

  MORAVIA_CASTLE: {
    name: 'Moravia Castle',
    encounterRate: 3,
    areaType: 'Dungeon',
    encounters: [
      [ENEMIES.HELL_HOUND_2, ENEMIES.HELL_HOUND_2, ENEMIES.HELL_HOUND_2, ENEMIES.WHIP_MASTER],
      [ENEMIES.HELL_HOUND_2, ENEMIES.HELL_HOUND_2, ENEMIES.HELL_HOUND_2, ENEMIES.WHIP_MASTER, ENEMIES.WHIP_MASTER],
      [ENEMIES.HELL_HOUND_2, ENEMIES.HELL_HOUND_2, ENEMIES.HELL_HOUND_2, ENEMIES.HELL_HOUND_2, ENEMIES.HELL_HOUND_2, ENEMIES.WHIP_MASTER],
      [ENEMIES.NINJA],
      [ENEMIES.NINJA, ENEMIES.NINJA],
      [ENEMIES.MAGUS],
      [ENEMIES.MAGUS, ENEMIES.MAGUS],
      [ENEMIES.ELITE_SOLDIER_1],
      [ENEMIES.ELITE_SOLDIER_1, ENEMIES.ELITE_SOLDIER_1],
      [ENEMIES.HELL_HOUND_2, ENEMIES.HELL_HOUND_2, ENEMIES.HELL_HOUND_2, ENEMIES.MAGUS, ENEMIES.WHIP_MASTER],
      [ENEMIES.NINJA, ENEMIES.NINJA, ENEMIES.NINJA, ENEMIES.MAGUS],
      [ENEMIES.ELITE_SOLDIER_1, ENEMIES.ELITE_SOLDIER_1, ENEMIES.ELITE_SOLDIER_1, ENEMIES.MAGUS],
      [ENEMIES.HELL_HOUND_2, ENEMIES.HELL_HOUND_2, ENEMIES.HELL_HOUND_2, ENEMIES.NINJA, ENEMIES.NINJA],
      [ENEMIES.NINJA, ENEMIES.NINJA, ENEMIES.NINJA, ENEMIES.MAGUS, ENEMIES.MAGUS],
      [ENEMIES.ELITE_SOLDIER_1, ENEMIES.ELITE_SOLDIER_1, ENEMIES.NINJA, ENEMIES.MAGUS, ENEMIES.MAGUS],
      [ENEMIES.HELL_HOUND_2, ENEMIES.HELL_HOUND_2, ENEMIES.HELL_HOUND_2, ENEMIES.ELITE_SOLDIER_1, ENEMIES.ELITE_SOLDIER_1, ENEMIES.WHIP_MASTER],
    ],
  },

  MT_SEIFU: {
    name: 'Mt. Seifu',
    encounterRate: 2,
    areaType: 'Dungeon',
    encounters: [
      [ENEMIES.SOLDIER_ANT, ENEMIES.SOLDIER_ANT, ENEMIES.SOLDIER_ANT, ENEMIES.SOLDIER_ANT, ENEMIES.SOLDIER_ANT, ENEMIES.SOLDIER_ANT],
      [ENEMIES.BANDIT_RED, ENEMIES.BANDIT_RED],
      [ENEMIES.BANDIT_YELLOW, ENEMIES.BANDIT_GREEN, ENEMIES.BANDIT_GREEN],
      [ENEMIES.BLACK_WILD_BOAR, ENEMIES.BLACK_WILD_BOAR],
      [ENEMIES.BANDIT_GREEN, ENEMIES.BANDIT_GREEN],
    ],
    scripted: [
      [BOSSES.QUEEN_ANT],
      [BOSSES.VARKAS, BOSSES.SYDONIA],
      // "Seifu 5 Bandits" ambush, from lib/enemies.js's "Other Enemies" section.
      [ENEMIES.BANDIT_GREEN, ENEMIES.BANDIT_GREEN, ENEMIES.BANDIT_RED, ENEMIES.BANDIT_RED, ENEMIES.BANDIT_YELLOW],
    ],
  },

  MT_TIGERWOLF: {
    name: 'Mt. Tigerwolf',
    encounterRate: 3,
    areaType: 'Dungeon',
    encounters: [
      [ENEMIES.SLASHER_RABBIT, ENEMIES.SLASHER_RABBIT, ENEMIES.SLASHER_RABBIT, ENEMIES.SLASHER_RABBIT, ENEMIES.SLASHER_RABBIT, ENEMIES.SLASHER_RABBIT],
      [ENEMIES.GIANT_SNAIL, ENEMIES.GIANT_SNAIL],
      [ENEMIES.KILLER_SLIME, ENEMIES.KILLER_SLIME, ENEMIES.KILLER_SLIME],
      [ENEMIES.KILLER_SLIME, ENEMIES.KILLER_SLIME, ENEMIES.KILLER_SLIME],
      [ENEMIES.GIANT_SNAIL],
    ],
  },

  NECLORDS_CASTLE: {
    name: "Neclord's Castle",
    encounterRate: 2,
    areaType: 'Dungeon',
    encounters: [
      [ENEMIES.DEMON_SORCERER],
      [ENEMIES.HELL_UNICORN],
      [ENEMIES.DEMON_SORCERER, ENEMIES.DEMON_SORCERER],
      [ENEMIES.LARVAE],
      [ENEMIES.LARVAE, ENEMIES.LARVAE],
      [ENEMIES.LARVAE, ENEMIES.LARVAE, ENEMIES.LARVAE],
      [ENEMIES.LARVAE, ENEMIES.LARVAE, ENEMIES.LARVAE, ENEMIES.DEMON_SORCERER],
      [ENEMIES.LARVAE, ENEMIES.LARVAE, ENEMIES.LARVAE, ENEMIES.HELL_UNICORN],
      [ENEMIES.LARVAE, ENEMIES.LARVAE, ENEMIES.LARVAE, ENEMIES.DEMON_SORCERER, ENEMIES.HELL_UNICORN],
    ],
    scripted: [[BOSSES.NECLORD]],
  },

  PANNU_YAKUTA_AREA: {
    name: 'Pannu Yakuta Area',
    encounterRate: 8,
    areaType: 'World Map',
    encounters: [
      [ENEMIES.KOBOLD_BOW, ENEMIES.KOBOLD_BOW],
      [ENEMIES.KOBOLD_SWORD, ENEMIES.KOBOLD_SWORD, ENEMIES.KOBOLD_SWORD],
      [ENEMIES.KOBOLD_SWORD, ENEMIES.KOBOLD_SWORD, ENEMIES.KOBOLD_SWORD, ENEMIES.KOBOLD_MAGE],
      [ENEMIES.KOBOLD_BOW, ENEMIES.KOBOLD_BOW, ENEMIES.KOBOLD_BOW, ENEMIES.KOBOLD_MAGE],
      [ENEMIES.KOBOLD_BOW, ENEMIES.KOBOLD_BOW, ENEMIES.STRONG_ARM, ENEMIES.KOBOLD_MAGE],
      [ENEMIES.KOBOLD_SWORD, ENEMIES.KOBOLD_SWORD, ENEMIES.KOBOLD_SWORD, ENEMIES.KOBOLD_MAGE, ENEMIES.KOBOLD_MAGE],
      [ENEMIES.KOBOLD_BOW, ENEMIES.KOBOLD_BOW, ENEMIES.KOBOLD_BOW, ENEMIES.KOBOLD_MAGE, ENEMIES.KOBOLD_MAGE],
      [ENEMIES.KOBOLD_SWORD, ENEMIES.KOBOLD_SWORD, ENEMIES.STRONG_ARM, ENEMIES.KOBOLD_MAGE, ENEMIES.KOBOLD_MAGE],
    ],
  },

  PANNU_YAKUTA: {
    name: 'Pannu Yakuta',
    encounterRate: 2,
    areaType: 'Dungeon',
    encounters: [
      [ENEMIES.VETERAN_SOLDIER_SPEAR, ENEMIES.VETERAN_SOLDIER_SPEAR, ENEMIES.VETERAN_SOLDIER_SPEAR],
      [ENEMIES.DEVIL_ARMOR],
      [ENEMIES.DEVIL_SHIELD, ENEMIES.DEVIL_SHIELD, ENEMIES.DEVIL_SHIELD, ENEMIES.DEVIL_ARMOR],
      [ENEMIES.VETERAN_SOLDIER_SABRE, ENEMIES.VETERAN_SOLDIER_SABRE],
      [ENEMIES.VETERAN_SOLDIER_SABRE, ENEMIES.VETERAN_SOLDIER_SABRE, ENEMIES.VETERAN_SOLDIER_SABRE],
      [ENEMIES.VETERAN_SOLDIER_BOW, ENEMIES.VETERAN_SOLDIER_BOW, ENEMIES.VETERAN_SOLDIER_BOW],
      [ENEMIES.VETERAN_SOLDIER_SABRE, ENEMIES.VETERAN_SOLDIER_SPEAR, ENEMIES.VETERAN_SOLDIER_BOW, ENEMIES.VETERAN_SOLDIER_BOW],
      [
        ENEMIES.VETERAN_SOLDIER_SABRE,
        ENEMIES.VETERAN_SOLDIER_SPEAR,
        ENEMIES.VETERAN_SOLDIER_BOW,
        ENEMIES.VETERAN_SOLDIER_BOW,
        ENEMIES.VETERAN_SOLDIER_BOW,
      ],
      [ENEMIES.DEVIL_SHIELD, ENEMIES.DEVIL_SHIELD],
      [ENEMIES.DEVIL_SHIELD, ENEMIES.DEVIL_SHIELD, ENEMIES.DEVIL_SHIELD],
    ],
    scripted: [[BOSSES.DRAGON]],
  },

  SCARLETICIA_AREA: {
    name: 'Scarleticia Area',
    encounterRate: 8,
    areaType: 'World Map',
    encounters: [
      [ENEMIES.HOLLY_FAIRY],
      [ENEMIES.HOLLY_FAIRY, ENEMIES.HOLLY_FAIRY],
      [ENEMIES.HOLLY_FAIRY, ENEMIES.HOLLY_FAIRY, ENEMIES.HOLLY_FAIRY],
      [ENEMIES.MAD_IVY],
      [ENEMIES.MAD_IVY, ENEMIES.MAD_IVY],
      [ENEMIES.MAD_IVY, ENEMIES.MAD_IVY, ENEMIES.MAD_IVY],
      [ENEMIES.CREEPER],
      [ENEMIES.CREEPER, ENEMIES.CREEPER],
      [ENEMIES.CREEPER, ENEMIES.CREEPER, ENEMIES.CREEPER],
      [ENEMIES.HOLLY_FAIRY, ENEMIES.HOLLY_FAIRY, ENEMIES.HOLLY_FAIRY, ENEMIES.CREEPER],
      [ENEMIES.HOLLY_FAIRY, ENEMIES.HOLLY_FAIRY, ENEMIES.HOLLY_FAIRY, ENEMIES.MAD_IVY],
      [ENEMIES.MAD_IVY, ENEMIES.MAD_IVY, ENEMIES.MAD_IVY, ENEMIES.CREEPER],
    ],
  },

  SCARLETICIA: {
    name: 'Scarleticia',
    encounterRate: 3,
    areaType: 'Dungeon',
    encounters: [
      [ENEMIES.MAD_IVY, ENEMIES.MAD_IVY],
      [ENEMIES.CREEPER, ENEMIES.CREEPER],
      [ENEMIES.CREEPER, ENEMIES.CREEPER, ENEMIES.CREEPER],
      [ENEMIES.CREEPER, ENEMIES.CREEPER, ENEMIES.CREEPER, ENEMIES.CREEPER, ENEMIES.CREEPER, ENEMIES.CREEPER],
      [ENEMIES.NIGHTMARE],
      [ENEMIES.CREEPER, ENEMIES.CREEPER, ENEMIES.CREEPER, ENEMIES.NIGHTMARE],
    ],
  },

  SEEK_VALLEY: {
    name: 'Seek Valley',
    encounterRate: 2,
    areaType: 'Dungeon',
    encounters: [
      [ENEMIES.IVY],
      [ENEMIES.IVY, ENEMIES.IVY],
      [ENEMIES.IVY, ENEMIES.IVY, ENEMIES.IVY],
      [ENEMIES.ROCK_BUSTER],
      [ENEMIES.ROCK_BUSTER, ENEMIES.ROCK_BUSTER],
      [ENEMIES.ROCK_BUSTER, ENEMIES.ROCK_BUSTER, ENEMIES.ROCK_BUSTER],
      [ENEMIES.WYVERN],
      [ENEMIES.QUEEN_ANT],
      [ENEMIES.IVY, ENEMIES.IVY, ENEMIES.ROCK_BUSTER],
      [ENEMIES.IVY, ENEMIES.IVY, ENEMIES.WYVERN],
      [ENEMIES.ROCK_BUSTER, ENEMIES.ROCK_BUSTER, ENEMIES.QUEEN_ANT],
      [ENEMIES.ROCK_BUSTER, ENEMIES.ROCK_BUSTER, ENEMIES.WYVERN],
    ],
    scripted: [[BOSSES.CRYSTAL_CORE]],
  },

  SEIKA_AREA: {
    name: 'Seika Area',
    encounterRate: 8,
    areaType: 'World Map',
    encounters: [
      [ENEMIES.FLYING_SQUIRREL, ENEMIES.FLYING_SQUIRREL, ENEMIES.FLYING_SQUIRREL, ENEMIES.BEAST_COMMANDER],
      [ENEMIES.FLYING_SQUIRREL, ENEMIES.FLYING_SQUIRREL],
      [ENEMIES.FLYING_SQUIRREL, ENEMIES.FLYING_SQUIRREL, ENEMIES.FLYING_SQUIRREL, ENEMIES.FLYING_SQUIRREL, ENEMIES.FLYING_SQUIRREL, ENEMIES.FLYING_SQUIRREL],
      [ENEMIES.ROC],
      [ENEMIES.KILLER_RABBIT, ENEMIES.KILLER_RABBIT, ENEMIES.KILLER_RABBIT, ENEMIES.KILLER_RABBIT, ENEMIES.KILLER_RABBIT, ENEMIES.KILLER_RABBIT],
      [ENEMIES.ROC, ENEMIES.ROC],
      [ENEMIES.KILLER_RABBIT, ENEMIES.KILLER_RABBIT, ENEMIES.KILLER_RABBIT, ENEMIES.BEAST_COMMANDER],
      [ENEMIES.FLYING_SQUIRREL, ENEMIES.FLYING_SQUIRREL, ENEMIES.FLYING_SQUIRREL, ENEMIES.KILLER_RABBIT, ENEMIES.KILLER_RABBIT, ENEMIES.BEAST_COMMANDER],
    ],
  },

  SHASARAZADE_FORTRESS: {
    name: 'Shasarazade Fortress',
    encounterRate: 3,
    areaType: 'Dungeon',
    encounters: [
      [ENEMIES.ELITE_SOLDIER_2, ENEMIES.ELITE_SOLDIER_2, ENEMIES.ELITE_SOLDIER_2, ENEMIES.ELITE_SOLDIER_2],
      [ENEMIES.ELITE_SOLDIER_2, ENEMIES.ELITE_SOLDIER_2],
      [ENEMIES.ELITE_SOLDIER_2, ENEMIES.ELITE_SOLDIER_2, ENEMIES.ELITE_SOLDIER_2],
      [ENEMIES.SIREN_2, ENEMIES.SIREN_2],
      [ENEMIES.SIREN_2, ENEMIES.SIREN_2, ENEMIES.SIREN_2],
      [ENEMIES.SIREN_2, ENEMIES.SIREN_2, ENEMIES.SIREN_2, ENEMIES.SIREN_2],
      [ENEMIES.KERBEROS],
    ],
    scripted: [[BOSSES.SHELL_VENUS], [BOSSES.SONYA_SHULEN]],
  },

  SONIERE_PRISON: {
    name: 'Soniere Prison',
    encounterRate: 2,
    areaType: 'Dungeon',
    encounters: [
      [ENEMIES.DELF, ENEMIES.VIPERMAN],
      [ENEMIES.DELF, ENEMIES.DELF, ENEMIES.DELF, ENEMIES.VIPERMAN],
      [ENEMIES.RED_SLIME],
      [ENEMIES.RED_SLIME, ENEMIES.RED_SLIME, ENEMIES.RED_SLIME],
      [ENEMIES.RED_SLIME, ENEMIES.RED_SLIME, ENEMIES.RED_SLIME, ENEMIES.NIGHTMARE, ENEMIES.NIGHTMARE],
      [ENEMIES.NIGHTMARE],
      [ENEMIES.NIGHTMARE, ENEMIES.NIGHTMARE, ENEMIES.NIGHTMARE],
      [ENEMIES.RED_SLIME, ENEMIES.RED_SLIME, ENEMIES.RED_SLIME, ENEMIES.NIGHTMARE],
    ],
    // Veteran Soldier ambush groups, from lib/enemies.js's "Other Enemies" section.
    scripted: [
      [ENEMIES.VETERAN_SOLDIER_SPEAR, ENEMIES.VETERAN_SOLDIER_SPEAR, ENEMIES.VETERAN_SOLDIER_SPEAR],
      [ENEMIES.VETERAN_SOLDIER_BOW, ENEMIES.VETERAN_SOLDIER_SPEAR, ENEMIES.VETERAN_SOLDIER_SPEAR],
      [
        ENEMIES.VETERAN_SOLDIER_SPEAR,
        ENEMIES.VETERAN_SOLDIER_SPEAR,
        ENEMIES.VETERAN_SOLDIER_SPEAR,
        ENEMIES.VETERAN_SOLDIER_BOW,
        ENEMIES.VETERAN_SOLDIER_BOW,
      ],
      [
        ENEMIES.VETERAN_SOLDIER_BOW,
        ENEMIES.VETERAN_SOLDIER_SPEAR,
        ENEMIES.VETERAN_SOLDIER_SPEAR,
        ENEMIES.VETERAN_SOLDIER_SPEAR,
        ENEMIES.VETERAN_SOLDIER_BOW,
      ],
    ],
  },

  TORAN_LAKE_CASTLE: {
    name: 'Toran Lake Castle',
    encounterRate: 2,
    areaType: 'Dungeon',
    encounters: [
      [ENEMIES.OANNES, ENEMIES.OANNES],
      [ENEMIES.OANNES, ENEMIES.OANNES, ENEMIES.OANNES],
      [ENEMIES.GIANT_SLUG, ENEMIES.GIANT_SLUG],
      [ENEMIES.GIANT_SLUG, ENEMIES.GIANT_SLUG, ENEMIES.GIANT_SLUG],
      [ENEMIES.GHOST_ARMOR],
      [ENEMIES.GIANT_SLUG, ENEMIES.GIANT_SLUG, ENEMIES.GIANT_SLUG, ENEMIES.GHOST_ARMOR],
      [ENEMIES.OANNES, ENEMIES.OANNES, ENEMIES.OANNES, ENEMIES.GHOST_ARMOR],
    ],
    scripted: [[BOSSES.ZOMBIE_DRAGON]],
  },

  // Catch-all for scripted fights whose bestiary location isn't one of lib/enemies.js's
  // regular areas (Liberation Army HQ, Pirates' Fortress, Warrior's Village, Grady's
  // Mansion, Lenankamp, Kraze's Mansion, Kobold Village) or is ambiguous against an
  // existing area (plain "Seika"/"Gregminster" vs. our SEIKA_AREA/GREGMINSTER_PALACE).
  OTHER: {
    name: 'Other',
    encounterRate: 0,
    encounters: [],
    scripted: [
      [BOSSES.ASSASSIN], // Liberation Army HQ
      [BOSSES.ANJI, BOSSES.KANAK, BOSSES.LEONARDO], // Pirates' Fortress
      [BOSSES.NECLORD_L], // Warrior's Village
      [BOSSES.AIN_GIDE], // Gregminster
      [ENEMIES.EMPIRE_SOLDIER_SABER_1, ENEMIES.EMPIRE_SOLDIER_SABER_1], // Grady's Mansion
      [
        ENEMIES.EMPIRE_SOLDIER_SPEAR_1,
        ENEMIES.EMPIRE_SOLDIER_SPEAR_1,
        ENEMIES.EMPIRE_SOLDIER_SPEAR_1,
        ENEMIES.EMPIRE_SOLDIER_BOW_1,
        ENEMIES.EMPIRE_SOLDIER_BOW_1,
        ENEMIES.EMPIRE_CAPTAIN,
      ], // Grady's Mansion
      [
        ENEMIES.EMPIRE_SOLDIER_BOW_2,
        ENEMIES.EMPIRE_SOLDIER_BOW_2,
        ENEMIES.EMPIRE_SOLDIER_BOW_2,
        ENEMIES.EMPIRE_SOLDIER_BOW_2,
        ENEMIES.EMPIRE_SOLDIER_BOW_2,
      ], // Lenankamp
      [ENEMIES.EMPIRE_SOLDIER_SWORD_3, ENEMIES.EMPIRE_SOLDIER_SWORD_3, ENEMIES.EMPIRE_SOLDIER_SPEAR_3], // Seika
      [
        ENEMIES.EMPIRE_SOLDIER_SWORD_4,
        ENEMIES.EMPIRE_SOLDIER_SWORD_4,
        ENEMIES.EMPIRE_SOLDIER_SWORD_4,
        ENEMIES.EMPIRE_SOLDIER_SWORD_4,
        ENEMIES.EMPIRE_SOLDIER_SWORD_4,
        ENEMIES.EMPIRE_SOLDIER_SWORD_4,
      ], // Kraze's Mansion
      [
        ENEMIES.VETERAN_SOLDIER_SPEAR,
        ENEMIES.VETERAN_SOLDIER_SPEAR,
        ENEMIES.VETERAN_SOLDIER_SPEAR,
        ENEMIES.VETERAN_SOLDIER_SPEAR,
        ENEMIES.VETERAN_SOLDIER_SPEAR,
        ENEMIES.VETERAN_SOLDIER_SPEAR,
      ], // Kobold Village
      [ENEMIES.IMPERIAL_GUARDS_SWORD, ENEMIES.IMPERIAL_GUARDS_SWORD, ENEMIES.IMPERIAL_GUARDS_SWORD, ENEMIES.IMPERIAL_GUARDS_SABRE], // Gregminster
      [
        ENEMIES.IMPERIAL_GUARDS_SWORD,
        ENEMIES.IMPERIAL_GUARDS_SWORD,
        ENEMIES.IMPERIAL_GUARDS_SABRE,
        ENEMIES.IMPERIAL_GUARDS_SABRE,
        ENEMIES.IMPERIAL_GUARDS_SABRE,
      ], // Gregminster
    ],
  },
};

/**
 * Builds a display name for an encounter from its party, e.g. "2 Banshee 1 Clay Doll".
 * Groups by identity (preserving first-occurrence order) and prefers each entry's
 * nickname over its name, so colloquial names (e.g. "Red Machine") fall out automatically.
 * @param {EnemyEntry[]} party
 * @returns {string}
 */
export function getEncounterName(party) {
  const order = [];
  const counts = new Map();
  for (const entry of party) {
    if (!counts.has(entry)) order.push(entry);
    counts.set(entry, (counts.get(entry) ?? 0) + 1);
  }
  return order.map(entry => `${counts.get(entry)} ${entry.nickname ?? entry.name}`).join(' ');
}
