import { ENEMIES } from './Enemies.js';
import { ENEMY_KEYS } from '../Keys.js';

/** @typedef {import('../Keys.js').EnemyKey} EnemyKey */

/**
 * @typedef {'Dungeon'|'World Map'} AreaType
 */

/**
 * A group's starting formation: index + 1 is the formation slot (combatant_rec+0x44; 1-3 front
 * row, 4-6 back row), null is an empty slot, and trailing empty slots are omitted. Setup doesn't
 * pack enemies by size, so gaps have to be written out (e.g. Neclord's Castle's Demon Sorcerer
 * in slot 6). Combatant order is slot order with the empty slots skipped.
 * @typedef {(EnemyKey | null)[]} Formation
 */

/**
 * @typedef {Object} Area
 * @property {string} name
 * @property {number} encounterRate
 * @property {AreaType} [areaType]
 * @property {Formation[]} encounters - Possible random-encounter party compositions.
 * @property {Formation[]} [scripted] - Fixed/forced fights tied to this area (bosses, ambushes), not part of the random encounter table.
 */

/** @satisfies {Record<string, Area>} */
export const AREAS = {
  CAVE_OF_THE_PAST: {
    name: 'Cave of the Past',
    encounterRate: 2,
    areaType: 'Dungeon',
    encounters: [
      [null, ENEMY_KEYS.BANSHEE],
      [ENEMY_KEYS.BANSHEE, null, ENEMY_KEYS.BANSHEE],
      [ENEMY_KEYS.BANSHEE, null, ENEMY_KEYS.BANSHEE, null, ENEMY_KEYS.BANSHEE],
      [null, ENEMY_KEYS.CLAY_DOLL],
      [ENEMY_KEYS.CLAY_DOLL, null, ENEMY_KEYS.CLAY_DOLL],
      [ENEMY_KEYS.CLAY_DOLL, null, ENEMY_KEYS.CLAY_DOLL, null, ENEMY_KEYS.CLAY_DOLL],
      [ENEMY_KEYS.CLAY_DOLL, null, ENEMY_KEYS.BANSHEE],
      [ENEMY_KEYS.BANSHEE, null, ENEMY_KEYS.BANSHEE, null, ENEMY_KEYS.CLAY_DOLL],
      [ENEMY_KEYS.RED_ELEMENTAL, ENEMY_KEYS.RED_ELEMENTAL, ENEMY_KEYS.RED_ELEMENTAL, null, ENEMY_KEYS.CLAY_DOLL],
      [ENEMY_KEYS.RED_ELEMENTAL, ENEMY_KEYS.RED_ELEMENTAL, ENEMY_KEYS.RED_ELEMENTAL, null, ENEMY_KEYS.BANSHEE],
      [
        ENEMY_KEYS.RED_ELEMENTAL,
        ENEMY_KEYS.RED_ELEMENTAL,
        ENEMY_KEYS.RED_ELEMENTAL,
        ENEMY_KEYS.BANSHEE,
        null,
        ENEMY_KEYS.BANSHEE,
      ],
    ],
  },

  DRAGON_KNIGHTS_AREA: {
    name: 'Dragon Knights Area',
    encounterRate: 8,
    areaType: 'World Map',
    encounters: [
      [ENEMY_KEYS.IVY],
      [ENEMY_KEYS.IVY, ENEMY_KEYS.IVY],
      [ENEMY_KEYS.IVY, ENEMY_KEYS.IVY, ENEMY_KEYS.IVY],
      [null, ENEMY_KEYS.SHADOW_MAN],
      [ENEMY_KEYS.SHADOW_MAN, null, ENEMY_KEYS.SHADOW_MAN],
      [ENEMY_KEYS.MIRAGE, null, ENEMY_KEYS.MIRAGE],
      [ENEMY_KEYS.MIRAGE, ENEMY_KEYS.MIRAGE, ENEMY_KEYS.MIRAGE, null, ENEMY_KEYS.MIRAGE],
      [ENEMY_KEYS.IVY, ENEMY_KEYS.IVY, ENEMY_KEYS.IVY, ENEMY_KEYS.SHADOW_MAN, null, ENEMY_KEYS.MIRAGE],
    ],
  },

  DRAGONS_DEN: {
    name: "Dragon's Den",
    encounterRate: 3,
    areaType: 'Dungeon',
    encounters: [
      [null, ENEMY_KEYS.SUNSHINE_KING],
      [null, ENEMY_KEYS.MAGIC_SHIELD],
      [ENEMY_KEYS.MAGIC_SHIELD, null, ENEMY_KEYS.MAGIC_SHIELD],
      [ENEMY_KEYS.MAGIC_SHIELD, ENEMY_KEYS.MAGIC_SHIELD, ENEMY_KEYS.MAGIC_SHIELD],
      [ENEMY_KEYS.SUNSHINE_KING, null, ENEMY_KEYS.MAGIC_SHIELD],
      [
        ENEMY_KEYS.BLACK_ELEMENTAL,
        ENEMY_KEYS.BLACK_ELEMENTAL,
        ENEMY_KEYS.BLACK_ELEMENTAL,
        null,
        ENEMY_KEYS.SUNSHINE_KING,
      ],
      [
        ENEMY_KEYS.BLACK_ELEMENTAL,
        ENEMY_KEYS.BLACK_ELEMENTAL,
        ENEMY_KEYS.BLACK_ELEMENTAL,
        ENEMY_KEYS.MAGIC_SHIELD,
        null,
        ENEMY_KEYS.MAGIC_SHIELD,
      ],
    ],
  },

  DWARVES_TRAIL: {
    name: 'Dwarves Trail',
    encounterRate: 2,
    areaType: 'Dungeon',
    encounters: [
      [ENEMY_KEYS.DWARF, ENEMY_KEYS.DWARF, ENEMY_KEYS.DWARF, ENEMY_KEYS.EAGLE_MAN, null, ENEMY_KEYS.EAGLE_MAN],
      [null, ENEMY_KEYS.EAGLE_MAN],
      [ENEMY_KEYS.EAGLE_MAN, null, ENEMY_KEYS.EAGLE_MAN],
      [ENEMY_KEYS.EAGLE_MAN, null, ENEMY_KEYS.EAGLE_MAN, null, ENEMY_KEYS.EAGLE_MAN],
      [null, ENEMY_KEYS.DWARF],
      [ENEMY_KEYS.DWARF, null, ENEMY_KEYS.DWARF],
      [ENEMY_KEYS.DWARF, ENEMY_KEYS.DWARF, ENEMY_KEYS.DWARF],
      [null, ENEMY_KEYS.DEATH_BOAR],
      [ENEMY_KEYS.DEATH_BOAR, null, ENEMY_KEYS.DEATH_BOAR],
      [ENEMY_KEYS.DEATH_BOAR, ENEMY_KEYS.DEATH_BOAR, ENEMY_KEYS.DEATH_BOAR],
      [ENEMY_KEYS.DEATH_BOAR, ENEMY_KEYS.DEATH_BOAR, ENEMY_KEYS.DEATH_BOAR, null, ENEMY_KEYS.EAGLE_MAN],
      [ENEMY_KEYS.DEATH_BOAR, ENEMY_KEYS.DEATH_BOAR, ENEMY_KEYS.DEATH_BOAR, null, ENEMY_KEYS.DWARF],
      [
        ENEMY_KEYS.DEATH_BOAR,
        ENEMY_KEYS.DEATH_BOAR,
        ENEMY_KEYS.DEATH_BOAR,
        ENEMY_KEYS.EAGLE_MAN,
        null,
        ENEMY_KEYS.EAGLE_MAN,
      ],
      [
        ENEMY_KEYS.DEATH_BOAR,
        ENEMY_KEYS.DEATH_BOAR,
        ENEMY_KEYS.DEATH_BOAR,
        ENEMY_KEYS.EAGLE_MAN,
        null,
        ENEMY_KEYS.DWARF,
      ],
    ],
  },

  DWARVES_VAULT: {
    name: 'Dwarves Vault',
    encounterRate: 2,
    areaType: 'Dungeon',
    encounters: [
      [null, ENEMY_KEYS.DEATH_MACHINE_SWORD],
      [ENEMY_KEYS.DEATH_MACHINE_SWORD, null, ENEMY_KEYS.DEATH_MACHINE_SWORD],
      [ENEMY_KEYS.DEATH_MACHINE_SWORD, ENEMY_KEYS.DEATH_MACHINE_SWORD, ENEMY_KEYS.DEATH_MACHINE_SWORD],
      [null, ENEMY_KEYS.DEATH_MACHINE_SPEAR],
      [ENEMY_KEYS.DEATH_MACHINE_SPEAR, null, ENEMY_KEYS.DEATH_MACHINE_SPEAR],
      [ENEMY_KEYS.DEATH_MACHINE_SPEAR, ENEMY_KEYS.DEATH_MACHINE_SPEAR, ENEMY_KEYS.DEATH_MACHINE_SPEAR],
      [null, ENEMY_KEYS.CRIMSON_DWARF],
      [ENEMY_KEYS.CRIMSON_DWARF, null, ENEMY_KEYS.CRIMSON_DWARF],
      [ENEMY_KEYS.CRIMSON_DWARF, ENEMY_KEYS.CRIMSON_DWARF, ENEMY_KEYS.CRIMSON_DWARF],
      [ENEMY_KEYS.DEATH_BOAR, null, ENEMY_KEYS.DEATH_BOAR],
      [ENEMY_KEYS.DEATH_BOAR, ENEMY_KEYS.DEATH_BOAR, ENEMY_KEYS.DEATH_BOAR],
      [
        ENEMY_KEYS.CRIMSON_DWARF,
        ENEMY_KEYS.CRIMSON_DWARF,
        ENEMY_KEYS.CRIMSON_DWARF,
        null,
        ENEMY_KEYS.DEATH_MACHINE_SWORD,
      ],
      [
        ENEMY_KEYS.CRIMSON_DWARF,
        ENEMY_KEYS.CRIMSON_DWARF,
        ENEMY_KEYS.CRIMSON_DWARF,
        ENEMY_KEYS.DEATH_MACHINE_SWORD,
        null,
        ENEMY_KEYS.DEATH_MACHINE_SWORD,
      ],
      [
        ENEMY_KEYS.CRIMSON_DWARF,
        ENEMY_KEYS.CRIMSON_DWARF,
        ENEMY_KEYS.CRIMSON_DWARF,
        ENEMY_KEYS.DEATH_MACHINE_SWORD,
        ENEMY_KEYS.DEATH_MACHINE_SWORD,
        ENEMY_KEYS.DEATH_MACHINE_SWORD,
      ],
    ],
    scripted: [[ENEMY_KEYS.GIGANTES]],
  },

  GREAT_FOREST: {
    name: 'Great Forest',
    encounterRate: 2,
    areaType: 'Dungeon',
    encounters: [
      [ENEMY_KEYS.KOBOLD_SWORD],
      [ENEMY_KEYS.KOBOLD_SWORD, ENEMY_KEYS.KOBOLD_SWORD, ENEMY_KEYS.KOBOLD_SWORD],
      [
        ENEMY_KEYS.KOBOLD_SWORD,
        ENEMY_KEYS.KOBOLD_SWORD,
        ENEMY_KEYS.KOBOLD_SWORD,
        ENEMY_KEYS.KOBOLD_BOW,
        ENEMY_KEYS.KOBOLD_BOW,
        ENEMY_KEYS.KOBOLD_BOW,
      ],
      [ENEMY_KEYS.KOBOLD_BOW, ENEMY_KEYS.KOBOLD_BOW],
      [ENEMY_KEYS.HOLLY_SPIRIT, ENEMY_KEYS.HOLLY_BOY_2, ENEMY_KEYS.HOLLY_BOY_2],
      [
        ENEMY_KEYS.HOLLY_BOY_2,
        ENEMY_KEYS.HOLLY_BOY_2,
        ENEMY_KEYS.HOLLY_BOY_2,
        ENEMY_KEYS.HOLLY_SPIRIT,
        ENEMY_KEYS.HOLLY_BOY_2,
        ENEMY_KEYS.HOLLY_BOY_2,
      ],
      [
        ENEMY_KEYS.HOLLY_BOY_2,
        ENEMY_KEYS.HOLLY_BOY_2,
        ENEMY_KEYS.HOLLY_BOY_2,
        ENEMY_KEYS.HOLLY_SPIRIT,
        ENEMY_KEYS.HOLLY_SPIRIT,
        ENEMY_KEYS.HOLLY_SPIRIT,
      ],
      [
        ENEMY_KEYS.HOLLY_BOY_2,
        ENEMY_KEYS.HOLLY_BOY_2,
        ENEMY_KEYS.HOLLY_BOY_2,
        ENEMY_KEYS.HOLLY_BOY_2,
        ENEMY_KEYS.HOLLY_BOY_2,
        ENEMY_KEYS.HOLLY_BOY_2,
      ],
    ],
  },

  GREGMINSTER_AREA_1: {
    name: 'Gregminster Area 1',
    encounterRate: 8,
    areaType: 'World Map',
    encounters: [
      [ENEMY_KEYS.BONBON],
      [ENEMY_KEYS.BONBON, ENEMY_KEYS.BONBON, ENEMY_KEYS.BONBON],
      [
        ENEMY_KEYS.MOSQUITO,
        ENEMY_KEYS.MOSQUITO,
        ENEMY_KEYS.MOSQUITO,
        ENEMY_KEYS.MOSQUITO,
        ENEMY_KEYS.MOSQUITO,
        ENEMY_KEYS.MOSQUITO,
      ],
      [ENEMY_KEYS.CROW, ENEMY_KEYS.CROW],
      [ENEMY_KEYS.WILD_BOAR],
      [ENEMY_KEYS.RED_SOLDIER_ANT],
      [ENEMY_KEYS.RED_SOLDIER_ANT, ENEMY_KEYS.RED_SOLDIER_ANT],
      [ENEMY_KEYS.MOSQUITO, ENEMY_KEYS.MOSQUITO, ENEMY_KEYS.MOSQUITO, ENEMY_KEYS.RED_SOLDIER_ANT],
      [ENEMY_KEYS.WILD_BOAR, ENEMY_KEYS.CROW, ENEMY_KEYS.CROW],
    ],
  },

  GREGMINSTER_AREA_2: {
    name: 'Gregminster Area 2',
    encounterRate: 8,
    areaType: 'World Map',
    encounters: [
      [ENEMY_KEYS.NINJA_MASTER, ENEMY_KEYS.NINJA_MASTER, ENEMY_KEYS.NINJA_MASTER, ENEMY_KEYS.SIMURGH],
      [ENEMY_KEYS.NINJA_MASTER],
      [ENEMY_KEYS.NINJA_MASTER, ENEMY_KEYS.NINJA_MASTER],
      [ENEMY_KEYS.NINJA_MASTER, ENEMY_KEYS.NINJA_MASTER, ENEMY_KEYS.NINJA_MASTER],
      [ENEMY_KEYS.SIMURGH],
      [ENEMY_KEYS.SIMURGH, ENEMY_KEYS.SIMURGH],
      [ENEMY_KEYS.SIMURGH, ENEMY_KEYS.SIMURGH, ENEMY_KEYS.SIMURGH],
      [ENEMY_KEYS.ORC],
      [ENEMY_KEYS.ORC, ENEMY_KEYS.ORC],
      [ENEMY_KEYS.ORC, ENEMY_KEYS.ORC, ENEMY_KEYS.ORC],
      [ENEMY_KEYS.NINJA_MASTER, ENEMY_KEYS.NINJA_MASTER, ENEMY_KEYS.NINJA_MASTER, ENEMY_KEYS.ORC],
      [
        ENEMY_KEYS.NINJA_MASTER,
        ENEMY_KEYS.NINJA_MASTER,
        ENEMY_KEYS.NINJA_MASTER,
        ENEMY_KEYS.SIMURGH,
        ENEMY_KEYS.SIMURGH,
      ],
      [ENEMY_KEYS.NINJA_MASTER, ENEMY_KEYS.NINJA_MASTER, ENEMY_KEYS.NINJA_MASTER, ENEMY_KEYS.ORC, ENEMY_KEYS.ORC],
    ],
  },

  GREGMINSTER_PALACE: {
    name: 'Gregminster Palace',
    encounterRate: 3,
    areaType: 'Dungeon',
    encounters: [
      [ENEMY_KEYS.COLOSSUS],
      [ENEMY_KEYS.IMPERIAL_GUARDS_SABRE, ENEMY_KEYS.IMPERIAL_GUARDS_SABRE],
      [ENEMY_KEYS.IMPERIAL_GUARDS_SABRE, ENEMY_KEYS.IMPERIAL_GUARDS_SABRE, ENEMY_KEYS.IMPERIAL_GUARDS_SABRE],
      [ENEMY_KEYS.IMPERIAL_GUARDS_SWORD, ENEMY_KEYS.IMPERIAL_GUARDS_SWORD],
      [ENEMY_KEYS.PHANTOM],
      [ENEMY_KEYS.PHANTOM, null, ENEMY_KEYS.PHANTOM],
      [ENEMY_KEYS.PHANTOM, ENEMY_KEYS.PHANTOM, ENEMY_KEYS.PHANTOM],
      [
        ENEMY_KEYS.IMPERIAL_GUARDS_SABRE,
        ENEMY_KEYS.IMPERIAL_GUARDS_SABRE,
        ENEMY_KEYS.IMPERIAL_GUARDS_SABRE,
        null,
        ENEMY_KEYS.EKIDONNA,
      ],
      [ENEMY_KEYS.PHANTOM, ENEMY_KEYS.PHANTOM, ENEMY_KEYS.PHANTOM, null, ENEMY_KEYS.EKIDONNA],
      [ENEMY_KEYS.PHANTOM, ENEMY_KEYS.PHANTOM, ENEMY_KEYS.PHANTOM, null, ENEMY_KEYS.COLOSSUS],
      [
        ENEMY_KEYS.IMPERIAL_GUARDS_SWORD,
        ENEMY_KEYS.IMPERIAL_GUARDS_SABRE,
        ENEMY_KEYS.IMPERIAL_GUARDS_SWORD,
        null,
        ENEMY_KEYS.COLOSSUS,
      ],
    ],
    // Golden Hydra's three heads are fought together as one battle.
    scripted: [[ENEMY_KEYS.GOLDEN_HYDRA_RIGHT, ENEMY_KEYS.GOLDEN_HYDRA_MIDDLE, ENEMY_KEYS.GOLDEN_HYDRA_LEFT]],
  },

  KALEKKA: {
    name: 'Kalekka',
    encounterRate: 4,
    areaType: 'Dungeon',
    encounters: [
      [null, ENEMY_KEYS.DEMON_HOUND],
      [ENEMY_KEYS.HAWK_MAN, null, ENEMY_KEYS.HAWK_MAN],
      [ENEMY_KEYS.HAWK_MAN, null, ENEMY_KEYS.HAWK_MAN, ENEMY_KEYS.HAWK_MAN],
      [ENEMY_KEYS.HAWK_MAN, null, ENEMY_KEYS.HAWK_MAN, ENEMY_KEYS.HAWK_MAN, null, ENEMY_KEYS.HAWK_MAN],
      [ENEMY_KEYS.SHADOW, null, ENEMY_KEYS.SHADOW],
      [ENEMY_KEYS.SHADOW, null, ENEMY_KEYS.SHADOW, ENEMY_KEYS.SHADOW, null, ENEMY_KEYS.SHADOW],
      [ENEMY_KEYS.HAWK_MAN, null, ENEMY_KEYS.HAWK_MAN, ENEMY_KEYS.SHADOW, null, ENEMY_KEYS.SHADOW],
    ],
  },

  KALEKKA_AREA: {
    name: 'Kalekka Area',
    encounterRate: 8,
    areaType: 'World Map',
    encounters: [
      [null, ENEMY_KEYS.DAGON],
      [ENEMY_KEYS.DAGON, null, ENEMY_KEYS.DAGON],
      [ENEMY_KEYS.DAGON, null, ENEMY_KEYS.DAGON, null, ENEMY_KEYS.DAGON],
      [ENEMY_KEYS.GRIZZLY_BEAR, null, ENEMY_KEYS.GRIZZLY_BEAR],
      [ENEMY_KEYS.GRIZZLY_BEAR, null, ENEMY_KEYS.GRIZZLY_BEAR, null, ENEMY_KEYS.GRIZZLY_BEAR],
      [ENEMY_KEYS.DAGON, null, ENEMY_KEYS.DAGON, null, ENEMY_KEYS.SIREN_1],
      [null, ENEMY_KEYS.GRIZZLY_BEAR],
      [null, ENEMY_KEYS.SIREN_1],
      [ENEMY_KEYS.SIREN_1, null, ENEMY_KEYS.SIREN_1],
    ],
  },

  LEPANTS_MANSION: {
    name: "Lepant's Mansion",
    encounterRate: 2,
    areaType: 'Dungeon',
    encounters: [
      [ENEMY_KEYS.SLOT_MAN],
      [ENEMY_KEYS.ROBOT_SOLDIER_SPEAR, ENEMY_KEYS.ROBOT_SOLDIER_SWORD, ENEMY_KEYS.ROBOT_SOLDIER_SWORD],
      [
        ENEMY_KEYS.ROBOT_SOLDIER_SWORD,
        ENEMY_KEYS.ROBOT_SOLDIER_SWORD,
        ENEMY_KEYS.ROBOT_SOLDIER_SWORD,
        ENEMY_KEYS.ROBOT_SOLDIER_SPEAR,
        ENEMY_KEYS.ROBOT_SOLDIER_SPEAR,
        ENEMY_KEYS.ROBOT_SOLDIER_SPEAR,
      ],
    ],
  },

  LORIMAR_AREA: {
    name: 'Lorimar Area',
    encounterRate: 8,
    areaType: 'World Map',
    encounters: [
      [ENEMY_KEYS.HELL_HOUND_1, ENEMY_KEYS.HELL_HOUND_1, ENEMY_KEYS.HELL_HOUND_1, ENEMY_KEYS.WHIP_WOLF],
      [ENEMY_KEYS.GRAVE_MASTER],
      [ENEMY_KEYS.GRAVE_MASTER, ENEMY_KEYS.GRAVE_MASTER],
      [ENEMY_KEYS.HELL_HOUND_1],
      [ENEMY_KEYS.HELL_HOUND_1, ENEMY_KEYS.HELL_HOUND_1],
      [ENEMY_KEYS.HELL_HOUND_1, ENEMY_KEYS.HELL_HOUND_1, ENEMY_KEYS.HELL_HOUND_1],
      [ENEMY_KEYS.SORCERER],
      [ENEMY_KEYS.SORCERER, ENEMY_KEYS.SORCERER],
      [ENEMY_KEYS.HELL_HOUND_1, ENEMY_KEYS.HELL_HOUND_1, ENEMY_KEYS.HELL_HOUND_1, ENEMY_KEYS.SORCERER],
      [ENEMY_KEYS.HELL_HOUND_1, ENEMY_KEYS.HELL_HOUND_1, ENEMY_KEYS.HELL_HOUND_1, ENEMY_KEYS.GRAVE_MASTER],
      [
        ENEMY_KEYS.HELL_HOUND_1,
        ENEMY_KEYS.HELL_HOUND_1,
        ENEMY_KEYS.HELL_HOUND_1,
        ENEMY_KEYS.GRAVE_MASTER,
        ENEMY_KEYS.GRAVE_MASTER,
      ],
    ],
  },

  MAGICIANS_ISLAND: {
    name: "Magician's Island",
    encounterRate: 4,
    areaType: 'Dungeon',
    encounters: [
      [ENEMY_KEYS.HOLLY_BOY_1, ENEMY_KEYS.HOLLY_BOY_1, ENEMY_KEYS.HOLLY_BOY_1, ENEMY_KEYS.HOLLY_BOY_1],
      [
        ENEMY_KEYS.HOLLY_BOY_1,
        ENEMY_KEYS.HOLLY_BOY_1,
        ENEMY_KEYS.HOLLY_BOY_1,
        ENEMY_KEYS.HOLLY_BOY_1,
        ENEMY_KEYS.HOLLY_BOY_1,
        ENEMY_KEYS.HOLLY_BOY_1,
      ],
      [ENEMY_KEYS.HOLLY_BOY_1, ENEMY_KEYS.HOLLY_BOY_1, ENEMY_KEYS.HOLLY_BOY_1, ENEMY_KEYS.FURFUR, ENEMY_KEYS.FURFUR],
      [ENEMY_KEYS.FURFUR, ENEMY_KEYS.FURFUR],
      [ENEMY_KEYS.HOLLY_BOY_1, ENEMY_KEYS.HOLLY_BOY_1, ENEMY_KEYS.HOLLY_BOY_1, ENEMY_KEYS.HOLLY_BOY_1],
      [
        ENEMY_KEYS.HOLLY_BOY_1,
        ENEMY_KEYS.HOLLY_BOY_1,
        ENEMY_KEYS.HOLLY_BOY_1,
        ENEMY_KEYS.HOLLY_BOY_1,
        ENEMY_KEYS.HOLLY_BOY_1,
        ENEMY_KEYS.HOLLY_BOY_1,
      ],
      [ENEMY_KEYS.HOLLY_BOY_1, ENEMY_KEYS.HOLLY_BOY_1, ENEMY_KEYS.HOLLY_BOY_1, ENEMY_KEYS.FURFUR, ENEMY_KEYS.FURFUR],
      [ENEMY_KEYS.FURFUR, ENEMY_KEYS.FURFUR],
      [ENEMY_KEYS.FURFUR, ENEMY_KEYS.FURFUR, ENEMY_KEYS.FURFUR],
    ],
    scripted: [[ENEMY_KEYS.GOLEM]],
  },

  MORAVIA_AREA: {
    name: 'Moravia Area',
    encounterRate: 8,
    areaType: 'World Map',
    encounters: [
      [ENEMY_KEYS.RABBIT_BIRD],
      [ENEMY_KEYS.RABBIT_BIRD, ENEMY_KEYS.RABBIT_BIRD],
      [ENEMY_KEYS.RABBIT_BIRD, ENEMY_KEYS.RABBIT_BIRD, ENEMY_KEYS.RABBIT_BIRD],
      [ENEMY_KEYS.MIRAGE],
      [ENEMY_KEYS.MIRAGE, ENEMY_KEYS.MIRAGE],
      [ENEMY_KEYS.MIRAGE, ENEMY_KEYS.MIRAGE, ENEMY_KEYS.MIRAGE],
      [ENEMY_KEYS.EARTH_GOLEM],
      [ENEMY_KEYS.EARTH_GOLEM, null, ENEMY_KEYS.EARTH_GOLEM],
      [ENEMY_KEYS.RABBIT_BIRD, ENEMY_KEYS.RABBIT_BIRD, ENEMY_KEYS.RABBIT_BIRD, ENEMY_KEYS.EARTH_GOLEM],
      [ENEMY_KEYS.MIRAGE, ENEMY_KEYS.MIRAGE, ENEMY_KEYS.MIRAGE, ENEMY_KEYS.EARTH_GOLEM],
      [
        ENEMY_KEYS.RABBIT_BIRD,
        ENEMY_KEYS.RABBIT_BIRD,
        ENEMY_KEYS.RABBIT_BIRD,
        ENEMY_KEYS.EARTH_GOLEM,
        null,
        ENEMY_KEYS.EARTH_GOLEM,
      ],
      [ENEMY_KEYS.MIRAGE, ENEMY_KEYS.MIRAGE, ENEMY_KEYS.MIRAGE, ENEMY_KEYS.EARTH_GOLEM, null, ENEMY_KEYS.EARTH_GOLEM],
    ],
  },

  MORAVIA_CASTLE: {
    name: 'Moravia Castle',
    encounterRate: 3,
    areaType: 'Dungeon',
    encounters: [
      [ENEMY_KEYS.HELL_HOUND_2, ENEMY_KEYS.HELL_HOUND_2, ENEMY_KEYS.HELL_HOUND_2, ENEMY_KEYS.WHIP_MASTER],
      [
        ENEMY_KEYS.HELL_HOUND_2,
        ENEMY_KEYS.HELL_HOUND_2,
        ENEMY_KEYS.HELL_HOUND_2,
        ENEMY_KEYS.WHIP_MASTER,
        ENEMY_KEYS.WHIP_MASTER,
      ],
      [
        ENEMY_KEYS.HELL_HOUND_2,
        ENEMY_KEYS.HELL_HOUND_2,
        ENEMY_KEYS.HELL_HOUND_2,
        ENEMY_KEYS.WHIP_MASTER,
        ENEMY_KEYS.HELL_HOUND_2,
        ENEMY_KEYS.HELL_HOUND_2,
      ],
      [ENEMY_KEYS.NINJA],
      [ENEMY_KEYS.NINJA, ENEMY_KEYS.NINJA],
      [ENEMY_KEYS.MAGUS],
      [ENEMY_KEYS.MAGUS, ENEMY_KEYS.MAGUS],
      [ENEMY_KEYS.ELITE_SOLDIER_1],
      [ENEMY_KEYS.ELITE_SOLDIER_1, ENEMY_KEYS.ELITE_SOLDIER_1],
      [
        ENEMY_KEYS.HELL_HOUND_2,
        ENEMY_KEYS.HELL_HOUND_2,
        ENEMY_KEYS.HELL_HOUND_2,
        ENEMY_KEYS.MAGUS,
        ENEMY_KEYS.WHIP_MASTER,
      ],
      [ENEMY_KEYS.NINJA, ENEMY_KEYS.NINJA, ENEMY_KEYS.NINJA, ENEMY_KEYS.MAGUS],
      [ENEMY_KEYS.ELITE_SOLDIER_1, ENEMY_KEYS.ELITE_SOLDIER_1, ENEMY_KEYS.ELITE_SOLDIER_1, ENEMY_KEYS.MAGUS],
      [ENEMY_KEYS.HELL_HOUND_2, ENEMY_KEYS.HELL_HOUND_2, ENEMY_KEYS.HELL_HOUND_2, ENEMY_KEYS.NINJA, ENEMY_KEYS.NINJA],
      [ENEMY_KEYS.NINJA, ENEMY_KEYS.NINJA, ENEMY_KEYS.NINJA, ENEMY_KEYS.MAGUS, ENEMY_KEYS.MAGUS],
      [ENEMY_KEYS.ELITE_SOLDIER_1, ENEMY_KEYS.NINJA, ENEMY_KEYS.ELITE_SOLDIER_1, ENEMY_KEYS.MAGUS, ENEMY_KEYS.MAGUS],
      [
        ENEMY_KEYS.HELL_HOUND_2,
        ENEMY_KEYS.HELL_HOUND_2,
        ENEMY_KEYS.HELL_HOUND_2,
        ENEMY_KEYS.ELITE_SOLDIER_1,
        ENEMY_KEYS.ELITE_SOLDIER_1,
        ENEMY_KEYS.WHIP_MASTER,
      ],
    ],
  },

  MT_SEIFU: {
    name: 'Mt. Seifu',
    encounterRate: 2,
    areaType: 'Dungeon',
    encounters: [
      [
        ENEMY_KEYS.SOLDIER_ANT,
        ENEMY_KEYS.SOLDIER_ANT,
        ENEMY_KEYS.SOLDIER_ANT,
        ENEMY_KEYS.SOLDIER_ANT,
        ENEMY_KEYS.SOLDIER_ANT,
        ENEMY_KEYS.SOLDIER_ANT,
      ],
      [ENEMY_KEYS.BANDIT_RED, ENEMY_KEYS.BANDIT_RED],
      [ENEMY_KEYS.BANDIT_RED, ENEMY_KEYS.BANDIT_YELLOW, ENEMY_KEYS.BANDIT_RED],
      [ENEMY_KEYS.BLACK_WILD_BOAR, ENEMY_KEYS.BLACK_WILD_BOAR],
      [ENEMY_KEYS.BANDIT_GREEN, ENEMY_KEYS.BANDIT_GREEN],
    ],
    scripted: [
      [ENEMY_KEYS.QUEEN_ANT_BOSS],
      [ENEMY_KEYS.BANDIT_YELLOW, ENEMY_KEYS.BANDIT_RED, ENEMY_KEYS.BANDIT_RED, ENEMY_KEYS.BANDIT_GREEN, null, ENEMY_KEYS.BANDIT_GREEN],
      [ENEMY_KEYS.VARKAS, ENEMY_KEYS.SYDONIA],
    ],
  },

  MT_TIGERWOLF: {
    name: 'Mt. Tigerwolf',
    encounterRate: 3,
    areaType: 'Dungeon',
    encounters: [
      [
        ENEMY_KEYS.SLASHER_RABBIT,
        ENEMY_KEYS.SLASHER_RABBIT,
        ENEMY_KEYS.SLASHER_RABBIT,
        ENEMY_KEYS.SLASHER_RABBIT,
        ENEMY_KEYS.SLASHER_RABBIT,
        ENEMY_KEYS.SLASHER_RABBIT,
      ],
      [ENEMY_KEYS.GIANT_SNAIL, ENEMY_KEYS.GIANT_SNAIL],
      [ENEMY_KEYS.KILLER_SLIME, ENEMY_KEYS.KILLER_SLIME, ENEMY_KEYS.KILLER_SLIME],
      [ENEMY_KEYS.KILLER_SLIME, ENEMY_KEYS.KILLER_SLIME, ENEMY_KEYS.KILLER_SLIME],
      [ENEMY_KEYS.GIANT_SNAIL],
    ],
  },

  NECLORDS_CASTLE: {
    name: "Neclord's Castle",
    encounterRate: 2,
    areaType: 'Dungeon',
    encounters: [
      [null, ENEMY_KEYS.DEMON_SORCERER],
      [null, ENEMY_KEYS.HELL_UNICORN],
      [ENEMY_KEYS.DEMON_SORCERER, null, ENEMY_KEYS.DEMON_SORCERER],
      [null, ENEMY_KEYS.LARVAE],
      [ENEMY_KEYS.LARVAE, null, ENEMY_KEYS.LARVAE],
      [ENEMY_KEYS.LARVAE, ENEMY_KEYS.LARVAE, ENEMY_KEYS.LARVAE],
      [ENEMY_KEYS.LARVAE, ENEMY_KEYS.LARVAE, ENEMY_KEYS.LARVAE, null, ENEMY_KEYS.DEMON_SORCERER],
      [ENEMY_KEYS.LARVAE, ENEMY_KEYS.LARVAE, ENEMY_KEYS.LARVAE, null, ENEMY_KEYS.HELL_UNICORN],
      [
        ENEMY_KEYS.LARVAE,
        ENEMY_KEYS.LARVAE,
        ENEMY_KEYS.LARVAE,
        ENEMY_KEYS.HELL_UNICORN,
        null,
        ENEMY_KEYS.DEMON_SORCERER,
      ],
    ],
    scripted: [[ENEMY_KEYS.NECLORD]],
  },

  PANNU_YAKUTA_AREA: {
    name: 'Pannu Yakuta Area',
    encounterRate: 8,
    areaType: 'World Map',
    encounters: [
      [ENEMY_KEYS.KOBOLD_BOW, ENEMY_KEYS.KOBOLD_BOW],
      [ENEMY_KEYS.KOBOLD_SWORD, ENEMY_KEYS.KOBOLD_SWORD, ENEMY_KEYS.KOBOLD_SWORD],
      [ENEMY_KEYS.KOBOLD_SWORD, ENEMY_KEYS.KOBOLD_SWORD, ENEMY_KEYS.KOBOLD_SWORD, ENEMY_KEYS.KOBOLD_MAGE],
      [ENEMY_KEYS.KOBOLD_BOW, ENEMY_KEYS.KOBOLD_BOW, ENEMY_KEYS.KOBOLD_BOW, ENEMY_KEYS.KOBOLD_MAGE],
      [ENEMY_KEYS.KOBOLD_BOW, ENEMY_KEYS.STRONG_ARM, ENEMY_KEYS.KOBOLD_BOW, ENEMY_KEYS.KOBOLD_MAGE],
      [
        ENEMY_KEYS.KOBOLD_SWORD,
        ENEMY_KEYS.KOBOLD_SWORD,
        ENEMY_KEYS.KOBOLD_SWORD,
        ENEMY_KEYS.KOBOLD_MAGE,
        ENEMY_KEYS.KOBOLD_MAGE,
      ],
      [
        ENEMY_KEYS.KOBOLD_BOW,
        ENEMY_KEYS.KOBOLD_BOW,
        ENEMY_KEYS.KOBOLD_BOW,
        ENEMY_KEYS.KOBOLD_MAGE,
        ENEMY_KEYS.KOBOLD_MAGE,
      ],
      [
        ENEMY_KEYS.KOBOLD_SWORD,
        ENEMY_KEYS.STRONG_ARM,
        ENEMY_KEYS.KOBOLD_SWORD,
        ENEMY_KEYS.KOBOLD_MAGE,
        ENEMY_KEYS.KOBOLD_MAGE,
      ],
    ],
  },

  PANNU_YAKUTA: {
    name: 'Pannu Yakuta',
    encounterRate: 2,
    areaType: 'Dungeon',
    encounters: [
      [ENEMY_KEYS.VETERAN_SOLDIER_SPEAR, ENEMY_KEYS.VETERAN_SOLDIER_SPEAR, ENEMY_KEYS.VETERAN_SOLDIER_SPEAR],
      [ENEMY_KEYS.DEVIL_ARMOR],
      [ENEMY_KEYS.DEVIL_SHIELD, ENEMY_KEYS.DEVIL_SHIELD, ENEMY_KEYS.DEVIL_SHIELD, ENEMY_KEYS.DEVIL_ARMOR],
      [null, ENEMY_KEYS.VETERAN_SOLDIER_SABRE, ENEMY_KEYS.VETERAN_SOLDIER_SABRE],
      [ENEMY_KEYS.VETERAN_SOLDIER_SABRE, ENEMY_KEYS.VETERAN_SOLDIER_SABRE, ENEMY_KEYS.VETERAN_SOLDIER_SABRE],
      [ENEMY_KEYS.VETERAN_SOLDIER_BOW, ENEMY_KEYS.VETERAN_SOLDIER_BOW, ENEMY_KEYS.VETERAN_SOLDIER_BOW],
      [
        ENEMY_KEYS.VETERAN_SOLDIER_SPEAR,
        ENEMY_KEYS.VETERAN_SOLDIER_BOW,
        ENEMY_KEYS.VETERAN_SOLDIER_BOW,
        ENEMY_KEYS.VETERAN_SOLDIER_SABRE,
      ],
      [
        ENEMY_KEYS.VETERAN_SOLDIER_SPEAR,
        ENEMY_KEYS.VETERAN_SOLDIER_BOW,
        ENEMY_KEYS.VETERAN_SOLDIER_SABRE,
        ENEMY_KEYS.VETERAN_SOLDIER_BOW,
        ENEMY_KEYS.VETERAN_SOLDIER_BOW,
      ],
      [ENEMY_KEYS.DEVIL_SHIELD, ENEMY_KEYS.DEVIL_SHIELD],
      [ENEMY_KEYS.DEVIL_SHIELD, ENEMY_KEYS.DEVIL_SHIELD, ENEMY_KEYS.DEVIL_SHIELD],
    ],
    scripted: [[ENEMY_KEYS.DRAGON]],
  },

  SCARLETICIA_AREA: {
    name: 'Scarleticia Area',
    encounterRate: 8,
    areaType: 'World Map',
    encounters: [
      [ENEMY_KEYS.HOLLY_FAIRY],
      [ENEMY_KEYS.HOLLY_FAIRY, ENEMY_KEYS.HOLLY_FAIRY],
      [ENEMY_KEYS.HOLLY_FAIRY, ENEMY_KEYS.HOLLY_FAIRY, ENEMY_KEYS.HOLLY_FAIRY],
      [ENEMY_KEYS.MAD_IVY],
      [ENEMY_KEYS.MAD_IVY, ENEMY_KEYS.MAD_IVY],
      [ENEMY_KEYS.MAD_IVY, ENEMY_KEYS.MAD_IVY, ENEMY_KEYS.MAD_IVY],
      [ENEMY_KEYS.CREEPER],
      [ENEMY_KEYS.CREEPER, ENEMY_KEYS.CREEPER],
      [ENEMY_KEYS.CREEPER, ENEMY_KEYS.CREEPER, ENEMY_KEYS.CREEPER],
      [ENEMY_KEYS.HOLLY_FAIRY, ENEMY_KEYS.HOLLY_FAIRY, ENEMY_KEYS.HOLLY_FAIRY, ENEMY_KEYS.CREEPER],
      [ENEMY_KEYS.HOLLY_FAIRY, ENEMY_KEYS.HOLLY_FAIRY, ENEMY_KEYS.HOLLY_FAIRY, ENEMY_KEYS.MAD_IVY],
      [ENEMY_KEYS.MAD_IVY, ENEMY_KEYS.MAD_IVY, ENEMY_KEYS.MAD_IVY, ENEMY_KEYS.CREEPER],
    ],
  },

  SCARLETICIA: {
    name: 'Scarleticia',
    encounterRate: 3,
    areaType: 'Dungeon',
    encounters: [
      [ENEMY_KEYS.MAD_IVY, ENEMY_KEYS.MAD_IVY],
      [ENEMY_KEYS.CREEPER, ENEMY_KEYS.CREEPER],
      [ENEMY_KEYS.CREEPER, ENEMY_KEYS.CREEPER, ENEMY_KEYS.CREEPER],
      [
        ENEMY_KEYS.CREEPER,
        ENEMY_KEYS.CREEPER,
        ENEMY_KEYS.CREEPER,
        ENEMY_KEYS.CREEPER,
        ENEMY_KEYS.CREEPER,
        ENEMY_KEYS.CREEPER,
      ],
      [ENEMY_KEYS.NIGHTMARE],
      [ENEMY_KEYS.CREEPER, ENEMY_KEYS.CREEPER, ENEMY_KEYS.CREEPER, ENEMY_KEYS.NIGHTMARE],
    ],
  },

  SEEK_VALLEY: {
    name: 'Seek Valley',
    encounterRate: 2,
    areaType: 'Dungeon',
    encounters: [
      [null, ENEMY_KEYS.IVY],
      [ENEMY_KEYS.IVY, null, ENEMY_KEYS.IVY],
      [ENEMY_KEYS.IVY, null, ENEMY_KEYS.IVY, null, ENEMY_KEYS.IVY],
      [null, ENEMY_KEYS.ROCK_BUSTER],
      [ENEMY_KEYS.ROCK_BUSTER, null, ENEMY_KEYS.ROCK_BUSTER],
      [ENEMY_KEYS.ROCK_BUSTER, null, ENEMY_KEYS.ROCK_BUSTER, null, ENEMY_KEYS.ROCK_BUSTER],
      [null, ENEMY_KEYS.WYVERN],
      [null, ENEMY_KEYS.QUEEN_ANT],
      [ENEMY_KEYS.IVY, null, ENEMY_KEYS.IVY, null, ENEMY_KEYS.ROCK_BUSTER],
      [ENEMY_KEYS.IVY, null, ENEMY_KEYS.IVY, null, ENEMY_KEYS.WYVERN],
      [ENEMY_KEYS.ROCK_BUSTER, null, ENEMY_KEYS.ROCK_BUSTER, null, ENEMY_KEYS.QUEEN_ANT],
      [ENEMY_KEYS.ROCK_BUSTER, null, ENEMY_KEYS.ROCK_BUSTER, null, ENEMY_KEYS.WYVERN],
    ],
    scripted: [[ENEMY_KEYS.CRYSTAL_CORE]],
  },

  SEIKA_AREA: {
    name: 'Seika Area',
    encounterRate: 8,
    areaType: 'World Map',
    encounters: [
      [ENEMY_KEYS.FLYING_SQUIRREL, ENEMY_KEYS.FLYING_SQUIRREL, ENEMY_KEYS.FLYING_SQUIRREL, ENEMY_KEYS.BEAST_COMMANDER],
      [ENEMY_KEYS.FLYING_SQUIRREL, null, ENEMY_KEYS.FLYING_SQUIRREL],
      [
        ENEMY_KEYS.FLYING_SQUIRREL,
        ENEMY_KEYS.FLYING_SQUIRREL,
        ENEMY_KEYS.FLYING_SQUIRREL,
        ENEMY_KEYS.FLYING_SQUIRREL,
        ENEMY_KEYS.FLYING_SQUIRREL,
        ENEMY_KEYS.FLYING_SQUIRREL,
      ],
      [null, ENEMY_KEYS.ROC],
      [
        ENEMY_KEYS.KILLER_RABBIT,
        ENEMY_KEYS.KILLER_RABBIT,
        ENEMY_KEYS.KILLER_RABBIT,
        ENEMY_KEYS.KILLER_RABBIT,
        ENEMY_KEYS.KILLER_RABBIT,
        ENEMY_KEYS.KILLER_RABBIT,
      ],
      [ENEMY_KEYS.ROC, null, ENEMY_KEYS.ROC],
      [ENEMY_KEYS.KILLER_RABBIT, ENEMY_KEYS.KILLER_RABBIT, ENEMY_KEYS.KILLER_RABBIT, ENEMY_KEYS.BEAST_COMMANDER],
      [
        ENEMY_KEYS.FLYING_SQUIRREL,
        ENEMY_KEYS.FLYING_SQUIRREL,
        ENEMY_KEYS.FLYING_SQUIRREL,
        ENEMY_KEYS.KILLER_RABBIT,
        ENEMY_KEYS.BEAST_COMMANDER,
        ENEMY_KEYS.KILLER_RABBIT,
      ],
    ],
  },

  SHASARAZADE_FORTRESS: {
    name: 'Shasarazade Fortress',
    encounterRate: 3,
    areaType: 'Dungeon',
    encounters: [
      [
        ENEMY_KEYS.ELITE_SOLDIER_2,
        ENEMY_KEYS.ELITE_SOLDIER_2,
        ENEMY_KEYS.ELITE_SOLDIER_2,
        null,
        ENEMY_KEYS.ELITE_SOLDIER_2,
      ],
      [ENEMY_KEYS.ELITE_SOLDIER_2, null, ENEMY_KEYS.ELITE_SOLDIER_2],
      [ENEMY_KEYS.ELITE_SOLDIER_2, ENEMY_KEYS.ELITE_SOLDIER_2, ENEMY_KEYS.ELITE_SOLDIER_2],
      [ENEMY_KEYS.SIREN_2, null, ENEMY_KEYS.SIREN_2],
      [ENEMY_KEYS.SIREN_2, ENEMY_KEYS.SIREN_2, ENEMY_KEYS.SIREN_2],
      [ENEMY_KEYS.SIREN_2, ENEMY_KEYS.SIREN_2, ENEMY_KEYS.SIREN_2, null, ENEMY_KEYS.SIREN_2],
      [null, ENEMY_KEYS.KERBEROS],
    ],
    scripted: [[ENEMY_KEYS.SHELL_VENUS], [ENEMY_KEYS.SONYA_SHULEN]],
  },

  SONIERE_PRISON: {
    name: 'Soniere Prison',
    encounterRate: 2,
    areaType: 'Dungeon',
    encounters: [
      [ENEMY_KEYS.VIPERMAN, ENEMY_KEYS.DELF],
      [ENEMY_KEYS.DELF, ENEMY_KEYS.DELF, ENEMY_KEYS.DELF, ENEMY_KEYS.VIPERMAN],
      [ENEMY_KEYS.RED_SLIME],
      [ENEMY_KEYS.RED_SLIME, ENEMY_KEYS.RED_SLIME, ENEMY_KEYS.RED_SLIME],
      [ENEMY_KEYS.RED_SLIME, ENEMY_KEYS.RED_SLIME, ENEMY_KEYS.RED_SLIME, ENEMY_KEYS.NIGHTMARE, ENEMY_KEYS.NIGHTMARE],
      [ENEMY_KEYS.NIGHTMARE],
      [ENEMY_KEYS.NIGHTMARE, ENEMY_KEYS.NIGHTMARE, ENEMY_KEYS.NIGHTMARE],
      [ENEMY_KEYS.RED_SLIME, ENEMY_KEYS.RED_SLIME, ENEMY_KEYS.RED_SLIME, ENEMY_KEYS.NIGHTMARE],
    ],
    // Veteran Soldier ambush groups, from lib/enemies.js's "Other Enemies" section.
    scripted: [
      [ENEMY_KEYS.VETERAN_SOLDIER_SPEAR, ENEMY_KEYS.VETERAN_SOLDIER_SPEAR, ENEMY_KEYS.VETERAN_SOLDIER_SPEAR],
      [ENEMY_KEYS.VETERAN_SOLDIER_BOW, ENEMY_KEYS.VETERAN_SOLDIER_SPEAR, ENEMY_KEYS.VETERAN_SOLDIER_SPEAR],
      [
        ENEMY_KEYS.VETERAN_SOLDIER_SPEAR,
        ENEMY_KEYS.VETERAN_SOLDIER_SPEAR,
        ENEMY_KEYS.VETERAN_SOLDIER_SPEAR,
        ENEMY_KEYS.VETERAN_SOLDIER_BOW,
        ENEMY_KEYS.VETERAN_SOLDIER_BOW,
      ],
      [
        ENEMY_KEYS.VETERAN_SOLDIER_BOW,
        ENEMY_KEYS.VETERAN_SOLDIER_SPEAR,
        ENEMY_KEYS.VETERAN_SOLDIER_SPEAR,
        ENEMY_KEYS.VETERAN_SOLDIER_SPEAR,
        ENEMY_KEYS.VETERAN_SOLDIER_BOW,
      ],
    ],
  },

  TORAN_LAKE_CASTLE: {
    name: 'Toran Lake Castle',
    encounterRate: 2,
    areaType: 'Dungeon',
    encounters: [
      [ENEMY_KEYS.OANNES, null, ENEMY_KEYS.OANNES],
      [ENEMY_KEYS.OANNES, ENEMY_KEYS.OANNES, ENEMY_KEYS.OANNES],
      [ENEMY_KEYS.GIANT_SLUG, ENEMY_KEYS.GIANT_SLUG],
      [ENEMY_KEYS.GIANT_SLUG, ENEMY_KEYS.GIANT_SLUG, ENEMY_KEYS.GIANT_SLUG],
      [ENEMY_KEYS.GHOST_ARMOR],
      [ENEMY_KEYS.GIANT_SLUG, ENEMY_KEYS.GIANT_SLUG, ENEMY_KEYS.GIANT_SLUG, ENEMY_KEYS.GHOST_ARMOR],
      [ENEMY_KEYS.OANNES, ENEMY_KEYS.OANNES, ENEMY_KEYS.OANNES, ENEMY_KEYS.GHOST_ARMOR],
    ],
    scripted: [[ENEMY_KEYS.ZOMBIE_DRAGON]],
  },

  // Catch-all for scripted fights whose bestiary location isn't one of lib/enemies.js's
  // regular areas (Liberation Army HQ, Pirates' Fortress, Warrior's Village, Grady's
  // Mansion, Lenankamp, Kraze's Mansion, Kobold Village) or is ambiguous against an
  // existing area (plain "Seika"/"Gregminster" vs. our SEIKA_AREA/GREGMINSTER_PALACE).
  OTHER: {
    name: 'Other',
    encounterRate: 0,
    encounters: [],
    scripted: [
      [ENEMY_KEYS.ASSASSIN], // Liberation Army HQ
      [ENEMY_KEYS.ANJI, ENEMY_KEYS.KANAK, ENEMY_KEYS.LEONARDO], // Pirates' Fortress
      [ENEMY_KEYS.NECLORD_L], // Warrior's Village
      [ENEMY_KEYS.AIN_GIDE], // Gregminster
      [ENEMY_KEYS.EMPIRE_SOLDIER_SABER_1, ENEMY_KEYS.EMPIRE_SOLDIER_SABER_1], // Grady's Mansion
      [
        ENEMY_KEYS.EMPIRE_SOLDIER_SPEAR_1,
        ENEMY_KEYS.EMPIRE_SOLDIER_SPEAR_1,
        ENEMY_KEYS.EMPIRE_SOLDIER_SPEAR_1,
        ENEMY_KEYS.EMPIRE_SOLDIER_BOW_1,
        ENEMY_KEYS.EMPIRE_SOLDIER_BOW_1,
        ENEMY_KEYS.EMPIRE_CAPTAIN,
      ], // Grady's Mansion
      [
        ENEMY_KEYS.EMPIRE_SOLDIER_BOW_2,
        ENEMY_KEYS.EMPIRE_SOLDIER_BOW_2,
        ENEMY_KEYS.EMPIRE_SOLDIER_BOW_2,
        ENEMY_KEYS.EMPIRE_SOLDIER_BOW_2,
        ENEMY_KEYS.EMPIRE_SOLDIER_BOW_2,
      ], // Lenankamp
      [ENEMY_KEYS.EMPIRE_SOLDIER_SWORD_3, ENEMY_KEYS.EMPIRE_SOLDIER_SWORD_3, ENEMY_KEYS.EMPIRE_SOLDIER_SPEAR_3], // Seika
      [
        ENEMY_KEYS.EMPIRE_SOLDIER_SWORD_4,
        ENEMY_KEYS.EMPIRE_SOLDIER_SWORD_4,
        ENEMY_KEYS.EMPIRE_SOLDIER_SWORD_4,
        ENEMY_KEYS.EMPIRE_SOLDIER_SWORD_4,
        ENEMY_KEYS.EMPIRE_SOLDIER_SWORD_4,
        ENEMY_KEYS.EMPIRE_SOLDIER_SWORD_4,
      ], // Kraze's Mansion
      [
        ENEMY_KEYS.VETERAN_SOLDIER_SPEAR,
        ENEMY_KEYS.VETERAN_SOLDIER_SPEAR,
        ENEMY_KEYS.VETERAN_SOLDIER_SPEAR,
        ENEMY_KEYS.VETERAN_SOLDIER_SPEAR,
        ENEMY_KEYS.VETERAN_SOLDIER_SPEAR,
        ENEMY_KEYS.VETERAN_SOLDIER_SPEAR,
      ], // Kobold Village
      [ENEMY_KEYS.IMPERIAL_GUARDS_SWORD, ENEMY_KEYS.IMPERIAL_GUARDS_SWORD, ENEMY_KEYS.IMPERIAL_GUARDS_SWORD, ENEMY_KEYS.IMPERIAL_GUARDS_SABRE], // Gregminster
      [
        ENEMY_KEYS.IMPERIAL_GUARDS_SWORD,
        ENEMY_KEYS.IMPERIAL_GUARDS_SWORD,
        ENEMY_KEYS.IMPERIAL_GUARDS_SABRE,
        ENEMY_KEYS.IMPERIAL_GUARDS_SABRE,
        ENEMY_KEYS.IMPERIAL_GUARDS_SABRE,
      ], // Gregminster
    ],
  },
};

/**
 * Builds a display name for an encounter from its party, e.g. "2 Banshee 1 Clay Doll".
 * Groups by key (preserving first-occurrence order) and prefers each entry's
 * nickname over its name, so colloquial names (e.g. "Red Machine") fall out automatically.
 * @param {Formation} party
 * @returns {string}
 */
export function getEncounterName(party) {
  const order = [];
  const counts = new Map();
  for (const key of party) {
    if (key === null) continue;
    if (!counts.has(key)) order.push(key);
    counts.set(key, (counts.get(key) ?? 0) + 1);
  }
  return order.map(key => `${counts.get(key)} ${ENEMIES[key].nickname ?? ENEMIES[key].name}`).join(' ');
}

/**
 * A formation's enemies in combatant order, each with its formation slot.
 * @param {Formation} formation
 * @returns {{ key: EnemyKey, position: number }[]}
 */
export function getFormationSlots(formation) {
  return formation
    .map((key, index) => ({ key, position: index + 1 }))
    .filter(slot => slot.key !== null);
}
