import { ELEMENTAL_RESISTANCES } from '../Constants.js';

/** @typedef {import('./Enemies.js').EnemyEntry} EnemyEntry */

/** @satisfies {Record<string, EnemyEntry>} */
export const BOSSES = {
  GOLEM: {
    name: 'Golem',
    LVL: 12,
    bits: 1500,
    bitsRaw: 1500,
    stats: { HP: 300, PWR: 40, SKL: 21, DEF: 2, SPD: 17, MGC: 25, LUK: 20 },
    drops: [{ item: 'Medicine x6', rate: 15 }],
    elements: { Fire: ELEMENTAL_RESISTANCES.RESISTANT, Lightning: ELEMENTAL_RESISTANCES.WEAK, Wind: ELEMENTAL_RESISTANCES.RESISTANT },
    speciesFlags: 4,
  },
  QUEEN_ANT: {
    name: 'Queen Ant',
    LVL: 15,
    bits: 2000,
    bitsRaw: 2000,
    stats: { HP: 7000, PWR: 75, SKL: 25, DEF: 50, SPD: 20, MGC: 55, LUK: 55 },
    drops: [{ item: 'Pointed Hat', rate: 10 }],
    elements: { Water: ELEMENTAL_RESISTANCES.WEAK, Earth: ELEMENTAL_RESISTANCES.WEAK },
    speciesFlags: 4,
  },
  VARKAS: {
    name: 'Varkas',
    LVL: 12,
    bits: 400,
    bitsRaw: 400,
    stats: { HP: 210, PWR: 76, SKL: 40, DEF: 15, SPD: 27, MGC: 18, LUK: 16 },
    drops: [],
    speciesFlags: 3,
  },
  SYDONIA: {
    name: 'Sydonia',
    LVL: 10,
    bits: 300,
    bitsRaw: 300,
    stats: { HP: 140, PWR: 67, SKL: 55, DEF: 8, SPD: 42, MGC: 30, LUK: 19 },
    drops: [],
    elements: { Fire: ELEMENTAL_RESISTANCES.RESISTANT },
    speciesFlags: 11,
  },
  ZOMBIE_DRAGON: {
    name: 'Zombie Dragon',
    LVL: 30,
    bits: 2000,
    bitsRaw: 2000,
    stats: { HP: 3700, PWR: 175, SKL: 50, DEF: 35, SPD: 65, MGC: 130, LUK: 40 },
    drops: [{ item: 'Lightning Rune', rate: 80 }],
    elements: { Fire: ELEMENTAL_RESISTANCES.WEAK, Resurrection: ELEMENTAL_RESISTANCES.WEAK },
    instantDeathImmune: true,
    speciesFlags: 16389,
  },
  GIGANTES: {
    name: 'Gigantes',
    LVL: 35,
    bits: 3000,
    bitsRaw: 3000,
    stats: { HP: 3900, PWR: 260, SKL: 60, DEF: 25, SPD: 80, MGC: 120, LUK: 55 },
    drops: [{ item: 'Goldlet', rate: 6 }],
    elements: { Fire: ELEMENTAL_RESISTANCES.INVULNERABLE, Lightning: ELEMENTAL_RESISTANCES.WEAK, Wind: ELEMENTAL_RESISTANCES.WEAK },
    instantDeathImmune: true,
    speciesFlags: 16420,
  },
  DRAGON: {
    name: 'Dragon',
    LVL: 40,
    bits: 3500,
    bitsRaw: 3500,
    stats: { HP: 6000, PWR: 250, SKL: 60, DEF: 35, SPD: 40, MGC: 150, LUK: 65 },
    drops: [{ item: 'Half Armor', rate: 80 }],
    elements: { Water: ELEMENTAL_RESISTANCES.RESISTANT, Fire: ELEMENTAL_RESISTANCES.RESISTANT, Lightning: ELEMENTAL_RESISTANCES.RESISTANT, Earth: ELEMENTAL_RESISTANCES.RESISTANT, Wind: ELEMENTAL_RESISTANCES.WEAK },
    instantDeathImmune: true,
    speciesFlags: 16388,
  },
  LEONARDO: {
    name: 'Leonardo',
    LVL: 36,
    bits: 400,
    bitsRaw: 400,
    stats: { HP: 1400, PWR: 270, SKL: 98, DEF: 55, SPD: 100, MGC: 60, LUK: 40 },
    drops: [],
    elements: { Fire: ELEMENTAL_RESISTANCES.RESISTANT, Wind: ELEMENTAL_RESISTANCES.RESISTANT },
    instantDeathImmune: true,
    speciesFlags: 16387,
  },
  KANAK: {
    name: 'Kanak',
    LVL: 35,
    bits: 400,
    bitsRaw: 400,
    stats: { HP: 2200, PWR: 240, SKL: 38, DEF: 70, SPD: 60, MGC: 50, LUK: 70 },
    drops: [],
    elements: { Lightning: ELEMENTAL_RESISTANCES.RESISTANT, Wind: ELEMENTAL_RESISTANCES.RESISTANT },
    instantDeathImmune: true,
    speciesFlags: 16387,
  },
  CRYSTAL_CORE: {
    name: 'Crystal Core',
    LVL: 60,
    bits: 70000,
    bitsRaw: 7001,
    stats: { HP: 5000, PWR: 350, SKL: 70, DEF: 90, SPD: 65, MGC: 275, LUK: 80 },
    drops: [],
    elements: {
      Water: ELEMENTAL_RESISTANCES.WEAK,
      Fire: ELEMENTAL_RESISTANCES.RESISTANT,
      Lightning: ELEMENTAL_RESISTANCES.RESISTANT,
      Earth: ELEMENTAL_RESISTANCES.WEAK,
      Wind: ELEMENTAL_RESISTANCES.RESISTANT,
      Resurrection: ELEMENTAL_RESISTANCES.INVULNERABLE,
    },
    instantDeathImmune: true,
    speciesFlags: 16384,
  },
  SHELL_VENUS: {
    name: 'Shell Venus',
    LVL: 65,
    bits: 100000,
    bitsRaw: 10001,
    stats: { HP: 15000, PWR: 470, SKL: 80, DEF: 40, SPD: 80, MGC: 350, LUK: 100 },
    drops: [],
    elements: { Water: ELEMENTAL_RESISTANCES.RESISTANT, Fire: ELEMENTAL_RESISTANCES.RESISTANT, Lightning: ELEMENTAL_RESISTANCES.WEAK, Earth: ELEMENTAL_RESISTANCES.WEAK, Wind: ELEMENTAL_RESISTANCES.RESISTANT },
    instantDeathImmune: true,
    speciesFlags: 16384,
  },
  SONYA_SHULEN: {
    name: 'Sonya Shulen',
    LVL: 58,
    bits: 1500,
    bitsRaw: 1500,
    stats: { HP: 6000, PWR: 480, SKL: 125, DEF: 110, SPD: 160, MGC: 390, LUK: 120 },
    drops: [],
    elements: { Water: ELEMENTAL_RESISTANCES.RESISTANT, Fire: ELEMENTAL_RESISTANCES.RESISTANT, Lightning: ELEMENTAL_RESISTANCES.RESISTANT, Earth: ELEMENTAL_RESISTANCES.RESISTANT, Wind: ELEMENTAL_RESISTANCES.RESISTANT },
    instantDeathImmune: true,
    speciesFlags: 16387,
  },
  AIN_GIDE: {
    name: 'Ain Gide',
    LVL: 60,
    bits: 2000,
    bitsRaw: 2000,
    stats: { HP: 8000, PWR: 500, SKL: 80, DEF: 120, SPD: 130, MGC: 410, LUK: 90 },
    drops: [],
    elements: { Fire: ELEMENTAL_RESISTANCES.RESISTANT, Lightning: ELEMENTAL_RESISTANCES.RESISTANT },
    instantDeathImmune: true,
    speciesFlags: 16387,
  },
  // LUK per the bestiary (lib/enemies.js said 19)
  ASSASSIN: {
    name: 'Assassin',
    LVL: 18,
    bits: 400,
    bitsRaw: 400,
    stats: { HP: 2000, PWR: 120, SKL: 60, DEF: 9, SPD: 35, MGC: 30, LUK: 50 },
    drops: [],
    instantDeathImmune: true,
    speciesFlags: 16398,
  },
  // LUK per the bestiary (lib/enemies.js said 30)
  ANJI: {
    name: 'Anji',
    LVL: 39,
    bits: 1000,
    bitsRaw: 1000,
    stats: { HP: 1700, PWR: 250, SKL: 68, DEF: 60, SPD: 80, MGC: 80, LUK: 35 },
    drops: [],
    elements: { Fire: ELEMENTAL_RESISTANCES.RESISTANT, Lightning: ELEMENTAL_RESISTANCES.RESISTANT },
    instantDeathImmune: true,
    speciesFlags: 16387,
  },

  // Neclord has two distinct fights with different stats; not in lib/enemies.js at all,
  // added fresh from the bestiary. This fight is unwinnable by design (full invulnerability).
  NECLORD_L: {
    name: 'Neclord',
    nickname: 'Neclord (Unwinnable)',
    LVL: 55,
    bits: 10000,
    bitsRaw: 10000,
    stats: { HP: 10000, PWR: 460, SKL: 100, DEF: 300, SPD: 75, MGC: 300, LUK: 30 },
    drops: [],
    elements: {
      Water: ELEMENTAL_RESISTANCES.INVULNERABLE,
      Fire: ELEMENTAL_RESISTANCES.INVULNERABLE,
      Lightning: ELEMENTAL_RESISTANCES.INVULNERABLE,
      Earth: ELEMENTAL_RESISTANCES.INVULNERABLE,
      Wind: ELEMENTAL_RESISTANCES.INVULNERABLE,
      Resurrection: ELEMENTAL_RESISTANCES.INVULNERABLE,
      Dark: ELEMENTAL_RESISTANCES.INVULNERABLE,
    },
    instantDeathImmune: true,
    speciesFlags: 49156,
  },
  // lib/enemies.js's only "Neclord" entry matches this fight exactly.
  NECLORD: {
    name: 'Neclord',
    LVL: 55,
    bits: 10000,
    bitsRaw: 10000,
    stats: { HP: 7500, PWR: 450, SKL: 100, DEF: 80, SPD: 75, MGC: 275, LUK: 30 },
    drops: [],
    elements: {
      Water: ELEMENTAL_RESISTANCES.INVULNERABLE,
      Fire: ELEMENTAL_RESISTANCES.INVULNERABLE,
      Lightning: ELEMENTAL_RESISTANCES.INVULNERABLE,
      Earth: ELEMENTAL_RESISTANCES.INVULNERABLE,
      Wind: ELEMENTAL_RESISTANCES.INVULNERABLE,
      Resurrection: ELEMENTAL_RESISTANCES.INVULNERABLE,
      Dark: ELEMENTAL_RESISTANCES.INVULNERABLE,
    },
    instantDeathImmune: true,
    speciesFlags: 49156,
  },

  // Golden Hydra — not in lib/enemies.js at all, added fresh from the bestiary. Each head
  // is a separate target; the fight grants no rewards (bits 0, no drops).
  GOLDEN_HYDRA_RIGHT: {
    name: 'Golden Hydra',
    nickname: 'Golden Hydra R',
    LVL: 75,
    bits: 0,
    bitsRaw: 3392,
    stats: { HP: 10000, PWR: 540, SKL: 105, DEF: 55, SPD: 75, MGC: 470, LUK: 80 },
    drops: [],
    elements: { Water: ELEMENTAL_RESISTANCES.RESISTANT, Lightning: ELEMENTAL_RESISTANCES.RESISTANT, Wind: ELEMENTAL_RESISTANCES.INVULNERABLE },
    instantDeathImmune: true,
    speciesFlags: 16384,
  },
  GOLDEN_HYDRA_MIDDLE: {
    name: 'Golden Hydra',
    nickname: 'Golden Hydra M',
    LVL: 75,
    bits: 0,
    bitsRaw: 3392,
    stats: { HP: 10000, PWR: 560, SKL: 105, DEF: 55, SPD: 75, MGC: 430, LUK: 80 },
    drops: [],
    elements: { Fire: ELEMENTAL_RESISTANCES.RESISTANT, Lightning: ELEMENTAL_RESISTANCES.INVULNERABLE, Earth: ELEMENTAL_RESISTANCES.RESISTANT },
    instantDeathImmune: true,
    speciesFlags: 16384,
  },
  GOLDEN_HYDRA_LEFT: {
    name: 'Golden Hydra',
    nickname: 'Golden Hydra L',
    LVL: 75,
    bits: 0,
    bitsRaw: 3392,
    stats: { HP: 10000, PWR: 570, SKL: 105, DEF: 55, SPD: 75, MGC: 420, LUK: 80 },
    drops: [],
    elements: { Water: ELEMENTAL_RESISTANCES.RESISTANT, Fire: ELEMENTAL_RESISTANCES.INVULNERABLE, Lightning: ELEMENTAL_RESISTANCES.RESISTANT },
    instantDeathImmune: true,
    speciesFlags: 16384,
  },
};
