import { RUNES } from '../Magic/Runes.js';
import { ARMOR, WEAR_CLASSES } from '../Armor.js';
import { RANGE } from '../Constants.js';

export const CHARACTERS = {
  MCDOHL: {
    name: 'McDohl',
    range: RANGE.MEDIUM,
    rune: RUNES.NONE,
    isRuneLocked: false,
    weapon: {
      id: 1,
      lvl: 1,
    },
    wearClasses: [WEAR_CLASSES.CAP, WEAR_CLASSES.LIGHT_ARMOR, WEAR_CLASSES.MALE],
    armor: {
      head: ARMOR.BANDANNA,
      body: ARMOR.TUNIC,
      shield: null,
      accessories: [ARMOR.GLOVES, ARMOR.BOOTS],
    },
    isArmorLocked: {
      head: false,
      body: false,
      shield: false,
      accessories: [false, false],
    },
    stats: {
      initial: {
        HP: 17,
        PWR: 13,
        SKL: 22,
        DEF: 18,
        SPD: 15,
        MGC: 12,
        LUK: 16,
      },
      growths: {
        PWR: 6,
        SKL: 7,
        DEF: 5,
        SPD: 7,
        MGC: 6,
        LUK: 6,
      },
    },
  },
  ALEN: {
    name: 'Alen',
    range: RANGE.SHORT,
    rune: RUNES.RAGE,
    isRuneLocked: true,
    weapon: {
      id: 42,
      lvl: 7,
    },
    wearClasses: [
      WEAR_CLASSES.HELMET,
      WEAR_CLASSES.LIGHT_ARMOR,
      WEAR_CLASSES.SHIELD,
      WEAR_CLASSES.MALE,
    ],
    armor: {
      head: null,
      body: ARMOR.LEATHER_ARMOR,
      shield: ARMOR.STEEL_SHIELD,
      accessories: [null, null],
    },
    isArmorLocked: {
      head: false,
      body: false,
      shield: false,
      accessories: [false, false],
    },
    stats: {
      initial: {
        HP: 25,
        PWR: 17,
        SKL: 15,
        DEF: 16,
        SPD: 11,
        MGC: 15,
        LUK: 13,
      },
      growths: {
        PWR: 6,
        SKL: 3,
        DEF: 5,
        SPD: 4,
        MGC: 5,
        LUK: 4,
      },
    },
  },
  ANJI: {
    name: 'Anji',
    range: RANGE.MEDIUM,
    rune: RUNES.NONE,
    isRuneLocked: false,
    weapon: {
      id: 46,
      lvl: 7,
    },
    wearClasses: [WEAR_CLASSES.CAP, WEAR_CLASSES.VEST, WEAR_CLASSES.MALE],
    armor: {
      head: ARMOR.BANDANNA,
      body: ARMOR.LEATHER_COAT,
      shield: null,
      accessories: [null, null],
    },
    isArmorLocked: {
      head: false,
      body: false,
      shield: false,
      accessories: [false, false],
    },
    stats: {
      initial: {
        HP: 24,
        PWR: 18,
        SKL: 17,
        DEF: 9,
        SPD: 15,
        MGC: 7,
        LUK: 9,
      },
      growths: {
        PWR: 6,
        SKL: 5,
        DEF: 3,
        SPD: 5,
        MGC: 2,
        LUK: 2,
      },
    },
  },
  ANTONIO: {
    name: 'Antonio',
    range: RANGE.MEDIUM,
    rune: RUNES.NONE,
    isRuneLocked: false,
    weapon: {
      id: 68,
      lvl: 2,
    },
    wearClasses: [WEAR_CLASSES.CAP, WEAR_CLASSES.VEST, WEAR_CLASSES.SHIELD, WEAR_CLASSES.MALE],
    armor: {
      head: null,
      body: ARMOR.TUNIC,
      shield: null,
      accessories: [ARMOR.GLOVES, null],
    },
    isArmorLocked: {
      head: false,
      body: false,
      shield: false,
      accessories: [false, false],
    },
    stats: {
      initial: {
        HP: 18,
        PWR: 16,
        SKL: 17,
        DEF: 12,
        SPD: 13,
        MGC: 5,
        LUK: 9,
      },
      growths: {
        PWR: 3,
        SKL: 3,
        DEF: 3,
        SPD: 4,
        MGC: 1,
        LUK: 3,
      },
    },
  },
  BLACKMAN: {
    name: 'Blackman',
    range: RANGE.MEDIUM,
    rune: RUNES.NONE,
    isRuneLocked: false,
    weapon: {
      id: 58,
      lvl: 3,
    },
    wearClasses: [WEAR_CLASSES.CAP, WEAR_CLASSES.HEAVY_ARMOR, WEAR_CLASSES.MALE],
    armor: {
      head: null,
      body: ARMOR.LEATHER_COAT,
      shield: null,
      accessories: [null, null],
    },
    isArmorLocked: {
      head: false,
      body: false,
      shield: false,
      accessories: [false, false],
    },
    stats: {
      initial: {
        HP: 28,
        PWR: 16,
        SKL: 9,
        DEF: 18,
        SPD: 8,
        MGC: 5,
        LUK: 7,
      },
      growths: {
        PWR: 5,
        SKL: 3,
        DEF: 6,
        SPD: 3,
        MGC: 1,
        LUK: 3,
      },
    },
  },
  CAMILLE: {
    name: 'Camille',
    range: RANGE.MEDIUM,
    rune: RUNES.NONE,
    isRuneLocked: false,
    weapon: {
      id: 6,
      lvl: 4,
    },
    wearClasses: [WEAR_CLASSES.CAP, WEAR_CLASSES.LIGHT_ARMOR, WEAR_CLASSES.FEMALE],
    armor: {
      head: ARMOR.BANDANNA,
      body: ARMOR.TUNIC,
      shield: null,
      accessories: [null, null],
    },
    isArmorLocked: {
      head: false,
      body: false,
      shield: false,
      accessories: [false, false],
    },
    stats: {
      initial: {
        HP: 20,
        PWR: 13,
        SKL: 19,
        DEF: 12,
        SPD: 18,
        MGC: 13,
        LUK: 12,
      },
      growths: {
        PWR: 5,
        SKL: 8,
        DEF: 4,
        SPD: 5,
        MGC: 5,
        LUK: 3,
      },
    },
  },
  CLEO: {
    name: 'Cleo',
    range: RANGE.LONG,
    rune: RUNES.NONE,
    isRuneLocked: false,
    weapon: {
      id: 4,
      lvl: 1,
    },
    wearClasses: [WEAR_CLASSES.HELMET, WEAR_CLASSES.LIGHT_ARMOR, WEAR_CLASSES.FEMALE],
    armor: {
      head: null,
      body: ARMOR.TUNIC,
      shield: null,
      accessories: [ARMOR.CIRCLET, null],
    },
    isArmorLocked: {
      head: false,
      body: false,
      shield: false,
      accessories: [false, false],
    },
    stats: {
      initial: {
        HP: 20,
        PWR: 12,
        SKL: 20,
        DEF: 15,
        SPD: 12,
        MGC: 21,
        LUK: 20,
      },
      growths: {
        PWR: 5,
        SKL: 6,
        DEF: 5,
        SPD: 6,
        MGC: 6,
        LUK: 2,
      },
    },
  },
  CLIVE: {
    name: 'Clive',
    range: RANGE.LONG,
    rune: RUNES.NONE,
    isRuneLocked: false,
    weapon: {
      id: 74,
      lvl: 13,
    },
    wearClasses: [WEAR_CLASSES.CAP, WEAR_CLASSES.LIGHT_ARMOR, WEAR_CLASSES.MALE],
    armor: {
      head: null,
      body: ARMOR.MAGIC_ROBE,
      shield: null,
      accessories: [ARMOR.CAPE, null],
    },
    isArmorLocked: {
      head: false,
      body: false,
      shield: false,
      accessories: [false, false],
    },
    stats: {
      initial: {
        HP: 24,
        PWR: 16,
        SKL: 22,
        DEF: 9,
        SPD: 17,
        MGC: 5,
        LUK: 6,
      },
      growths: {
        PWR: 6,
        SKL: 8,
        DEF: 3,
        SPD: 6,
        MGC: 2,
        LUK: 1,
      },
    },
  },
  CROWLEY: {
    name: 'Crowley',
    range: RANGE.SHORT,
    rune: RUNES.CYCLONE,
    isRuneLocked: false,
    weapon: {
      id: 76,
      lvl: 2,
    },
    wearClasses: [WEAR_CLASSES.CAP, WEAR_CLASSES.ROBE, WEAR_CLASSES.MALE],
    armor: {
      head: null,
      body: ARMOR.MASTER_ROBE,
      shield: null,
      accessories: [ARMOR.EMBLEM, null],
    },
    isArmorLocked: {
      head: false,
      body: true,
      shield: false,
      accessories: [true, false],
    },
    stats: {
      initial: {
        HP: 16,
        PWR: 7,
        SKL: 6,
        DEF: 5,
        SPD: 9,
        MGC: 27,
        LUK: 13,
      },
      growths: {
        PWR: 2,
        SKL: 3,
        DEF: 1,
        SPD: 5,
        MGC: 8,
        LUK: 3,
      },
    },
  },
  EIKEI: {
    name: 'Eikei',
    range: RANGE.SHORT,
    rune: RUNES.DOUBLE_BEAT,
    isRuneLocked: false,
    weapon: {
      id: 64,
      lvl: 6,
    },
    wearClasses: [WEAR_CLASSES.CAP, WEAR_CLASSES.VEST, WEAR_CLASSES.MALE],
    armor: {
      head: null,
      body: ARMOR.KARATE_UNIFORM,
      shield: null,
      accessories: [null, null],
    },
    isArmorLocked: {
      head: false,
      body: false,
      shield: false,
      accessories: [false, false],
    },
    stats: {
      initial: {
        HP: 26,
        PWR: 16,
        SKL: 19,
        DEF: 17,
        SPD: 13,
        MGC: 2,
        LUK: 7,
      },
      growths: {
        PWR: 5,
        SKL: 4,
        DEF: 5,
        SPD: 2,
        MGC: 0,
        LUK: 3,
      },
    },
  },
  EILEEN: {
    name: 'Eileen',
    range: RANGE.LONG,
    rune: RUNES.EARTH,
    isRuneLocked: false,
    weapon: {
      id: 17,
      lvl: 4,
    },
    wearClasses: [WEAR_CLASSES.CAP, WEAR_CLASSES.ROBE, WEAR_CLASSES.FEMALE],
    armor: {
      head: null,
      body: ARMOR.ROBE,
      shield: null,
      accessories: [ARMOR.STAR_EARRINGS, null],
    },
    isArmorLocked: {
      head: false,
      body: false,
      shield: false,
      accessories: [true, false],
    },
    stats: {
      initial: {
        HP: 15,
        PWR: 9,
        SKL: 12,
        DEF: 11,
        SPD: 15,
        MGC: 17,
        LUK: 15,
      },
      growths: {
        PWR: 2,
        SKL: 4,
        DEF: 2,
        SPD: 6,
        MGC: 7,
        LUK: 5,
      },
    },
  },
  FLIK: {
    name: 'Flik',
    range: RANGE.SHORT,
    rune: RUNES.LIGHTNING,
    isRuneLocked: false,
    weapon: {
      id: 11,
      lvl: 9,
    },
    wearClasses: [
      WEAR_CLASSES.CAP,
      WEAR_CLASSES.LIGHT_ARMOR,
      WEAR_CLASSES.SHIELD,
      WEAR_CLASSES.MALE,
    ],
    armor: {
      head: ARMOR.BANDANNA,
      body: ARMOR.BRASS_ARMOR,
      shield: ARMOR.WOODEN_SHIELD,
      accessories: [ARMOR.CAPE, null],
    },
    isArmorLocked: {
      head: false,
      body: false,
      shield: false,
      accessories: [false, false],
    },
    stats: {
      initial: {
        HP: 24,
        PWR: 17,
        SKL: 16,
        DEF: 13,
        SPD: 16,
        MGC: 15,
        LUK: 14,
      },
      growths: {
        PWR: 6,
        SKL: 6,
        DEF: 4,
        SPD: 6,
        MGC: 5,
        LUK: 4,
      },
    },
  },
  FU_SU_LU: {
    name: 'Fu Su Lu',
    range: RANGE.SHORT,
    rune: RUNES.NONE,
    isRuneLocked: false,
    weapon: {
      id: 49,
      lvl: 6,
    },
    wearClasses: [WEAR_CLASSES.HELMET, WEAR_CLASSES.VEST, WEAR_CLASSES.MALE],
    armor: {
      head: null,
      body: ARMOR.LEATHER_COAT,
      shield: null,
      accessories: [ARMOR.FUR_CAPE, null],
    },
    isArmorLocked: {
      head: false,
      body: false,
      shield: false,
      accessories: [false, false],
    },
    stats: {
      initial: {
        HP: 35,
        PWR: 30,
        SKL: 5,
        DEF: 22,
        SPD: 3,
        MGC: 1,
        LUK: 2,
      },
      growths: {
        PWR: 8,
        SKL: 1,
        DEF: 6,
        SPD: 1,
        MGC: 0,
        LUK: 1,
      },
    },
  },
  FUKIEN: {
    name: 'Fukien',
    range: RANGE.SHORT,
    rune: RUNES.RESURRECTION,
    isRuneLocked: true,
    weapon: {
      id: 27,
      lvl: 9,
    },
    wearClasses: [WEAR_CLASSES.CAP, WEAR_CLASSES.VEST, WEAR_CLASSES.MALE],
    armor: {
      head: null,
      body: ARMOR.LEATHER_COAT,
      shield: null,
      accessories: [null, null],
    },
    isArmorLocked: {
      head: false,
      body: false,
      shield: false,
      accessories: [false, false],
    },
    stats: {
      initial: {
        HP: 16,
        PWR: 8,
        SKL: 12,
        DEF: 9,
        SPD: 12,
        MGC: 10,
        LUK: 20,
      },
      growths: {
        PWR: 2,
        SKL: 3,
        DEF: 4,
        SPD: 4,
        MGC: 6,
        LUK: 5,
      },
    },
  },
  FUMA: {
    name: 'Fuma',
    range: RANGE.LONG,
    rune: RUNES.NONE,
    isRuneLocked: false,
    weapon: {
      id: 53,
      lvl: 11,
    },
    wearClasses: [WEAR_CLASSES.CAP, WEAR_CLASSES.VEST, WEAR_CLASSES.MALE],
    armor: {
      head: null,
      body: ARMOR.NINJA_SUIT,
      shield: null,
      accessories: [null, null],
    },
    isArmorLocked: {
      head: false,
      body: false,
      shield: false,
      accessories: [false, false],
    },
    stats: {
      initial: {
        HP: 17,
        PWR: 14,
        SKL: 16,
        DEF: 11,
        SPD: 17,
        MGC: 5,
        LUK: 13,
      },
      growths: {
        PWR: 5,
        SKL: 5,
        DEF: 5,
        SPD: 6,
        MGC: 1,
        LUK: 3,
      },
    },
  },
  FUTCH: {
    name: 'Futch',
    range: RANGE.MEDIUM,
    rune: RUNES.NONE,
    isRuneLocked: false,
    weapon: {
      id: 28,
      lvl: 9,
    },
    wearClasses: [
      WEAR_CLASSES.HELMET,
      WEAR_CLASSES.LIGHT_ARMOR,
      WEAR_CLASSES.SHIELD,
      WEAR_CLASSES.MALE,
    ],
    armor: {
      head: ARMOR.HALF_HELMET,
      body: ARMOR.LEATHER_ARMOR,
      shield: null,
      accessories: [null, null],
    },
    isArmorLocked: {
      head: false,
      body: false,
      shield: false,
      accessories: [false, false],
    },
    stats: {
      initial: {
        HP: 16,
        PWR: 14,
        SKL: 13,
        DEF: 12,
        SPD: 17,
        MGC: 10,
        LUK: 15,
      },
      growths: {
        PWR: 5,
        SKL: 4,
        DEF: 5,
        SPD: 6,
        MGC: 2,
        LUK: 6,
      },
    },
  },
  GEN: {
    name: 'Gen',
    range: RANGE.SHORT,
    rune: RUNES.NONE,
    isRuneLocked: false,
    weapon: {
      id: 22,
      lvl: 9,
    },
    wearClasses: [WEAR_CLASSES.CAP, WEAR_CLASSES.LIGHT_ARMOR, WEAR_CLASSES.MALE],
    armor: {
      head: ARMOR.HEADBAND,
      body: ARMOR.KARATE_UNIFORM,
      shield: null,
      accessories: [null, null],
    },
    isArmorLocked: {
      head: false,
      body: false,
      shield: false,
      accessories: [false, false],
    },
    stats: {
      initial: {
        HP: 27,
        PWR: 19,
        SKL: 13,
        DEF: 17,
        SPD: 15,
        MGC: 2,
        LUK: 18,
      },
      growths: {
        PWR: 6,
        SKL: 5,
        DEF: 4,
        SPD: 4,
        MGC: 2,
        LUK: 4,
      },
    },
  },
  GON: {
    name: 'Gon',
    range: RANGE.SHORT,
    rune: RUNES.NONE,
    isRuneLocked: false,
    weapon: {
      id: 50,
      lvl: 7,
    },
    wearClasses: [
      WEAR_CLASSES.HELMET,
      WEAR_CLASSES.LIGHT_ARMOR,
      WEAR_CLASSES.SHIELD,
      WEAR_CLASSES.KOBOLD,
    ],
    armor: {
      head: ARMOR.HEADBAND,
      body: ARMOR.LEATHER_COAT,
      shield: null,
      accessories: [null, null],
    },
    isArmorLocked: {
      head: false,
      body: false,
      shield: false,
      accessories: [false, false],
    },
    stats: {
      initial: {
        HP: 17,
        PWR: 13,
        SKL: 14,
        DEF: 16,
        SPD: 11,
        MGC: 12,
        LUK: 27,
      },
      growths: {
        PWR: 4,
        SKL: 4,
        DEF: 5,
        SPD: 3,
        MGC: 2,
        LUK: 8,
      },
    },
  },
  GREMIO: {
    name: 'Gremio',
    range: RANGE.MEDIUM,
    rune: RUNES.NONE,
    isRuneLocked: false,
    weapon: {
      id: 2,
      lvl: 1,
    },
    wearClasses: [WEAR_CLASSES.CAP, WEAR_CLASSES.LIGHT_ARMOR, WEAR_CLASSES.MALE],
    armor: {
      head: null,
      body: ARMOR.LEATHER_COAT,
      shield: null,
      accessories: [ARMOR.CAPE, null],
    },
    isArmorLocked: {
      head: false,
      body: false,
      shield: false,
      accessories: [false, false],
    },
    stats: {
      initial: {
        HP: 22,
        PWR: 17,
        SKL: 12,
        DEF: 16,
        SPD: 10,
        MGC: 7,
        LUK: 10,
      },
      growths: {
        PWR: 13,
        SKL: 5,
        DEF: 6,
        SPD: 3,
        MGC: 2,
        LUK: 5,
      },
    },
  },
  GRENSEAL: {
    name: 'Grenseal',
    range: RANGE.SHORT,
    rune: RUNES.THUNDER,
    isRuneLocked: true,
    weapon: {
      id: 43,
      lvl: 7,
    },
    wearClasses: [
      WEAR_CLASSES.HELMET,
      WEAR_CLASSES.LIGHT_ARMOR,
      WEAR_CLASSES.SHIELD,
      WEAR_CLASSES.MALE,
    ],
    armor: {
      head: null,
      body: ARMOR.LEATHER_ARMOR,
      shield: ARMOR.STEEL_SHIELD,
      accessories: [null, null],
    },
    isArmorLocked: {
      head: false,
      body: false,
      shield: false,
      accessories: [false, false],
    },
    stats: {
      initial: {
        HP: 21,
        PWR: 14,
        SKL: 12,
        DEF: 16,
        SPD: 12,
        MGC: 15,
        LUK: 9,
      },
      growths: {
        PWR: 5,
        SKL: 4,
        DEF: 5,
        SPD: 5,
        MGC: 6,
        LUK: 3,
      },
    },
  },
  GRIFFITH: {
    name: 'Griffith',
    range: RANGE.SHORT,
    rune: RUNES.NONE,
    isRuneLocked: false,
    weapon: {
      id: 35,
      lvl: 8,
    },
    wearClasses: [
      WEAR_CLASSES.HELMET,
      WEAR_CLASSES.LIGHT_ARMOR,
      WEAR_CLASSES.SHIELD,
      WEAR_CLASSES.MALE,
    ],
    armor: {
      head: null,
      body: ARMOR.LEATHER_ARMOR,
      shield: null,
      accessories: [null, null],
    },
    isArmorLocked: {
      head: false,
      body: false,
      shield: false,
      accessories: [false, false],
    },
    stats: {
      initial: {
        HP: 21,
        PWR: 15,
        SKL: 12,
        DEF: 16,
        SPD: 12,
        MGC: 11,
        LUK: 13,
      },
      growths: {
        PWR: 5,
        SKL: 3,
        DEF: 4,
        SPD: 3,
        MGC: 2,
        LUK: 3,
      },
    },
  },
  HELLION: {
    name: 'Hellion',
    range: RANGE.SHORT,
    rune: RUNES.MOTHER_EARTH,
    isRuneLocked: true,
    weapon: {
      id: 67,
      lvl: 3,
    },
    wearClasses: [WEAR_CLASSES.CAP, WEAR_CLASSES.ROBE, WEAR_CLASSES.FEMALE],
    armor: {
      head: null,
      body: ARMOR.GUARD_ROBE,
      shield: null,
      accessories: [null, null],
    },
    isArmorLocked: {
      head: false,
      body: false,
      shield: false,
      accessories: [false, false],
    },
    stats: {
      initial: {
        HP: 20,
        PWR: 2,
        SKL: 2,
        DEF: 5,
        SPD: 4,
        MGC: 23,
        LUK: 13,
      },
      growths: {
        PWR: 1,
        SKL: 1,
        DEF: 3,
        SPD: 3,
        MGC: 7,
        LUK: 4,
      },
    },
  },
  HIX: {
    name: 'Hix',
    range: RANGE.SHORT,
    rune: RUNES.NONE,
    isRuneLocked: false,
    weapon: {
      id: 31,
      lvl: 10,
    },
    wearClasses: [
      WEAR_CLASSES.HELMET,
      WEAR_CLASSES.LIGHT_ARMOR,
      WEAR_CLASSES.SHIELD,
      WEAR_CLASSES.MALE,
    ],
    armor: {
      head: ARMOR.HALF_HELMET,
      body: ARMOR.LEATHER_ARMOR,
      shield: ARMOR.WOODEN_SHIELD,
      accessories: [ARMOR.BOOTS, null],
    },
    isArmorLocked: {
      head: false,
      body: false,
      shield: false,
      accessories: [false, false],
    },
    stats: {
      initial: {
        HP: 24,
        PWR: 17,
        SKL: 15,
        DEF: 13,
        SPD: 16,
        MGC: 9,
        LUK: 21,
      },
      growths: {
        PWR: 5,
        SKL: 5,
        DEF: 4,
        SPD: 5,
        MGC: 3,
        LUK: 7,
      },
    },
  },
  HUMPHREY: {
    name: 'Humphrey',
    range: RANGE.SHORT,
    rune: RUNES.NONE,
    isRuneLocked: false,
    weapon: {
      id: 10,
      lvl: 7,
    },
    wearClasses: [WEAR_CLASSES.HELMET, WEAR_CLASSES.HEAVY_ARMOR, WEAR_CLASSES.MALE],
    armor: {
      head: null,
      body: ARMOR.BRASS_ARMOR,
      shield: null,
      accessories: [ARMOR.CAPE, null],
    },
    isArmorLocked: {
      head: false,
      body: false,
      shield: false,
      accessories: [false, false],
    },
    stats: {
      initial: {
        HP: 35,
        PWR: 22,
        SKL: 15,
        DEF: 19,
        SPD: 7,
        MGC: 2,
        LUK: 9,
      },
      growths: {
        PWR: 6,
        SKL: 3,
        DEF: 7,
        SPD: 2,
        MGC: 1,
        LUK: 3,
      },
    },
  },
  JUPPO: {
    name: 'Juppo',
    range: RANGE.LONG,
    rune: RUNES.TRICK,
    isRuneLocked: true,
    weapon: {
      id: 19,
      lvl: 4,
    },
    wearClasses: [WEAR_CLASSES.CAP, WEAR_CLASSES.VEST, WEAR_CLASSES.MALE],
    armor: {
      head: ARMOR.POINTED_HAT,
      body: ARMOR.TUNIC,
      shield: null,
      accessories: [null, null],
    },
    isArmorLocked: {
      head: false,
      body: false,
      shield: false,
      accessories: [false, false],
    },
    stats: {
      initial: {
        HP: 20,
        PWR: 9,
        SKL: 21,
        DEF: 15,
        SPD: 13,
        MGC: 17,
        LUK: 8,
      },
      growths: {
        PWR: 3,
        SKL: 7,
        DEF: 4,
        SPD: 4,
        MGC: 4,
        LUK: 6,
      },
    },
  },
  KAGE: {
    name: 'Kage',
    range: RANGE.LONG,
    rune: RUNES.NONE,
    isRuneLocked: false,
    weapon: {
      id: 44,
      lvl: 9,
    },
    wearClasses: [WEAR_CLASSES.CAP, WEAR_CLASSES.VEST, WEAR_CLASSES.MALE],
    armor: {
      head: null,
      body: ARMOR.KARATE_UNIFORM,
      shield: null,
      accessories: [null, null],
    },
    isArmorLocked: {
      head: false,
      body: false,
      shield: false,
      accessories: [false, false],
    },
    stats: {
      initial: {
        HP: 20,
        PWR: 13,
        SKL: 17,
        DEF: 11,
        SPD: 21,
        MGC: 9,
        LUK: 8,
      },
      growths: {
        PWR: 4,
        SKL: 6,
        DEF: 5,
        SPD: 7,
        MGC: 3,
        LUK: 3,
      },
    },
  },
  KAI: {
    name: 'Kai',
    range: RANGE.MEDIUM,
    rune: RUNES.HAZY,
    isRuneLocked: true,
    weapon: {
      id: 63,
      lvl: 8,
    },
    wearClasses: [WEAR_CLASSES.CAP, WEAR_CLASSES.VEST, WEAR_CLASSES.MALE],
    armor: {
      head: ARMOR.HEADBAND,
      body: ARMOR.KARATE_UNIFORM,
      shield: null,
      accessories: [null, null],
    },
    isArmorLocked: {
      head: false,
      body: false,
      shield: false,
      accessories: [false, false],
    },
    stats: {
      initial: {
        HP: 24,
        PWR: 19,
        SKL: 15,
        DEF: 16,
        SPD: 15,
        MGC: 3,
        LUK: 13,
      },
      growths: {
        PWR: 6,
        SKL: 3,
        DEF: 4,
        SPD: 2,
        MGC: 1,
        LUK: 3,
      },
    },
  },
  KAMANDOL: {
    name: 'Kamandol',
    range: RANGE.SHORT,
    rune: RUNES.NONE,
    isRuneLocked: false,
    weapon: {
      id: 23,
      lvl: 3,
    },
    wearClasses: [WEAR_CLASSES.HELMET, WEAR_CLASSES.VEST, WEAR_CLASSES.MALE],
    armor: {
      head: null,
      body: ARMOR.GUARD_ROBE,
      shield: null,
      accessories: [null, null],
    },
    isArmorLocked: {
      head: false,
      body: false,
      shield: false,
      accessories: [false, false],
    },
    stats: {
      initial: {
        HP: 24,
        PWR: 11,
        SKL: 21,
        DEF: 9,
        SPD: 11,
        MGC: 8,
        LUK: 9,
      },
      growths: {
        PWR: 4,
        SKL: 7,
        DEF: 2,
        SPD: 3,
        MGC: 3,
        LUK: 2,
      },
    },
  },
  KANAK: {
    name: 'Kanak',
    range: RANGE.MEDIUM,
    rune: RUNES.NONE,
    isRuneLocked: false,
    weapon: {
      id: 48,
      lvl: 4,
    },
    wearClasses: [WEAR_CLASSES.CAP, WEAR_CLASSES.LIGHT_ARMOR, WEAR_CLASSES.MALE],
    armor: {
      head: null,
      body: ARMOR.LEATHER_COAT,
      shield: null,
      accessories: [null, null],
    },
    isArmorLocked: {
      head: false,
      body: false,
      shield: false,
      accessories: [false, false],
    },
    stats: {
      initial: {
        HP: 25,
        PWR: 14,
        SKL: 15,
        DEF: 13,
        SPD: 17,
        MGC: 1,
        LUK: 3,
      },
      growths: {
        PWR: 5,
        SKL: 5,
        DEF: 4,
        SPD: 6,
        MGC: 0,
        LUK: 2,
      },
    },
  },
  KASIM: {
    name: 'Kasim',
    range: RANGE.SHORT,
    rune: RUNES.NONE,
    isRuneLocked: false,
    weapon: {
      id: 36,
      lvl: 13,
    },
    wearClasses: [WEAR_CLASSES.HELMET, WEAR_CLASSES.LIGHT_ARMOR, WEAR_CLASSES.MALE],
    armor: {
      head: null,
      body: ARMOR.NINJA_SUIT,
      shield: null,
      accessories: [ARMOR.GAUNTLET, null],
    },
    isArmorLocked: {
      head: false,
      body: false,
      shield: false,
      accessories: [false, false],
    },
    stats: {
      initial: {
        HP: 24,
        PWR: 23,
        SKL: 13,
        DEF: 17,
        SPD: 9,
        MGC: 5,
        LUK: 11,
      },
      growths: {
        PWR: 7,
        SKL: 4,
        DEF: 6,
        SPD: 3,
        MGC: 1,
        LUK: 2,
      },
    },
  },
  KASUMI: {
    name: 'Kasumi',
    range: RANGE.LONG,
    rune: RUNES.SHRIKE,
    isRuneLocked: true,
    weapon: {
      id: 25,
      lvl: 6,
    },
    wearClasses: [WEAR_CLASSES.CAP, WEAR_CLASSES.VEST, WEAR_CLASSES.FEMALE],
    armor: {
      head: ARMOR.HEADBAND,
      body: ARMOR.KARATE_UNIFORM,
      shield: null,
      accessories: [null, null],
    },
    isArmorLocked: {
      head: false,
      body: false,
      shield: false,
      accessories: [false, false],
    },
    stats: {
      initial: {
        HP: 24,
        PWR: 16,
        SKL: 19,
        DEF: 13,
        SPD: 24,
        MGC: 13,
        LUK: 15,
      },
      growths: {
        PWR: 5,
        SKL: 6,
        DEF: 4,
        SPD: 8,
        MGC: 4,
        LUK: 3,
      },
    },
  },
  KESSLER: {
    name: 'Kessler',
    range: RANGE.MEDIUM,
    rune: RUNES.NONE,
    isRuneLocked: false,
    weapon: {
      id: 12,
      lvl: 9,
    },
    wearClasses: [WEAR_CLASSES.CAP, WEAR_CLASSES.HEAVY_ARMOR, WEAR_CLASSES.MALE],
    armor: {
      head: null,
      body: ARMOR.LEATHER_COAT,
      shield: null,
      accessories: [null, null],
    },
    isArmorLocked: {
      head: false,
      body: false,
      shield: false,
      accessories: [false, false],
    },
    stats: {
      initial: {
        HP: 26,
        PWR: 15,
        SKL: 16,
        DEF: 13,
        SPD: 12,
        MGC: 10,
        LUK: 11,
      },
      growths: {
        PWR: 5,
        SKL: 5,
        DEF: 4,
        SPD: 3,
        MGC: 2,
        LUK: 3,
      },
    },
  },
  KIMBERLY: {
    name: 'Kimberly',
    range: RANGE.SHORT,
    rune: RUNES.NONE,
    isRuneLocked: false,
    weapon: {
      id: 24,
      lvl: 8,
    },
    wearClasses: [WEAR_CLASSES.CAP, WEAR_CLASSES.LIGHT_ARMOR, WEAR_CLASSES.FEMALE],
    armor: {
      head: null,
      body: ARMOR.LEATHER_COAT,
      shield: null,
      accessories: [ARMOR.WOODEN_SHOES, null],
    },
    isArmorLocked: {
      head: false,
      body: false,
      shield: false,
      accessories: [false, false],
    },
    stats: {
      initial: {
        HP: 26,
        PWR: 13,
        SKL: 19,
        DEF: 11,
        SPD: 21,
        MGC: 11,
        LUK: 13,
      },
      growths: {
        PWR: 4,
        SKL: 6,
        DEF: 4,
        SPD: 5,
        MGC: 2,
        LUK: 5,
      },
    },
  },
  KIRKE: {
    name: 'Kirke',
    range: RANGE.SHORT,
    rune: RUNES.NONE,
    isRuneLocked: false,
    weapon: {
      id: 60,
      lvl: 5,
    },
    wearClasses: [WEAR_CLASSES.CAP, WEAR_CLASSES.LIGHT_ARMOR, WEAR_CLASSES.MALE],
    armor: {
      head: null,
      body: ARMOR.LEATHER_COAT,
      shield: null,
      accessories: [null, null],
    },
    isArmorLocked: {
      head: false,
      body: false,
      shield: false,
      accessories: [false, false],
    },
    stats: {
      initial: {
        HP: 20,
        PWR: 14,
        SKL: 17,
        DEF: 13,
        SPD: 12,
        MGC: 10,
        LUK: 2,
      },
      growths: {
        PWR: 5,
        SKL: 4,
        DEF: 4,
        SPD: 3,
        MGC: 2,
        LUK: 0,
      },
    },
  },
  KIRKIS: {
    name: 'Kirkis',
    range: RANGE.LONG,
    rune: RUNES.NONE,
    isRuneLocked: false,
    weapon: {
      id: 20,
      lvl: 5,
    },
    wearClasses: [WEAR_CLASSES.CAP, WEAR_CLASSES.LIGHT_ARMOR, WEAR_CLASSES.MALE],
    armor: {
      head: ARMOR.BANDANNA,
      body: ARMOR.BRASS_ARMOR,
      shield: null,
      accessories: [null, null],
    },
    isArmorLocked: {
      head: false,
      body: false,
      shield: false,
      accessories: [false, false],
    },
    stats: {
      initial: {
        HP: 20,
        PWR: 13,
        SKL: 21,
        DEF: 12,
        SPD: 15,
        MGC: 11,
        LUK: 12,
      },
      growths: {
        PWR: 5,
        SKL: 8,
        DEF: 5,
        SPD: 6,
        MGC: 5,
        LUK: 3,
      },
    },
  },
  KREUTZ: {
    name: 'Kreutz',
    range: RANGE.SHORT,
    rune: RUNES.NONE,
    isRuneLocked: false,
    weapon: {
      id: 59,
      lvl: 9,
    },
    wearClasses: [
      WEAR_CLASSES.HELMET,
      WEAR_CLASSES.HEAVY_ARMOR,
      WEAR_CLASSES.SHIELD,
      WEAR_CLASSES.MALE,
    ],
    armor: {
      head: null,
      body: ARMOR.HALF_ARMOR,
      shield: ARMOR.STEEL_SHIELD,
      accessories: [null, null],
    },
    isArmorLocked: {
      head: false,
      body: false,
      shield: false,
      accessories: [false, false],
    },
    stats: {
      initial: {
        HP: 27,
        PWR: 19,
        SKL: 17,
        DEF: 18,
        SPD: 3,
        MGC: 2,
        LUK: 10,
      },
      growths: {
        PWR: 6,
        SKL: 3,
        DEF: 6,
        SPD: 1,
        MGC: 1,
        LUK: 1,
      },
    },
  },
  KRIN: {
    name: 'Krin',
    range: RANGE.LONG,
    rune: RUNES.NONE,
    isRuneLocked: false,
    weapon: {
      id: 18,
      lvl: 2,
    },
    wearClasses: [WEAR_CLASSES.CAP, WEAR_CLASSES.VEST, WEAR_CLASSES.MALE],
    armor: {
      head: null,
      body: ARMOR.TUNIC,
      shield: null,
      accessories: [null, null],
    },
    isArmorLocked: {
      head: false,
      body: false,
      shield: false,
      accessories: [false, false],
    },
    stats: {
      initial: {
        HP: 13,
        PWR: 3,
        SKL: 12,
        DEF: 2,
        SPD: 25,
        MGC: 4,
        LUK: 6,
      },
      growths: {
        PWR: 3,
        SKL: 6,
        DEF: 2,
        SPD: 8,
        MGC: 1,
        LUK: 1,
      },
    },
  },
  KUROMIMI: {
    name: 'Kuromimi',
    range: RANGE.SHORT,
    rune: RUNES.NONE,
    isRuneLocked: false,
    weapon: {
      id: 41,
      lvl: 6,
    },
    wearClasses: [
      WEAR_CLASSES.HELMET,
      WEAR_CLASSES.LIGHT_ARMOR,
      WEAR_CLASSES.SHIELD,
      WEAR_CLASSES.KOBOLD,
    ],
    armor: {
      head: ARMOR.HEADBAND,
      body: ARMOR.BRASS_ARMOR,
      shield: ARMOR.WOODEN_SHIELD,
      accessories: [null, null],
    },
    isArmorLocked: {
      head: false,
      body: false,
      shield: false,
      accessories: [false, false],
    },
    stats: {
      initial: {
        HP: 18,
        PWR: 15,
        SKL: 12,
        DEF: 12,
        SPD: 9,
        MGC: 5,
        LUK: 13,
      },
      growths: {
        PWR: 5,
        SKL: 4,
        DEF: 5,
        SPD: 5,
        MGC: 2,
        LUK: 5,
      },
    },
  },
  KWANDA: {
    name: 'Kwanda',
    range: RANGE.MEDIUM,
    rune: RUNES.NONE,
    isRuneLocked: false,
    weapon: {
      id: 32,
      lvl: 6,
    },
    wearClasses: [
      WEAR_CLASSES.HELMET,
      WEAR_CLASSES.HEAVY_ARMOR,
      WEAR_CLASSES.SHIELD,
      WEAR_CLASSES.MALE,
    ],
    armor: {
      head: ARMOR.HALF_HELMET,
      body: ARMOR.LEATHER_ARMOR,
      shield: null,
      accessories: [null, null],
    },
    isArmorLocked: {
      head: false,
      body: false,
      shield: false,
      accessories: [false, false],
    },
    stats: {
      initial: {
        HP: 26,
        PWR: 18,
        SKL: 9,
        DEF: 25,
        SPD: 5,
        MGC: 3,
        LUK: 7,
      },
      growths: {
        PWR: 6,
        SKL: 3,
        DEF: 8,
        SPD: 2,
        MGC: 1,
        LUK: 3,
      },
    },
  },
  LEONARDO: {
    name: 'Leonardo',
    range: RANGE.MEDIUM,
    rune: RUNES.NONE,
    isRuneLocked: false,
    weapon: {
      id: 47,
      lvl: 5,
    },
    wearClasses: [WEAR_CLASSES.HELMET, WEAR_CLASSES.LIGHT_ARMOR, WEAR_CLASSES.MALE],
    armor: {
      head: null,
      body: ARMOR.TUNIC,
      shield: null,
      accessories: [null, null],
    },
    isArmorLocked: {
      head: false,
      body: false,
      shield: false,
      accessories: [false, false],
    },
    stats: {
      initial: {
        HP: 26,
        PWR: 17,
        SKL: 7,
        DEF: 13,
        SPD: 15,
        MGC: 5,
        LUK: 8,
      },
      growths: {
        PWR: 6,
        SKL: 3,
        DEF: 4,
        SPD: 4,
        MGC: 1,
        LUK: 1,
      },
    },
  },
  LEPANT: {
    name: 'Lepant',
    range: RANGE.SHORT,
    rune: RUNES.NONE,
    isRuneLocked: false,
    weapon: {
      id: 16,
      lvl: 5,
    },
    wearClasses: [
      WEAR_CLASSES.CAP,
      WEAR_CLASSES.LIGHT_ARMOR,
      WEAR_CLASSES.SHIELD,
      WEAR_CLASSES.MALE,
    ],
    armor: {
      head: null,
      body: ARMOR.BRASS_ARMOR,
      shield: ARMOR.WOODEN_SHIELD,
      accessories: [null, null],
    },
    isArmorLocked: {
      head: false,
      body: false,
      shield: false,
      accessories: [false, false],
    },
    stats: {
      initial: {
        HP: 24,
        PWR: 21,
        SKL: 18,
        DEF: 16,
        SPD: 11,
        MGC: 12,
        LUK: 9,
      },
      growths: {
        PWR: 5,
        SKL: 5,
        DEF: 4,
        SPD: 4,
        MGC: 3,
        LUK: 4,
      },
    },
  },
  LESTER: {
    name: 'Lester',
    range: RANGE.MEDIUM,
    rune: RUNES.NONE,
    isRuneLocked: false,
    weapon: {
      id: 69,
      lvl: 3,
    },
    wearClasses: [WEAR_CLASSES.CAP, WEAR_CLASSES.VEST, WEAR_CLASSES.SHIELD, WEAR_CLASSES.MALE],
    armor: {
      head: null,
      body: ARMOR.LEATHER_COAT,
      shield: null,
      accessories: [null, null],
    },
    isArmorLocked: {
      head: false,
      body: false,
      shield: false,
      accessories: [false, false],
    },
    stats: {
      initial: {
        HP: 14,
        PWR: 17,
        SKL: 18,
        DEF: 13,
        SPD: 14,
        MGC: 6,
        LUK: 10,
      },
      growths: {
        PWR: 4,
        SKL: 4,
        DEF: 3,
        SPD: 5,
        MGC: 1,
        LUK: 5,
      },
    },
  },
  LIUKAN: {
    name: 'Liukan',
    range: RANGE.SHORT,
    rune: RUNES.NONE,
    isRuneLocked: false,
    weapon: {
      id: 21,
      lvl: 2,
    },
    wearClasses: [WEAR_CLASSES.CAP, WEAR_CLASSES.ROBE, WEAR_CLASSES.SHIELD, WEAR_CLASSES.MALE],
    armor: {
      head: null,
      body: ARMOR.GUARD_ROBE,
      shield: null,
      accessories: [null, null],
    },
    isArmorLocked: {
      head: false,
      body: false,
      shield: false,
      accessories: [false, false],
    },
    stats: {
      initial: {
        HP: 16,
        PWR: 9,
        SKL: 18,
        DEF: 7,
        SPD: 11,
        MGC: 13,
        LUK: 16,
      },
      growths: {
        PWR: 3,
        SKL: 7,
        DEF: 3,
        SPD: 4,
        MGC: 3,
        LUK: 5,
      },
    },
  },
  LORELAI: {
    name: 'Lorelai',
    range: RANGE.LONG,
    rune: RUNES.NONE,
    isRuneLocked: false,
    weapon: {
      id: 54,
      lvl: 5,
    },
    wearClasses: [
      WEAR_CLASSES.HELMET,
      WEAR_CLASSES.LIGHT_ARMOR,
      WEAR_CLASSES.SHIELD,
      WEAR_CLASSES.FEMALE,
    ],
    armor: {
      head: ARMOR.HEADBAND,
      body: ARMOR.TUNIC,
      shield: null,
      accessories: [null, null],
    },
    isArmorLocked: {
      head: false,
      body: false,
      shield: false,
      accessories: [false, false],
    },
    stats: {
      initial: {
        HP: 20,
        PWR: 17,
        SKL: 25,
        DEF: 13,
        SPD: 9,
        MGC: 7,
        LUK: 15,
      },
      growths: {
        PWR: 5,
        SKL: 7,
        DEF: 4,
        SPD: 3,
        MGC: 2,
        LUK: 2,
      },
    },
  },
  LOTTE: {
    name: 'Lotte',
    range: RANGE.SHORT,
    rune: RUNES.EARTH,
    isRuneLocked: false,
    weapon: {
      id: 52,
      lvl: 4,
    },
    wearClasses: [WEAR_CLASSES.CAP, WEAR_CLASSES.LIGHT_ARMOR, WEAR_CLASSES.FEMALE],
    armor: {
      head: null,
      body: ARMOR.GUARD_ROBE,
      shield: null,
      accessories: [null, null],
    },
    isArmorLocked: {
      head: false,
      body: false,
      shield: false,
      accessories: [false, false],
    },
    stats: {
      initial: {
        HP: 16,
        PWR: 12,
        SKL: 14,
        DEF: 13,
        SPD: 16,
        MGC: 18,
        LUK: 11,
      },
      growths: {
        PWR: 3,
        SKL: 4,
        DEF: 3,
        SPD: 5,
        MGC: 6,
        LUK: 4,
      },
    },
  },
  LUC: {
    name: 'Luc',
    range: RANGE.SHORT,
    rune: RUNES.WIND,
    isRuneLocked: false,
    weapon: {
      id: 15,
      lvl: 3,
    },
    wearClasses: [WEAR_CLASSES.CAP, WEAR_CLASSES.ROBE, WEAR_CLASSES.MALE],
    armor: {
      head: null,
      body: ARMOR.GUARD_ROBE,
      shield: null,
      accessories: [ARMOR.SPEED_RING, null],
    },
    isArmorLocked: {
      head: false,
      body: true,
      shield: false,
      accessories: [true, false],
    },
    stats: {
      initial: {
        HP: 13,
        PWR: 3,
        SKL: 7,
        DEF: 2,
        SPD: 16,
        MGC: 27,
        LUK: 6,
      },
      growths: {
        PWR: 0,
        SKL: 5,
        DEF: 1,
        SPD: 5,
        MGC: 8,
        LUK: 1,
      },
    },
  },
  MAAS: {
    name: 'Maas',
    range: RANGE.MEDIUM,
    rune: RUNES.NONE,
    isRuneLocked: false,
    weapon: {
      id: 70,
      lvl: 3,
    },
    wearClasses: [WEAR_CLASSES.CAP, WEAR_CLASSES.LIGHT_ARMOR, WEAR_CLASSES.MALE],
    armor: {
      head: null,
      body: ARMOR.LEATHER_COAT,
      shield: null,
      accessories: [null, null],
    },
    isArmorLocked: {
      head: false,
      body: false,
      shield: false,
      accessories: [false, false],
    },
    stats: {
      initial: {
        HP: 20,
        PWR: 13,
        SKL: 15,
        DEF: 14,
        SPD: 12,
        MGC: 10,
        LUK: 15,
      },
      growths: {
        PWR: 4,
        SKL: 5,
        DEF: 4,
        SPD: 4,
        MGC: 2,
        LUK: 4,
      },
    },
  },
  MACE: {
    name: 'Mace',
    range: RANGE.MEDIUM,
    rune: RUNES.NONE,
    isRuneLocked: false,
    weapon: {
      id: 73,
      lvl: 15,
    },
    wearClasses: [WEAR_CLASSES.CAP, WEAR_CLASSES.LIGHT_ARMOR, WEAR_CLASSES.MALE],
    armor: {
      head: null,
      body: ARMOR.LEATHER_ARMOR,
      shield: null,
      accessories: [null, null],
    },
    isArmorLocked: {
      head: false,
      body: false,
      shield: false,
      accessories: [false, false],
    },
    stats: {
      initial: {
        HP: 27,
        PWR: 16,
        SKL: 21,
        DEF: 17,
        SPD: 13,
        MGC: 10,
        LUK: 15,
      },
      growths: {
        PWR: 6,
        SKL: 6,
        DEF: 6,
        SPD: 5,
        MGC: 3,
        LUK: 5,
      },
    },
  },
  MEESE: {
    name: 'Meese',
    range: RANGE.MEDIUM,
    rune: RUNES.NONE,
    isRuneLocked: false,
    weapon: {
      id: 71,
      lvl: 9,
    },
    wearClasses: [WEAR_CLASSES.CAP, WEAR_CLASSES.LIGHT_ARMOR, WEAR_CLASSES.MALE],
    armor: {
      head: null,
      body: ARMOR.LEATHER_COAT,
      shield: null,
      accessories: [null, null],
    },
    isArmorLocked: {
      head: false,
      body: false,
      shield: false,
      accessories: [false, false],
    },
    stats: {
      initial: {
        HP: 20,
        PWR: 13,
        SKL: 15,
        DEF: 14,
        SPD: 12,
        MGC: 10,
        LUK: 15,
      },
      growths: {
        PWR: 4,
        SKL: 5,
        DEF: 4,
        SPD: 4,
        MGC: 2,
        LUK: 4,
      },
    },
  },
  MEG: {
    name: 'Meg',
    range: RANGE.LONG,
    rune: RUNES.NONE,
    isRuneLocked: false,
    weapon: {
      id: 61,
      lvl: 6,
    },
    wearClasses: [WEAR_CLASSES.CAP, WEAR_CLASSES.VEST, WEAR_CLASSES.FEMALE],
    armor: {
      head: null,
      body: ARMOR.GUARD_ROBE,
      shield: null,
      accessories: [null, null],
    },
    isArmorLocked: {
      head: false,
      body: true,
      shield: false,
      accessories: [false, false],
    },
    stats: {
      initial: {
        HP: 16,
        PWR: 11,
        SKL: 17,
        DEF: 13,
        SPD: 12,
        MGC: 9,
        LUK: 25,
      },
      growths: {
        PWR: 4,
        SKL: 5,
        DEF: 4,
        SPD: 4,
        MGC: 3,
        LUK: 8,
      },
    },
  },
  MILIA: {
    name: 'Milia',
    range: RANGE.MEDIUM,
    rune: RUNES.NONE,
    isRuneLocked: false,
    weapon: {
      id: 29,
      lvl: 9,
    },
    wearClasses: [
      WEAR_CLASSES.HELMET,
      WEAR_CLASSES.LIGHT_ARMOR,
      WEAR_CLASSES.SHIELD,
      WEAR_CLASSES.FEMALE,
    ],
    armor: {
      head: null,
      body: ARMOR.LEATHER_ARMOR,
      shield: ARMOR.WOODEN_SHIELD,
      accessories: [null, null],
    },
    isArmorLocked: {
      head: false,
      body: false,
      shield: false,
      accessories: [false, false],
    },
    stats: {
      initial: {
        HP: 27,
        PWR: 18,
        SKL: 12,
        DEF: 14,
        SPD: 9,
        MGC: 3,
        LUK: 7,
      },
      growths: {
        PWR: 6,
        SKL: 3,
        DEF: 6,
        SPD: 3,
        MGC: 1,
        LUK: 4,
      },
    },
  },
  MILICH: {
    name: 'Milich',
    range: RANGE.SHORT,
    rune: RUNES.NONE,
    isRuneLocked: false,
    weapon: {
      id: 34,
      lvl: 6,
    },
    wearClasses: [
      WEAR_CLASSES.CAP,
      WEAR_CLASSES.LIGHT_ARMOR,
      WEAR_CLASSES.SHIELD,
      WEAR_CLASSES.NOBILITY,
    ],
    armor: {
      head: ARMOR.POINTED_HAT,
      body: ARMOR.GUARD_ROBE,
      shield: null,
      accessories: [ARMOR.ROSE_BROOCH, null],
    },
    isArmorLocked: {
      head: false,
      body: false,
      shield: false,
      accessories: [true, false],
    },
    stats: {
      initial: {
        HP: 24,
        PWR: 17,
        SKL: 15,
        DEF: 17,
        SPD: 16,
        MGC: 20,
        LUK: 7,
      },
      growths: {
        PWR: 5,
        SKL: 4,
        DEF: 5,
        SPD: 4,
        MGC: 6,
        LUK: 1,
      },
    },
  },
  MINA: {
    name: 'Mina',
    range: RANGE.SHORT,
    rune: RUNES.NONE,
    isRuneLocked: false,
    weapon: {
      id: 57,
      lvl: 6,
    },
    wearClasses: [WEAR_CLASSES.CAP, WEAR_CLASSES.LIGHT_ARMOR, WEAR_CLASSES.FEMALE],
    armor: {
      head: null,
      body: ARMOR.MAGIC_ROBE,
      shield: null,
      accessories: [ARMOR.TOE_SHOES, null],
    },
    isArmorLocked: {
      head: false,
      body: false,
      shield: false,
      accessories: [true, false],
    },
    stats: {
      initial: {
        HP: 16,
        PWR: 6,
        SKL: 13,
        DEF: 11,
        SPD: 15,
        MGC: 17,
        LUK: 22,
      },
      growths: {
        PWR: 2,
        SKL: 4,
        DEF: 4,
        SPD: 4,
        MGC: 6,
        LUK: 6,
      },
    },
  },
  MOOSE: {
    name: 'Moose',
    range: RANGE.MEDIUM,
    rune: RUNES.NONE,
    isRuneLocked: false,
    weapon: {
      id: 72,
      lvl: 12,
    },
    wearClasses: [WEAR_CLASSES.CAP, WEAR_CLASSES.LIGHT_ARMOR, WEAR_CLASSES.MALE],
    armor: {
      head: null,
      body: ARMOR.LEATHER_COAT,
      shield: null,
      accessories: [null, null],
    },
    isArmorLocked: {
      head: false,
      body: false,
      shield: false,
      accessories: [false, false],
    },
    stats: {
      initial: {
        HP: 20,
        PWR: 13,
        SKL: 15,
        DEF: 14,
        SPD: 12,
        MGC: 10,
        LUK: 15,
      },
      growths: {
        PWR: 4,
        SKL: 6,
        DEF: 4,
        SPD: 4,
        MGC: 2,
        LUK: 4,
      },
    },
  },
  MORGAN: {
    name: 'Morgan',
    range: RANGE.SHORT,
    rune: RUNES.COUNTER,
    isRuneLocked: false,
    weapon: {
      id: 55,
      lvl: 6,
    },
    wearClasses: [WEAR_CLASSES.CAP, WEAR_CLASSES.VEST, WEAR_CLASSES.MALE],
    armor: {
      head: ARMOR.HEADBAND,
      body: ARMOR.KARATE_UNIFORM,
      shield: null,
      accessories: [null, null],
    },
    isArmorLocked: {
      head: false,
      body: false,
      shield: false,
      accessories: [false, false],
    },
    stats: {
      initial: {
        HP: 24,
        PWR: 19,
        SKL: 9,
        DEF: 16,
        SPD: 7,
        MGC: 1,
        LUK: 12,
      },
      growths: {
        PWR: 6,
        SKL: 3,
        DEF: 5,
        SPD: 2,
        MGC: 0,
        LUK: 1,
      },
    },
  },
  MOSE: {
    name: 'Mose',
    range: RANGE.MEDIUM,
    rune: RUNES.NONE,
    isRuneLocked: false,
    weapon: {
      id: 26,
      lvl: 8,
    },
    wearClasses: [WEAR_CLASSES.HELMET, WEAR_CLASSES.LIGHT_ARMOR, WEAR_CLASSES.MALE],
    armor: {
      head: null,
      body: ARMOR.BRASS_ARMOR,
      shield: null,
      accessories: [null, null],
    },
    isArmorLocked: {
      head: false,
      body: false,
      shield: false,
      accessories: [false, false],
    },
    stats: {
      initial: {
        HP: 24,
        PWR: 15,
        SKL: 16,
        DEF: 13,
        SPD: 12,
        MGC: 10,
        LUK: 17,
      },
      growths: {
        PWR: 5,
        SKL: 5,
        DEF: 5,
        SPD: 4,
        MGC: 1,
        LUK: 3,
      },
    },
  },
  ODESSA: {
    name: 'Odessa',
    range: RANGE.LONG,
    rune: RUNES.WIND,
    isRuneLocked: true,
    weapon: {
      id: 78,
      lvl: 5,
    },
    wearClasses: [WEAR_CLASSES.CAP, WEAR_CLASSES.LIGHT_ARMOR, WEAR_CLASSES.FEMALE],
    armor: {
      head: ARMOR.HEAD_GEAR,
      body: ARMOR.TUNIC,
      shield: null,
      accessories: [null, null],
    },
    isArmorLocked: {
      head: true,
      body: false,
      shield: false,
      accessories: [false, false],
    },
    stats: {
      initial: {
        HP: 24,
        PWR: 13,
        SKL: 21,
        DEF: 12,
        SPD: 18,
        MGC: 10,
        LUK: 18,
      },
      growths: {
        PWR: 5,
        SKL: 8,
        DEF: 5,
        SPD: 8,
        MGC: 7,
        LUK: 6,
      },
    },
  },
  PAHN: {
    name: 'Pahn',
    range: RANGE.SHORT,
    rune: RUNES.BOAR,
    isRuneLocked: true,
    weapon: {
      id: 3,
      lvl: 1,
    },
    wearClasses: [WEAR_CLASSES.CAP, WEAR_CLASSES.VEST, WEAR_CLASSES.MALE],
    armor: {
      head: ARMOR.HEADBAND,
      body: ARMOR.TUNIC,
      shield: null,
      accessories: [ARMOR.GLOVES, null],
    },
    isArmorLocked: {
      head: false,
      body: false,
      shield: false,
      accessories: [false, false],
    },
    stats: {
      initial: {
        HP: 25,
        PWR: 25,
        SKL: 17,
        DEF: 18,
        SPD: 10,
        MGC: 3,
        LUK: 15,
      },
      growths: {
        PWR: 7,
        SKL: 5,
        DEF: 6,
        SPD: 2,
        MGC: 0,
        LUK: 4,
      },
    },
  },
  PESMERGA: {
    name: 'Pesmerga',
    range: RANGE.SHORT,
    rune: RUNES.NONE,
    isRuneLocked: false,
    weapon: {
      id: 75,
      lvl: 7,
    },
    wearClasses: [
      WEAR_CLASSES.HELMET,
      WEAR_CLASSES.HEAVY_ARMOR,
      WEAR_CLASSES.SHIELD,
      WEAR_CLASSES.MALE,
    ],
    armor: {
      head: ARMOR.HALF_HELMET,
      body: ARMOR.DRAGON_ARMOR,
      shield: ARMOR.STEEL_SHIELD,
      accessories: [null, null],
    },
    isArmorLocked: {
      head: false,
      body: true,
      shield: false,
      accessories: [false, false],
    },
    stats: {
      initial: {
        HP: 26,
        PWR: 22,
        SKL: 7,
        DEF: 17,
        SPD: 6,
        MGC: 3,
        LUK: 1,
      },
      growths: {
        PWR: 8,
        SKL: 2,
        DEF: 6,
        SPD: 3,
        MGC: 1,
        LUK: 0,
      },
    },
  },
  QUINCY: {
    name: 'Quincy',
    range: RANGE.LONG,
    rune: RUNES.NONE,
    isRuneLocked: false,
    weapon: {
      id: 56,
      lvl: 6,
    },
    wearClasses: [WEAR_CLASSES.CAP, WEAR_CLASSES.VEST, WEAR_CLASSES.MALE],
    armor: {
      head: null,
      body: ARMOR.GUARD_ROBE,
      shield: null,
      accessories: [ARMOR.FEATHER, null],
    },
    isArmorLocked: {
      head: false,
      body: false,
      shield: false,
      accessories: [false, false],
    },
    stats: {
      initial: {
        HP: 20,
        PWR: 13,
        SKL: 27,
        DEF: 16,
        SPD: 13,
        MGC: 5,
        LUK: 14,
      },
      growths: {
        PWR: 4,
        SKL: 8,
        DEF: 5,
        SPD: 5,
        MGC: 1,
        LUK: 5,
      },
    },
  },
  RONNIE: {
    name: 'Ronnie',
    range: RANGE.SHORT,
    rune: RUNES.HATE,
    isRuneLocked: true,
    weapon: {
      id: 40,
      lvl: 7,
    },
    wearClasses: [WEAR_CLASSES.CAP, WEAR_CLASSES.VEST, WEAR_CLASSES.FEMALE],
    armor: {
      head: ARMOR.HEADBAND,
      body: ARMOR.KARATE_UNIFORM,
      shield: null,
      accessories: [null, null],
    },
    isArmorLocked: {
      head: false,
      body: false,
      shield: false,
      accessories: [false, false],
    },
    stats: {
      initial: {
        HP: 24,
        PWR: 17,
        SKL: 13,
        DEF: 16,
        SPD: 9,
        MGC: 1,
        LUK: 7,
      },
      growths: {
        PWR: 6,
        SKL: 4,
        DEF: 6,
        SPD: 4,
        MGC: 0,
        LUK: 3,
      },
    },
  },
  RUBI: {
    name: 'Rubi',
    range: RANGE.LONG,
    rune: RUNES.NONE,
    isRuneLocked: false,
    weapon: {
      id: 51,
      lvl: 6,
    },
    wearClasses: [WEAR_CLASSES.CAP, WEAR_CLASSES.LIGHT_ARMOR, WEAR_CLASSES.MALE],
    armor: {
      head: ARMOR.BANDANNA,
      body: ARMOR.BRASS_ARMOR,
      shield: null,
      accessories: [null, null],
    },
    isArmorLocked: {
      head: false,
      body: false,
      shield: false,
      accessories: [false, false],
    },
    stats: {
      initial: {
        HP: 20,
        PWR: 14,
        SKL: 13,
        DEF: 12,
        SPD: 17,
        MGC: 18,
        LUK: 1,
      },
      growths: {
        PWR: 5,
        SKL: 6,
        DEF: 4,
        SPD: 6,
        MGC: 6,
        LUK: 0,
      },
    },
  },
  SANSUKE: {
    name: 'Sansuke',
    range: RANGE.SHORT,
    rune: RUNES.NONE,
    isRuneLocked: false,
    weapon: {
      id: 66,
      lvl: 5,
    },
    wearClasses: [WEAR_CLASSES.CAP, WEAR_CLASSES.VEST, WEAR_CLASSES.MALE],
    armor: {
      head: null,
      body: ARMOR.TUNIC,
      shield: null,
      accessories: [null, null],
    },
    isArmorLocked: {
      head: false,
      body: false,
      shield: false,
      accessories: [false, false],
    },
    stats: {
      initial: {
        HP: 20,
        PWR: 11,
        SKL: 13,
        DEF: 15,
        SPD: 12,
        MGC: 4,
        LUK: 8,
      },
      growths: {
        PWR: 3,
        SKL: 5,
        DEF: 5,
        SPD: 4,
        MGC: 1,
        LUK: 4,
      },
    },
  },
  SARAH: {
    name: 'Sarah',
    range: RANGE.LONG,
    rune: RUNES.NONE,
    isRuneLocked: false,
    weapon: {
      id: 62,
      lvl: 2,
    },
    wearClasses: [WEAR_CLASSES.CAP, WEAR_CLASSES.VEST, WEAR_CLASSES.FEMALE],
    armor: {
      head: null,
      body: ARMOR.TUNIC,
      shield: null,
      accessories: [null, null],
    },
    isArmorLocked: {
      head: false,
      body: false,
      shield: false,
      accessories: [false, false],
    },
    stats: {
      initial: {
        HP: 20,
        PWR: 17,
        SKL: 11,
        DEF: 19,
        SPD: 13,
        MGC: 16,
        LUK: 8,
      },
      growths: {
        PWR: 5,
        SKL: 3,
        DEF: 5,
        SPD: 3,
        MGC: 4,
        LUK: 2,
      },
    },
  },
  SERGEI: {
    name: 'Sergei',
    range: RANGE.SHORT,
    rune: RUNES.NONE,
    isRuneLocked: false,
    weapon: {
      id: 65,
      lvl: 4,
    },
    wearClasses: [WEAR_CLASSES.CAP, WEAR_CLASSES.LIGHT_ARMOR, WEAR_CLASSES.MALE],
    armor: {
      head: null,
      body: ARMOR.ROBE,
      shield: null,
      accessories: [ARMOR.GLOVES, null],
    },
    isArmorLocked: {
      head: false,
      body: false,
      shield: false,
      accessories: [false, false],
    },
    stats: {
      initial: {
        HP: 20,
        PWR: 7,
        SKL: 17,
        DEF: 16,
        SPD: 9,
        MGC: 11,
        LUK: 13,
      },
      growths: {
        PWR: 2,
        SKL: 6,
        DEF: 6,
        SPD: 3,
        MGC: 2,
        LUK: 2,
      },
    },
  },
  SHEENA: {
    name: 'Sheena',
    range: RANGE.SHORT,
    rune: RUNES.LIGHTNING,
    isRuneLocked: true,
    weapon: {
      id: 45,
      lvl: 6,
    },
    wearClasses: [WEAR_CLASSES.CAP, WEAR_CLASSES.LIGHT_ARMOR, WEAR_CLASSES.MALE],
    armor: {
      head: null,
      body: ARMOR.TUNIC,
      shield: null,
      accessories: [null, null],
    },
    isArmorLocked: {
      head: false,
      body: false,
      shield: false,
      accessories: [false, false],
    },
    stats: {
      initial: {
        HP: 20,
        PWR: 16,
        SKL: 14,
        DEF: 15,
        SPD: 12,
        MGC: 15,
        LUK: 13,
      },
      growths: {
        PWR: 5,
        SKL: 4,
        DEF: 5,
        SPD: 6,
        MGC: 6,
        LUK: 6,
      },
    },
  },
  SONYA: {
    name: 'Sonya',
    range: RANGE.SHORT,
    rune: RUNES.WATER,
    isRuneLocked: false,
    weapon: {
      id: 37,
      lvl: 11,
    },
    wearClasses: [
      WEAR_CLASSES.HELMET,
      WEAR_CLASSES.LIGHT_ARMOR,
      WEAR_CLASSES.SHIELD,
      WEAR_CLASSES.FEMALE,
    ],
    armor: {
      head: null,
      body: ARMOR.LEATHER_ARMOR,
      shield: null,
      accessories: [ARMOR.CRIMSON_CAPE, null],
    },
    isArmorLocked: {
      head: false,
      body: false,
      shield: false,
      accessories: [true, false],
    },
    stats: {
      initial: {
        HP: 20,
        PWR: 16,
        SKL: 17,
        DEF: 13,
        SPD: 21,
        MGC: 18,
        LUK: 15,
      },
      growths: {
        PWR: 6,
        SKL: 5,
        DEF: 4,
        SPD: 7,
        MGC: 5,
        LUK: 3,
      },
    },
  },
  STALLION: {
    name: 'Stallion',
    range: RANGE.LONG,
    rune: RUNES.TRUE_HOLY,
    isRuneLocked: true,
    weapon: {
      id: 39,
      lvl: 6,
    },
    wearClasses: [WEAR_CLASSES.CAP, WEAR_CLASSES.LIGHT_ARMOR, WEAR_CLASSES.MALE],
    armor: {
      head: null,
      body: ARMOR.BRASS_ARMOR,
      shield: null,
      accessories: [ARMOR.WING_BOOTS, null],
    },
    isArmorLocked: {
      head: false,
      body: false,
      shield: false,
      accessories: [true, false],
    },
    stats: {
      initial: {
        HP: 16,
        PWR: 14,
        SKL: 9,
        DEF: 13,
        SPD: 19,
        MGC: 10,
        LUK: 13,
      },
      growths: {
        PWR: 3,
        SKL: 6,
        DEF: 5,
        SPD: 8,
        MGC: 4,
        LUK: 4,
      },
    },
  },
  SYDONIA: {
    name: 'Sydonia',
    range: RANGE.LONG,
    rune: RUNES.NONE,
    isRuneLocked: false,
    weapon: {
      id: 9,
      lvl: 6,
    },
    wearClasses: [WEAR_CLASSES.CAP, WEAR_CLASSES.VEST, WEAR_CLASSES.MALE],
    armor: {
      head: ARMOR.BANDANNA,
      body: ARMOR.LEATHER_COAT,
      shield: null,
      accessories: [null, null],
    },
    isArmorLocked: {
      head: false,
      body: false,
      shield: false,
      accessories: [false, false],
    },
    stats: {
      initial: {
        HP: 18,
        PWR: 17,
        SKL: 22,
        DEF: 9,
        SPD: 22,
        MGC: 7,
        LUK: 5,
      },
      growths: {
        PWR: 4,
        SKL: 6,
        DEF: 3,
        SPD: 6,
        MGC: 3,
        LUK: 2,
      },
    },
  },
  SYLVINA: {
    name: 'Sylvina',
    range: RANGE.LONG,
    rune: RUNES.NONE,
    isRuneLocked: false,
    weapon: {
      id: 38,
      lvl: 5,
    },
    wearClasses: [WEAR_CLASSES.CAP, WEAR_CLASSES.ROBE, WEAR_CLASSES.FEMALE],
    armor: {
      head: null,
      body: ARMOR.ROBE,
      shield: null,
      accessories: [null, null],
    },
    isArmorLocked: {
      head: false,
      body: false,
      shield: false,
      accessories: [false, false],
    },
    stats: {
      initial: {
        HP: 16,
        PWR: 9,
        SKL: 13,
        DEF: 8,
        SPD: 15,
        MGC: 17,
        LUK: 22,
      },
      growths: {
        PWR: 3,
        SKL: 5,
        DEF: 4,
        SPD: 6,
        MGC: 5,
        LUK: 6,
      },
    },
  },
  TAI_HO: {
    name: 'Tai Ho',
    range: RANGE.MEDIUM,
    rune: RUNES.NONE,
    isRuneLocked: false,
    weapon: {
      id: 13,
      lvl: 3,
    },
    wearClasses: [WEAR_CLASSES.CAP, WEAR_CLASSES.VEST, WEAR_CLASSES.MALE],
    armor: {
      head: ARMOR.HEADBAND,
      body: ARMOR.TUNIC,
      shield: null,
      accessories: [null, null],
    },
    isArmorLocked: {
      head: false,
      body: false,
      shield: false,
      accessories: [false, false],
    },
    stats: {
      initial: {
        HP: 24,
        PWR: 21,
        SKL: 14,
        DEF: 12,
        SPD: 11,
        MGC: 10,
        LUK: 12,
      },
      growths: {
        PWR: 6,
        SKL: 7,
        DEF: 3,
        SPD: 5,
        MGC: 1,
        LUK: 4,
      },
    },
  },
  TENGAAR: {
    name: 'Tengaar',
    range: RANGE.LONG,
    rune: RUNES.NONE,
    isRuneLocked: false,
    weapon: {
      id: 30,
      lvl: 7,
    },
    wearClasses: [WEAR_CLASSES.CAP, WEAR_CLASSES.ROBE, WEAR_CLASSES.FEMALE],
    armor: {
      head: null,
      body: ARMOR.GUARD_ROBE,
      shield: null,
      accessories: [ARMOR.GUARD_RING, null],
    },
    isArmorLocked: {
      head: false,
      body: false,
      shield: false,
      accessories: [false, false],
    },
    stats: {
      initial: {
        HP: 19,
        PWR: 10,
        SKL: 16,
        DEF: 12,
        SPD: 12,
        MGC: 19,
        LUK: 8,
      },
      growths: {
        PWR: 3,
        SKL: 6,
        DEF: 4,
        SPD: 5,
        MGC: 7,
        LUK: 2,
      },
    },
  },
  TED: {
    name: 'Ted',
    range: RANGE.LONG,
    rune: RUNES.UNKNOWN,
    isRuneLocked: true,
    weapon: {
      id: 77,
      lvl: 3,
    },
    wearClasses: [WEAR_CLASSES.CAP, WEAR_CLASSES.ROBE, WEAR_CLASSES.MALE],
    armor: {
      head: null,
      body: ARMOR.ROBE,
      shield: null,
      accessories: [null, null],
    },
    isArmorLocked: {
      head: false,
      body: false,
      shield: false,
      accessories: [false, false],
    },
    stats: {
      initial: {
        HP: 18,
        PWR: 13,
        SKL: 20,
        DEF: 10,
        SPD: 15,
        MGC: 12,
        LUK: 15,
      },
      growths: {
        PWR: 5,
        SKL: 7,
        DEF: 4,
        SPD: 6,
        MGC: 7,
        LUK: 4,
      },
    },
  },
  VALERIA: {
    name: 'Valeria',
    range: RANGE.SHORT,
    rune: RUNES.FALCON,
    isRuneLocked: true,
    weapon: {
      id: 33,
      lvl: 7,
    },
    wearClasses: [
      WEAR_CLASSES.HELMET,
      WEAR_CLASSES.LIGHT_ARMOR,
      WEAR_CLASSES.SHIELD,
      WEAR_CLASSES.FEMALE,
    ],
    armor: {
      head: null,
      body: ARMOR.BRASS_ARMOR,
      shield: ARMOR.WOODEN_SHIELD,
      accessories: [null, null],
    },
    isArmorLocked: {
      head: false,
      body: false,
      shield: false,
      accessories: [false, false],
    },
    stats: {
      initial: {
        HP: 26,
        PWR: 16,
        SKL: 17,
        DEF: 11,
        SPD: 20,
        MGC: 15,
        LUK: 12,
      },
      growths: {
        PWR: 6,
        SKL: 4,
        DEF: 6,
        SPD: 3,
        MGC: 3,
        LUK: 4,
      },
    },
  },
  VARKAS: {
    name: 'Varkas',
    range: RANGE.MEDIUM,
    rune: RUNES.NONE,
    isRuneLocked: false,
    weapon: {
      id: 8,
      lvl: 5,
    },
    wearClasses: [WEAR_CLASSES.HELMET, WEAR_CLASSES.HEAVY_ARMOR, WEAR_CLASSES.MALE],
    armor: {
      head: null,
      body: ARMOR.BRASS_ARMOR,
      shield: null,
      accessories: [ARMOR.LEGGINGS, null],
    },
    isArmorLocked: {
      head: false,
      body: false,
      shield: false,
      accessories: [false, false],
    },
    stats: {
      initial: {
        HP: 30,
        PWR: 21,
        SKL: 9,
        DEF: 14,
        SPD: 12,
        MGC: 7,
        LUK: 11,
      },
      growths: {
        PWR: 6,
        SKL: 3,
        DEF: 5,
        SPD: 3,
        MGC: 1,
        LUK: 2,
      },
    },
  },
  VIKTOR: {
    name: 'Viktor',
    range: RANGE.SHORT,
    rune: RUNES.NONE,
    isRuneLocked: false,
    weapon: {
      id: 5,
      lvl: 3,
    },
    wearClasses: [WEAR_CLASSES.CAP, WEAR_CLASSES.LIGHT_ARMOR, WEAR_CLASSES.MALE],
    armor: {
      head: null,
      body: ARMOR.LEATHER_COAT,
      shield: null,
      accessories: [ARMOR.BOOTS, null],
    },
    isArmorLocked: {
      head: false,
      body: false,
      shield: false,
      accessories: [false, false],
    },
    stats: {
      initial: {
        HP: 26,
        PWR: 15,
        SKL: 9,
        DEF: 10,
        SPD: 5,
        MGC: 7,
        LUK: 11,
      },
      growths: {
        PWR: 9,
        SKL: 2,
        DEF: 7,
        SPD: 5,
        MGC: 3,
        LUK: 4,
      },
    },
  },
  WARREN: {
    name: 'Warren',
    range: RANGE.MEDIUM,
    rune: RUNES.NONE,
    isRuneLocked: false,
    weapon: {
      id: 7,
      lvl: 12,
    },
    wearClasses: [WEAR_CLASSES.HELMET, WEAR_CLASSES.LIGHT_ARMOR, WEAR_CLASSES.MALE],
    armor: {
      head: ARMOR.HALF_HELMET,
      body: ARMOR.LEATHER_ARMOR,
      shield: null,
      accessories: [null, null],
    },
    isArmorLocked: {
      head: false,
      body: false,
      shield: false,
      accessories: [false, false],
    },
    stats: {
      initial: {
        HP: 24,
        PWR: 17,
        SKL: 16,
        DEF: 16,
        SPD: 12,
        MGC: 10,
        LUK: 11,
      },
      growths: {
        PWR: 5,
        SKL: 4,
        DEF: 5,
        SPD: 3,
        MGC: 2,
        LUK: 3,
      },
    },
  },
  YAM_KOO: {
    name: 'Yam Koo',
    range: RANGE.MEDIUM,
    rune: RUNES.NONE,
    isRuneLocked: false,
    weapon: {
      id: 14,
      lvl: 3,
    },
    wearClasses: [WEAR_CLASSES.CAP, WEAR_CLASSES.VEST, WEAR_CLASSES.MALE],
    armor: {
      head: null,
      body: ARMOR.TUNIC,
      shield: null,
      accessories: [null, null],
    },
    isArmorLocked: {
      head: false,
      body: false,
      shield: false,
      accessories: [false, false],
    },
    stats: {
      initial: {
        HP: 20,
        PWR: 15,
        SKL: 17,
        DEF: 11,
        SPD: 19,
        MGC: 8,
        LUK: 15,
      },
      growths: {
        PWR: 5,
        SKL: 6,
        DEF: 3,
        SPD: 6,
        MGC: 2,
        LUK: 4,
      },
    },
  },
};
