export const WEAPON_TYPES = {
  BOW: {
    NAME: 'Bow',
    ATK: [5, 7, 10, 14, 18, 35, 42, 48, 54, 63, 70, 81, 105, 117, 132, 155],
  },
  STAFF: {
    NAME: 'Staff',
    ATK: [5, 7, 9, 12, 20, 25, 32, 39, 47, 57, 68, 91, 103, 117, 136, 158],
  },
  AXE: {
    NAME: 'Axe',
    ATK: [9, 14, 18, 23, 28, 32, 37, 42, 67, 77, 86, 95, 106, 130, 150, 170],
  },
  DARTS: {
    NAME: 'Darts',
    ATK: [6, 8, 11, 20, 25, 31, 35, 39, 45, 69, 78, 89, 99, 113, 128, 150],
  },
  CLAWS: {
    NAME: 'Claws',
    ATK: [6, 8, 10, 13, 17, 22, 28, 46, 55, 64, 75, 86, 95, 110, 130, 170],
  },
  TWO_HANDED_SWORD: {
    NAME: 'Two-handed Sword',
    ATK: [7, 9, 11, 14, 22, 27, 34, 41, 49, 59, 70, 93, 105, 119, 138, 160],
  },
  SPEAR: {
    NAME: 'Spear',
    ATK: [7, 11, 15, 19, 27, 33, 40, 47, 56, 66, 88, 97, 107, 119, 136, 150],
  },
  ROD: {
    NAME: 'Rod',
    ATK: [3, 5, 7, 10, 13, 17, 28, 33, 38, 44, 60, 70, 85, 100, 114, 130],
  },
  ONE_HANDED_SWORD: {
    NAME: 'One-handed Sword',
    ATK: [5, 7, 9, 12, 16, 20, 33, 40, 48, 59, 70, 80, 102, 115, 134, 150],
  },
  TALKING_SWORD: {
    NAME: 'Talking Sword',
    ATK: [9, 11, 13, 16, 25, 30, 39, 55, 62, 75, 83, 109, 112, 143, 163, 185],
  },
};

export const WEAPONS = [
  null,
  {
    NAMES: ['Wolf Fang Staff', 'Dragon Fang Staff', 'Heaven Fang Staff'],
    TYPE: WEAPON_TYPES.STAFF,
  },
  { NAMES: ['Axe', 'Copper Axe', 'Axe of the Oath'], TYPE: WEAPON_TYPES.AXE },
  { NAMES: ['Claws', 'Super Claws', 'Ultra Claws'], TYPE: WEAPON_TYPES.CLAWS },
  { NAMES: ['Air Sword', 'Air Moon Sword', 'Air Moonstar Sword'], TYPE: WEAPON_TYPES.DARTS },
  { NAMES: ['Taia Sword', 'Shiko Sword', 'Koten Sword'], TYPE: WEAPON_TYPES.TWO_HANDED_SWORD },
  { NAMES: ['Galm', 'Fenril', 'Loki'], TYPE: WEAPON_TYPES.SPEAR },
  { NAMES: ['Slavenil', 'Gunnigle', 'Odin'], TYPE: WEAPON_TYPES.SPEAR },
  { NAMES: ['Lighting Hatchet', 'Rockbreaker Hatchet', 'Leppa Hatchet'], TYPE: WEAPON_TYPES.AXE },
  { NAMES: ['Ruisui', 'Ryuseisui', 'Mikagetsusui'], TYPE: WEAPON_TYPES.DARTS },
  { NAMES: ['Masamune', 'Murasame', 'Murasama'], TYPE: WEAPON_TYPES.TWO_HANDED_SWORD },
  { NAMES: ['Odessa', 'Odessa+', 'Odessa++'], TYPE: WEAPON_TYPES.ONE_HANDED_SWORD },
  { NAMES: ['Axe', 'Battle Axe', 'Ogre Axe'], TYPE: WEAPON_TYPES.AXE },
  { NAMES: ['Satsuki', 'Akemi', 'Mizuki'], TYPE: WEAPON_TYPES.SPEAR },
  { NAMES: ['Uranami Spear', 'Seigetsu Spear', 'Matsukaze Spear'], TYPE: WEAPON_TYPES.SPEAR },
  { NAMES: ['Wind Rod', 'Gale Rod', 'Gust Rod'], TYPE: WEAPON_TYPES.ROD },
  { NAMES: ['Kirinji', 'Kirinji 2', 'Kirinji 3'], TYPE: WEAPON_TYPES.ONE_HANDED_SWORD },
  { NAMES: ['Darts', 'Ruby Darts', 'Crystal Darts'], TYPE: WEAPON_TYPES.DARTS },
  { NAMES: ['Needle', 'Gold Needle', 'Super Needle'], TYPE: WEAPON_TYPES.DARTS },
  { NAMES: ['Gear', 'Iron Gear', 'Metal Gear'], TYPE: WEAPON_TYPES.DARTS },
  { NAMES: ['Light Bow', 'Shine Bow', 'Elfin Bow'], TYPE: WEAPON_TYPES.BOW },
  { NAMES: ['Stick', 'Oak Stick', 'Ebony Stick'], TYPE: WEAPON_TYPES.ROD },
  { NAMES: ['Light Steel', 'Regular Steel', 'Heavy Steel'], TYPE: WEAPON_TYPES.TWO_HANDED_SWORD },
  { NAMES: ['Steed Rod', 'Master Rod', 'Rod of Hermes'], TYPE: WEAPON_TYPES.ROD },
  {
    NAMES: ['Kitchen Knife', 'Silver Kitchen Knife', 'Gold Kitchen Knife'],
    TYPE: WEAPON_TYPES.ONE_HANDED_SWORD,
  },
  { NAMES: ['Sakura', 'Big Sakura', 'Max Sakura'], TYPE: WEAPON_TYPES.DARTS },
  { NAMES: ['Aluminum Hammer', 'Titanium Hammer', 'Iron Hammer'], TYPE: WEAPON_TYPES.SPEAR },
  { NAMES: ['Punishment', 'Super Punishment', 'Ultra Punishment'], TYPE: WEAPON_TYPES.ROD },
  { NAMES: ['Verserk', 'Sigmund', 'Sigurd'], TYPE: WEAPON_TYPES.SPEAR },
  { NAMES: ['Valkryie', 'Valhalla', 'Brunhildt'], TYPE: WEAPON_TYPES.SPEAR },
  { NAMES: ['Light Knife', 'Ray Knife', 'Shining Knife'], TYPE: WEAPON_TYPES.ROD },
  { NAMES: ['Tengaar', 'Tengaar+', 'Tengaar++'], TYPE: WEAPON_TYPES.ONE_HANDED_SWORD },
  { NAMES: ['Alkaid Hatchet', 'Mizar Hatchet', 'Alioth Hatchet'], TYPE: WEAPON_TYPES.AXE },
  {
    NAMES: ['Star Sword', 'Seven Star Sword', 'Conqueror Star Sword'],
    TYPE: WEAPON_TYPES.ONE_HANDED_SWORD,
  },
  { NAMES: ['Rose', 'Marguerite', 'Orchid'], TYPE: WEAPON_TYPES.ONE_HANDED_SWORD },
  { NAMES: ['Black Knife', 'Black Blade', 'Black Sword'], TYPE: WEAPON_TYPES.ONE_HANDED_SWORD },
  {
    NAMES: ['Moonlight', 'Blue Moonlight', 'Emerald Moonlight'],
    TYPE: WEAPON_TYPES.TWO_HANDED_SWORD,
  },
  { NAMES: ['Blue', 'Turquoise Blue', 'Royal Blue'], TYPE: WEAPON_TYPES.ONE_HANDED_SWORD },
  { NAMES: ['Night Bow', 'Moon Bow', 'Elfin Bow'], TYPE: WEAPON_TYPES.BOW },
  { NAMES: ['Bow of Amrita', 'Bow of Shiva', 'Bow of Vishnu'], TYPE: WEAPON_TYPES.BOW },
  { NAMES: ['Claw', 'Tiger Claw', 'Dragon Claw'], TYPE: WEAPON_TYPES.CLAWS },
  { NAMES: ['Sword', 'Good Sword', 'Excellent Sword'], TYPE: WEAPON_TYPES.ONE_HANDED_SWORD },
  { NAMES: ['Fire Sword', 'Flame Sword', 'True Flame Sword'], TYPE: WEAPON_TYPES.ONE_HANDED_SWORD },
  {
    NAMES: ['Flashing Sword', 'Lightning Sword', 'True Lightning Sword'],
    TYPE: WEAPON_TYPES.ONE_HANDED_SWORD,
  },
  { NAMES: ['First Sword', 'Second Sword', 'Third Sword'], TYPE: WEAPON_TYPES.DARTS },
  { NAMES: ['Rapier', 'Silver Rapier', 'Platinum Rapier'], TYPE: WEAPON_TYPES.ONE_HANDED_SWORD },
  { NAMES: ['Demon Spear', 'Demon God Spear', 'Demon Army Spear'], TYPE: WEAPON_TYPES.SPEAR },
  {
    NAMES: ['Horse-killer Hatchet', 'Killer Steel Hatchet', 'Killer Big Hatchet'],
    TYPE: WEAPON_TYPES.AXE,
  },
  {
    NAMES: ['Sickle & chain', 'Steel sickle & chain', 'Copper sickle & chain'],
    TYPE: WEAPON_TYPES.SPEAR,
  },
  { NAMES: ['Double Axe', 'Double Big Axe', 'Double Battle Axe'], TYPE: WEAPON_TYPES.AXE },
  { NAMES: ['Sword', 'Cool Sword', 'Very Neat Sword'], TYPE: WEAPON_TYPES.ONE_HANDED_SWORD },
  { NAMES: ['Bow of Vlitra', 'Bow of Garuda', 'Bow of Ashra'], TYPE: WEAPON_TYPES.BOW },
  { NAMES: ['Silver Rod', 'Moon Rod', 'Star Rod'], TYPE: WEAPON_TYPES.ROD },
  { NAMES: ['Shuriken', 'Super Shuriken', 'Ultra Shuriken'], TYPE: WEAPON_TYPES.DARTS },
  { NAMES: ['Short Bow', 'Silver Bow', 'Magic Bow'], TYPE: WEAPON_TYPES.BOW },
  { NAMES: ['Talons', 'Hooked Talons', 'Hawk Talons'], TYPE: WEAPON_TYPES.CLAWS },
  { NAMES: ['Thunder', 'Lightning', 'Holy Thunderbolt'], TYPE: WEAPON_TYPES.DARTS },
  { NAMES: ['Pretty Shawl', 'Lovely Shawl', 'Sexy Shawl'], TYPE: WEAPON_TYPES.STAFF },
  { NAMES: ['Seeding How', 'Mowing How', 'Harvest How'], TYPE: WEAPON_TYPES.AXE },
  { NAMES: ['Denta', 'Big Denta', 'Kamui'], TYPE: WEAPON_TYPES.TWO_HANDED_SWORD },
  { NAMES: ['Tower', 'Death', 'Judgment'], TYPE: WEAPON_TYPES.TWO_HANDED_SWORD },
  { NAMES: ['Dagger', "Assassin's Dagger", 'Silver Dagger'], TYPE: WEAPON_TYPES.DARTS },
  { NAMES: ['Throwing Knife', 'Laser Knife', 'Slash Knife'], TYPE: WEAPON_TYPES.DARTS },
  { NAMES: ["Pilgrim's Staff", "Conjurer's Staff", "Exorcist's Staff"], TYPE: WEAPON_TYPES.STAFF },
  { NAMES: ['Wolf', 'Tiger', 'Dragon'], TYPE: WEAPON_TYPES.CLAWS },
  { NAMES: ['Wrench', 'Iron Wrench', 'Killer Wrench'], TYPE: WEAPON_TYPES.ROD },
  { NAMES: ['Saw', 'Long Saw', 'Giant Saw'], TYPE: WEAPON_TYPES.TWO_HANDED_SWORD },
  { NAMES: ['Rod', 'Earth Rod', 'Gaia Rod'], TYPE: WEAPON_TYPES.ROD },
  { NAMES: ['Milk Pan', 'Frying Pan', 'Ceramic Pan'], TYPE: WEAPON_TYPES.AXE },
  { NAMES: ['Pan', 'Pot', 'Wok'], TYPE: WEAPON_TYPES.AXE },
  { NAMES: ['Wooden Hammer', 'Stone Hammer', 'Rock Hammer'], TYPE: WEAPON_TYPES.SPEAR },
  { NAMES: ['Carbon Hammer', 'Chrome Hammer', 'Tin Hammer'], TYPE: WEAPON_TYPES.SPEAR },
  { NAMES: ['Brass Hammer', 'Bronze Hammer', 'Copper Hammer'], TYPE: WEAPON_TYPES.SPEAR },
  { NAMES: ['Silver Hammer', 'Gold Hammer', 'Platinum Hammer'], TYPE: WEAPON_TYPES.SPEAR },
  { NAMES: ['Wind', 'Storm', 'Tornado'], TYPE: WEAPON_TYPES.DARTS },
  { NAMES: ['Crimson', 'Death Crimson', 'King Crimson'], TYPE: WEAPON_TYPES.TWO_HANDED_SWORD },
  { NAMES: ['Comet Rod', 'Meteor Rod', 'Cosmo Rod'], TYPE: WEAPON_TYPES.ROD },
  { NAMES: ['Steel Bow', 'Copper Bow', 'Gold Bow'], TYPE: WEAPON_TYPES.BOW },
  { NAMES: ['Steel Bow', 'Copper Bow', 'Gold Bow'], TYPE: WEAPON_TYPES.BOW },
  {
    NAMES: ['Star Dragon Sword', 'Black Dragon Sword', 'King Dragon Sword'],
    TYPE: WEAPON_TYPES.TALKING_SWORD,
  },
];
