import { CHARACTER_KEYS, UNITE_KEYS } from '../Keys.js';

/** @typedef {import('../Keys.js').CharacterKey} CharacterKey */
/** @typedef {import('../Keys.js').UniteKey} UniteKey */

/**
 * Physical Unite animation timing, in frames (= battle ticks). Generated by Suikoden-Bizhawk-HUD's
 * scripts/AttackTimingWalker.py from each participant's 04_play/<code>.bin scripts. Talisman is
 * live-verified (scripts/VerifyTalismanUnite.lua, 2026-09-27): impacts, done bits, return
 * lengths and the target's reaction all match the walker exactly.
 *
 * Frame convention: S = the tick unite_gather_participants runs, the tick after the resolver
 * first finds every combatant idle. Every participant starts its Unite script on S, whoever
 * initiated. As for basic attacks, damage lands the tick after the gating script sets 0x2.
 *
 * @typedef {Object} UniteParticipantTiming
 * @property {number} script - Which slot of the participant's own script table the handler
 *   starts (the walker's --party <code> <slot> input).
 * @property {number | null} impact - S -> the frame its script sets effect flag 0x2 (null = never).
 *   Damage gated on it rolls at impact + 1.
 * @property {number} done - S -> the frame it sets 0x4. Its return script starts at done + 1,
 *   and the handler ends the tick after the last participant's done.
 *
 * @typedef {Object} UniteTiming
 * @property {UniteParticipantTiming[]} participants - Same def order as UNITES[key].participants.
 * @property {{ by: number, script: number, frames: number }} reaction - The target plays
 *   participant `by`'s (def-order index) script table slot `script` as its hit reaction:
 *   damage tick -> the frame its busy bit 8 clears.
 */

/**
 * Unites with a known timeline. Missing ones can't be simulated yet: which script slot each
 * participant plays (and whose reaction the target plays) is set in each Unite's own handler,
 * which hasn't been decompiled per Unite.
 * @satisfies {Partial<Record<UniteKey, UniteTiming>>}
 */
export const UNITE_TIMINGS = {
  [UNITE_KEYS.TALISMAN]: {
    participants: [
      { script: 9, impact: 66, done: 135 }, // Pahn
      { script: 9, impact: 74, done: 130 }, // Gremio
    ],
    reaction: { by: 1, script: 15, frames: 37 }, // Gremio's slot 15, same on every target walked
  },
};

/**
 * The shared return-to-position script (main.exe 0x8016d214) each participant starts the tick
 * after its own done bit: its start -> the frame the participant's busy clears. It runs on the
 * participant's own sprite, so it depends only on the character, not the Unite.
 * @satisfies {Partial<Record<CharacterKey, number>>}
 */
export const UNITE_RETURN_FRAMES = {
  [CHARACTER_KEYS.ALEN]: 45,
  [CHARACTER_KEYS.ANJI]: 45,
  [CHARACTER_KEYS.CAMILLE]: 45,
  [CHARACTER_KEYS.CLEO]: 21,
  [CHARACTER_KEYS.EIKEI]: 52,
  [CHARACTER_KEYS.EILEEN]: 21,
  [CHARACTER_KEYS.FLIK]: 45,
  [CHARACTER_KEYS.FUKIEN]: 44,
  [CHARACTER_KEYS.FUMA]: 21,
  [CHARACTER_KEYS.FUTCH]: 48,
  [CHARACTER_KEYS.FU_SU_LU]: 45,
  [CHARACTER_KEYS.GEN]: 44,
  [CHARACTER_KEYS.GON]: 45,
  [CHARACTER_KEYS.GREMIO]: 45,
  [CHARACTER_KEYS.GRENSEAL]: 45,
  [CHARACTER_KEYS.HIX]: 47,
  [CHARACTER_KEYS.HUMPHREY]: 45,
  [CHARACTER_KEYS.JUPPO]: 21,
  [CHARACTER_KEYS.KAGE]: 21,
  [CHARACTER_KEYS.KAI]: 45,
  [CHARACTER_KEYS.KAMANDOL]: 45,
  [CHARACTER_KEYS.KANAK]: 55,
  [CHARACTER_KEYS.KASUMI]: 125,
  [CHARACTER_KEYS.KIRKIS]: 21,
  [CHARACTER_KEYS.KRIN]: 21,
  [CHARACTER_KEYS.KUROMIMI]: 45,
  [CHARACTER_KEYS.LEONARDO]: 45,
  [CHARACTER_KEYS.LEPANT]: 45,
  [CHARACTER_KEYS.LIUKAN]: 44,
  [CHARACTER_KEYS.MAAS]: 45,
  [CHARACTER_KEYS.MACE]: 45,
  [CHARACTER_KEYS.MCDOHL]: 45,
  [CHARACTER_KEYS.MEESE]: 45,
  [CHARACTER_KEYS.MEG]: 21,
  [CHARACTER_KEYS.MILIA]: 45,
  [CHARACTER_KEYS.MOOSE]: 45,
  [CHARACTER_KEYS.MORGAN]: 52,
  [CHARACTER_KEYS.MOSE]: 48,
  [CHARACTER_KEYS.PAHN]: 52,
  [CHARACTER_KEYS.RONNIE]: 45,
  [CHARACTER_KEYS.RUBI]: 21,
  [CHARACTER_KEYS.SANSUKE]: 44,
  [CHARACTER_KEYS.SHEENA]: 47,
  [CHARACTER_KEYS.SONYA]: 178,
  [CHARACTER_KEYS.STALLION]: 21,
  [CHARACTER_KEYS.SYDONIA]: 21,
  [CHARACTER_KEYS.SYLVINA]: 21,
  [CHARACTER_KEYS.TAI_HO]: 51,
  [CHARACTER_KEYS.TENGAAR]: 21,
  [CHARACTER_KEYS.VALERIA]: 45,
  [CHARACTER_KEYS.VARKAS]: 45,
  [CHARACTER_KEYS.YAM_KOO]: 51,
};
