/**
 * @typedef {Object} ArmorSources
 * @property {string[]} shop
 * @property {string[]} treasure
 * @property {string[]} loot
 */

/**
 * @typedef {Object} ArmorStats
 * @property {number} DEF
 * @property {number} [PWR]
 * @property {number} [SKL]
 * @property {number} [SPD]
 * @property {number} [MGC]
 * @property {number} [LUK]
 */

/**
 * @typedef {Object} ArmorPiece
 * @property {string} name
 * @property {ArmorType} type
 * @property {number} bits
 * @property {ArmorStats} stats
 * @property {WearClass[]} wear
 * @property {string[]} description
 * @property {ArmorSources} sources
 */

/** @typedef {typeof ARMOR_TYPES[keyof typeof ARMOR_TYPES]} ArmorType */
export const ARMOR_TYPES = /** @type {const} */ ({
  HEAD: 'Head',
  BODY: 'Body',
  SHIELD: 'Shield',
  ACCESSORY: 'Accessory',
});

/** @typedef {typeof WEAR_CLASSES[keyof typeof WEAR_CLASSES]} WearClass */
export const WEAR_CLASSES = /** @type {const} */ ({
  CAP: 'C',
  HELMET: 'E',
  LIGHT_ARMOR: 'L',
  HEAVY_ARMOR: 'H',
  VEST: 'V',
  ROBE: 'R',
  SHIELD: 'S',
  MALE: 'M',
  FEMALE: 'F',
  KOBOLD: 'K',
  NOBILITY: 'N',
});

/** @satisfies {Record<string, ArmorPiece>} */
export const ARMOR = {
  BANDANNA: {
    name: 'Bandanna',
    type: ARMOR_TYPES.HEAD,
    bits: 50,
    stats: { DEF: 1 },
    wear: [WEAR_CLASSES.CAP],
    description: [],
    sources: {
      shop: ['Gregminster #1'],
      treasure: [],
      loot: ['Crow'],
    },
  },
  HEADBAND: {
    name: 'Headband',
    type: ARMOR_TYPES.HEAD,
    bits: 300,
    stats: { DEF: 2 },
    wear: [WEAR_CLASSES.CAP, WEAR_CLASSES.HELMET],
    description: [],
    sources: {
      shop: ['Gregminster', 'Rockland', 'Lenankamp'],
      treasure: [],
      loot: [],
    },
  },
  POINTED_HAT: {
    name: 'Pointed Hat',
    type: ARMOR_TYPES.HEAD,
    bits: 1200,
    stats: { DEF: 5 },
    wear: [WEAR_CLASSES.CAP],
    description: ['Prevents "Balloon"'],
    sources: {
      shop: ['Lenankamp', 'Kaku'],
      treasure: ['Toran Basement', "Dwarves' Vault"],
      loot: ['Red Soldier Ant', 'Soldier Ant', 'Robot Soldier (spear)'],
    },
  },
  HALF_HELMET: {
    name: 'Half Helmet',
    type: ARMOR_TYPES.HEAD,
    bits: 3300,
    stats: { DEF: 9 },
    wear: [WEAR_CLASSES.CAP, WEAR_CLASSES.HELMET],
    description: [],
    sources: {
      shop: ['Dwarf Village', 'Antei', 'Kirov'],
      treasure: ['Soniere'],
      loot: ['Death Machine (spear)'],
    },
  },
  HEAD_GEAR: {
    name: 'Head Gear',
    type: ARMOR_TYPES.HEAD,
    bits: 6500,
    stats: { DEF: 14 },
    wear: [WEAR_CLASSES.CAP],
    description: [],
    sources: {
      shop: ['Antei', "Warrior's Village"],
      treasure: ['Qlon Cave'],
      loot: ['Mad Ivy', 'Grizzly Bear'],
    },
  },
  FULL_HELMET: {
    name: 'Full Helmet',
    type: ARMOR_TYPES.HEAD,
    bits: 13200,
    stats: { DEF: 20 },
    wear: [WEAR_CLASSES.HELMET],
    description: [],
    sources: {
      shop: ["Warrior's Village"],
      treasure: ["Neclord's Castle"],
      loot: ['Grave Master'],
    },
  },
  SILVER_HAT: {
    name: 'Silver Hat',
    type: ARMOR_TYPES.HEAD,
    bits: 27000,
    stats: { DEF: 27 },
    wear: [WEAR_CLASSES.CAP],
    description: ['Auto-heal +5'],
    sources: {
      shop: ['Gregminster #2'],
      treasure: [],
      loot: ['Queen Ant'],
    },
  },
  HORNED_HELMET: {
    name: 'Horned Helmet',
    type: ARMOR_TYPES.HEAD,
    bits: 43000,
    stats: { DEF: 35 },
    wear: [WEAR_CLASSES.HELMET],
    description: [],
    sources: {
      shop: [],
      treasure: ['Gregminster Palace'],
      loot: ['Elite Soldier'],
    },
  },
  ROBE: {
    name: 'Robe',
    type: ARMOR_TYPES.BODY,
    bits: 100,
    stats: { DEF: 1 },
    wear: [WEAR_CLASSES.LIGHT_ARMOR, WEAR_CLASSES.VEST, WEAR_CLASSES.ROBE],
    description: [],
    sources: {
      shop: ['Gregminster #1'],
      treasure: [],
      loot: ['Holly Boy'],
    },
  },
  TUNIC: {
    name: 'Tunic',
    type: ARMOR_TYPES.BODY,
    bits: 200,
    stats: { DEF: 2 },
    wear: [WEAR_CLASSES.LIGHT_ARMOR, WEAR_CLASSES.VEST],
    description: [],
    sources: {
      shop: ['Gregminster #1', 'Rockland', 'Lenankamp'],
      treasure: [],
      loot: ['Bandit (green)'],
    },
  },
  LEATHER_COAT: {
    name: 'Leather Coat',
    type: ARMOR_TYPES.BODY,
    bits: 700,
    stats: { DEF: 4 },
    wear: [WEAR_CLASSES.LIGHT_ARMOR, WEAR_CLASSES.HEAVY_ARMOR, WEAR_CLASSES.VEST],
    description: [],
    sources: {
      shop: ['Gregminster #1', 'Rockland', 'Lenankamp', 'Kaku'],
      treasure: ["Magician's Island"],
      loot: [],
    },
  },
  BRASS_ARMOR: {
    name: 'Brass Armor',
    type: ARMOR_TYPES.BODY,
    bits: 1000,
    stats: { DEF: 5 },
    wear: [WEAR_CLASSES.LIGHT_ARMOR, WEAR_CLASSES.HEAVY_ARMOR],
    description: [],
    sources: {
      shop: ['Lenankamp', 'Kaku', 'Dwarf Village'],
      treasure: ["Grady's Mansion"],
      loot: ['Ghost Armor', 'Empire Soldier (sword #4)'],
    },
  },
  GUARD_ROBE: {
    name: 'Guard Robe',
    type: ARMOR_TYPES.BODY,
    bits: 1700,
    stats: { DEF: 7, MGC: 15 },
    wear: [WEAR_CLASSES.LIGHT_ARMOR, WEAR_CLASSES.VEST, WEAR_CLASSES.ROBE],
    description: [],
    sources: {
      shop: ['Kaku'],
      treasure: ["Dwarves' Trail"],
      loot: ['Kobold (mage)'],
    },
  },
  KARATE_UNIFORM: {
    name: 'Karate Uniform',
    type: ARMOR_TYPES.BODY,
    bits: 3000,
    stats: { DEF: 10 },
    wear: [WEAR_CLASSES.LIGHT_ARMOR, WEAR_CLASSES.VEST],
    description: [],
    sources: {
      shop: ['Kouan'],
      treasure: ["Dwarves' Trail"],
      loot: ['Slasher Rabbit', 'Dwarf'],
    },
  },
  LEATHER_ARMOR: {
    name: 'Leather Armor',
    type: ARMOR_TYPES.BODY,
    bits: 5900,
    stats: { DEF: 14 },
    wear: [WEAR_CLASSES.LIGHT_ARMOR, WEAR_CLASSES.HEAVY_ARMOR],
    description: [],
    sources: {
      shop: ['Kouan', 'Dwarf Village'],
      treasure: ["Lepant's House"],
      loot: ['Veteran Soldier (spear)'],
    },
  },
  HALF_ARMOR: {
    name: 'Half Armor',
    type: ARMOR_TYPES.BODY,
    bits: 8700,
    stats: { DEF: 18 },
    wear: [WEAR_CLASSES.HEAVY_ARMOR],
    description: [],
    sources: {
      shop: ['Dwarf Village'],
      treasure: ['Panna Yakuta'],
      loot: ['Dragon'],
    },
  },
  MAGIC_ROBE: {
    name: 'Magic Robe',
    type: ARMOR_TYPES.BODY,
    bits: 15000,
    stats: { DEF: 22 },
    wear: [WEAR_CLASSES.LIGHT_ARMOR, WEAR_CLASSES.VEST, WEAR_CLASSES.ROBE],
    description: [],
    sources: {
      shop: ['Antei'],
      treasure: ["Dwarves' Vault", 'Scarleticia'],
      loot: ['Holly Fairy'],
    },
  },
  NINJA_SUIT: {
    name: 'Ninja Suit',
    type: ARMOR_TYPES.BODY,
    bits: 22000,
    stats: { DEF: 28, SPD: 5 },
    wear: [WEAR_CLASSES.LIGHT_ARMOR, WEAR_CLASSES.VEST],
    description: [],
    sources: {
      shop: ['Antei', 'Kirov'],
      treasure: [],
      loot: ['Viperman'],
    },
  },
  DRAGON_ARMOR: {
    name: 'Dragon Armor',
    type: ARMOR_TYPES.BODY,
    bits: 37000,
    stats: { DEF: 34 },
    wear: [WEAR_CLASSES.LIGHT_ARMOR, WEAR_CLASSES.HEAVY_ARMOR],
    description: [],
    sources: {
      shop: ["Warrior's Village", 'Kirov', 'Gregminster #2'],
      treasure: [],
      loot: ['Dagon'],
    },
  },
  MASTER_ROBE: {
    name: 'Master Robe',
    type: ARMOR_TYPES.BODY,
    bits: 78000,
    stats: { DEF: 37 },
    wear: [WEAR_CLASSES.VEST, WEAR_CLASSES.ROBE],
    description: ['Auto-heal +5'],
    sources: {
      shop: ['Gregminster #2'],
      treasure: ['Seek Valley'],
      loot: ['Sorcerer'],
    },
  },
  FULL_ARMOR: {
    name: 'Full Armor',
    type: ARMOR_TYPES.BODY,
    bits: 57000,
    stats: { DEF: 45 },
    wear: [WEAR_CLASSES.HEAVY_ARMOR],
    description: [],
    sources: {
      shop: ["Warrior's Village"],
      treasure: [],
      loot: ['Clay Doll'],
    },
  },
  TAIKIOKU_WEAR: {
    name: 'Taikioku Wear',
    type: ARMOR_TYPES.BODY,
    bits: 80000,
    stats: { DEF: 48, SPD: 10 },
    wear: [WEAR_CLASSES.VEST],
    description: [],
    sources: {
      shop: [],
      treasure: ['Moravia'],
      loot: ['Rock Buster'],
    },
  },
  MASTER_GARB: {
    name: 'Master Garb',
    type: ARMOR_TYPES.BODY,
    bits: 93000,
    stats: { DEF: 55, SKL: 5 },
    wear: [WEAR_CLASSES.LIGHT_ARMOR, WEAR_CLASSES.HEAVY_ARMOR],
    description: [],
    sources: {
      shop: [],
      treasure: ['Shasarazade'],
      loot: ['Earth Golem'],
    },
  },
  WINDSPUN_ARMOR: {
    name: 'Windspun Armor',
    type: ARMOR_TYPES.BODY,
    bits: 120000,
    stats: { DEF: 63, SPD: 20 },
    wear: [WEAR_CLASSES.HEAVY_ARMOR],
    description: [],
    sources: {
      shop: [],
      treasure: ['Gregminster Palace'],
      loot: ['Ekidonna'],
    },
  },
  WOODEN_SHIELD: {
    name: 'Wooden Shield',
    type: ARMOR_TYPES.SHIELD,
    bits: 300,
    stats: { DEF: 2 },
    wear: [WEAR_CLASSES.SHIELD],
    description: [],
    sources: {
      shop: ['Rockland', 'Kaku'],
      treasure: [],
      loot: ['Kobold (sword)'],
    },
  },
  STEEL_SHIELD: {
    name: 'Steel Shield',
    type: ARMOR_TYPES.SHIELD,
    bits: 7300,
    stats: { DEF: 13 },
    wear: [WEAR_CLASSES.SHIELD],
    description: [],
    sources: {
      shop: ['Kouan'],
      treasure: ['Panna Yakuta'],
      loot: ['Death Machine (sword)'],
    },
  },
  CHAOS_SHIELD: {
    name: 'Chaos Shield',
    type: ARMOR_TYPES.SHIELD,
    bits: 32000,
    stats: { DEF: 27 },
    wear: [WEAR_CLASSES.SHIELD],
    description: [],
    sources: {
      shop: ['Kirov'],
      treasure: ['Shasarazade'],
      loot: ['Devil Shield'],
    },
  },
  EARTH_SHIELD: {
    name: 'Earth Shield',
    type: ARMOR_TYPES.SHIELD,
    bits: 68000,
    stats: { DEF: 45 },
    wear: [WEAR_CLASSES.SHIELD],
    description: [],
    sources: {
      shop: ['Gregminster #2'],
      treasure: [],
      loot: ['Magic Shield'],
    },
  },
  WOODEN_SHOES: {
    name: 'Wooden Shoes',
    type: ARMOR_TYPES.ACCESSORY,
    bits: 100,
    stats: { DEF: 1 },
    wear: [WEAR_CLASSES.MALE, WEAR_CLASSES.FEMALE, WEAR_CLASSES.NOBILITY],
    description: [],
    sources: {
      shop: ['Gregminster #1'],
      treasure: [],
      loot: ['Fur Fur'],
    },
  },
  LEGGINGS: {
    name: 'Leggings',
    type: ARMOR_TYPES.ACCESSORY,
    bits: 200,
    stats: { DEF: 2 },
    wear: [WEAR_CLASSES.MALE, WEAR_CLASSES.FEMALE, WEAR_CLASSES.NOBILITY],
    description: [],
    sources: {
      shop: ['Rockland'],
      treasure: ['Mt. Seifu'],
      loot: [],
    },
  },
  GLOVES: {
    name: 'Gloves',
    type: ARMOR_TYPES.ACCESSORY,
    bits: 300,
    stats: { DEF: 2 },
    wear: [WEAR_CLASSES.MALE, WEAR_CLASSES.FEMALE, WEAR_CLASSES.NOBILITY, WEAR_CLASSES.KOBOLD],
    description: [],
    sources: {
      shop: ['Rockland', 'Kaku'],
      treasure: ['Mt. Tigerwolf', 'Panna Yakuta'],
      loot: [],
    },
  },
  CAPE: {
    name: 'Cape',
    type: ARMOR_TYPES.ACCESSORY,
    bits: 400,
    stats: { DEF: 2 },
    wear: [WEAR_CLASSES.MALE, WEAR_CLASSES.FEMALE, WEAR_CLASSES.NOBILITY, WEAR_CLASSES.KOBOLD],
    description: [],
    sources: {
      shop: ['Lenankamp', 'Kaku'],
      treasure: [],
      loot: [],
    },
  },
  CIRCLET: {
    name: 'Circlet',
    type: ARMOR_TYPES.ACCESSORY,
    bits: 600,
    stats: { DEF: 3 },
    wear: [WEAR_CLASSES.FEMALE, WEAR_CLASSES.NOBILITY],
    description: [],
    sources: {
      shop: ['Lenankamp'],
      treasure: ['Mt. Tigerwolf'],
      loot: [],
    },
  },
  BOOTS: {
    name: 'Boots',
    type: ARMOR_TYPES.ACCESSORY,
    bits: 800,
    stats: { DEF: 3 },
    wear: [WEAR_CLASSES.MALE, WEAR_CLASSES.FEMALE, WEAR_CLASSES.NOBILITY, WEAR_CLASSES.KOBOLD],
    description: [],
    sources: {
      shop: ['Kouan'],
      treasure: ['Mt. Seifu'],
      loot: [],
    },
  },
  GAUNTLET: {
    name: 'Gauntlet',
    type: ARMOR_TYPES.ACCESSORY,
    bits: 1700,
    stats: { DEF: 4 },
    wear: [WEAR_CLASSES.MALE, WEAR_CLASSES.FEMALE, WEAR_CLASSES.NOBILITY],
    description: [],
    sources: {
      shop: ['Kouan'],
      treasure: ['Great Forest'],
      loot: [],
    },
  },
  SHOULDER_PADS: {
    name: 'Shoulder Pads',
    type: ARMOR_TYPES.ACCESSORY,
    bits: 2000,
    stats: { DEF: 4 },
    wear: [WEAR_CLASSES.MALE, WEAR_CLASSES.FEMALE, WEAR_CLASSES.NOBILITY],
    description: [],
    sources: {
      shop: ['Kaku'],
      treasure: ["Lepant's House"],
      loot: ['Bandit (yellow)'],
    },
  },
  BLUE_RIBBON: {
    name: 'Blue Ribbon',
    type: ARMOR_TYPES.ACCESSORY,
    bits: 1150,
    stats: { DEF: 6 },
    wear: [WEAR_CLASSES.FEMALE, WEAR_CLASSES.NOBILITY],
    description: [],
    sources: {
      shop: ['Kouan'],
      treasure: ["Dwarves' Vault"],
      loot: ['Beast Commander'],
    },
  },
  NECKLACE: {
    name: 'Necklace',
    type: ARMOR_TYPES.ACCESSORY,
    bits: 1200,
    stats: { DEF: 7 },
    wear: [WEAR_CLASSES.KOBOLD],
    description: [],
    sources: {
      shop: ['Elves Village'],
      treasure: [],
      loot: ['Kobold (bow)'],
    },
  },
  EMBLEM: {
    name: 'Emblem',
    type: ARMOR_TYPES.ACCESSORY,
    bits: 2700,
    stats: { DEF: 8, MGC: 10 },
    wear: [WEAR_CLASSES.MALE, WEAR_CLASSES.NOBILITY],
    description: [],
    sources: {
      shop: ['Kouan'],
      treasure: [],
      loot: ['Veteran Soldier (bow)'],
    },
  },
  FUR_CAPE: {
    name: 'Fur Cape',
    type: ARMOR_TYPES.ACCESSORY,
    bits: 2800,
    stats: { DEF: 8 },
    wear: [WEAR_CLASSES.MALE, WEAR_CLASSES.FEMALE, WEAR_CLASSES.NOBILITY, WEAR_CLASSES.KOBOLD],
    description: [],
    sources: {
      shop: ['Dwarf Village'],
      treasure: [],
      loot: ['Death Boar'],
    },
  },
  STAR_EARRINGS: {
    name: 'Star Earrings',
    type: ARMOR_TYPES.ACCESSORY,
    bits: 12000,
    stats: { DEF: 8 },
    wear: [WEAR_CLASSES.FEMALE, WEAR_CLASSES.NOBILITY],
    description: ['Auto-heal +5'],
    sources: {
      shop: [],
      treasure: [],
      loot: ['Hell Unicorn'],
    },
  },
  FEATHER: {
    name: 'Feather',
    type: ARMOR_TYPES.ACCESSORY,
    bits: 2000,
    stats: { DEF: 9 },
    wear: [WEAR_CLASSES.MALE, WEAR_CLASSES.FEMALE, WEAR_CLASSES.NOBILITY, WEAR_CLASSES.KOBOLD],
    description: [],
    sources: {
      shop: ['Elves Village'],
      treasure: ["Dwarves' Trail"],
      loot: ['Roc'],
    },
  },
  TOE_SHOES: {
    name: 'Toe Shoes',
    type: ARMOR_TYPES.ACCESSORY,
    bits: 2800,
    stats: { DEF: 9 },
    wear: [WEAR_CLASSES.MALE, WEAR_CLASSES.FEMALE, WEAR_CLASSES.NOBILITY],
    description: [],
    sources: {
      shop: ['Antei'],
      treasure: ['Toran Basement'],
      loot: ['Holly Spirit'],
    },
  },
  SILVER_RING: {
    name: 'Silver Ring',
    type: ARMOR_TYPES.ACCESSORY,
    bits: 5500,
    stats: { DEF: 11 },
    wear: [WEAR_CLASSES.FEMALE, WEAR_CLASSES.NOBILITY],
    description: [],
    sources: {
      shop: ['Kirov'],
      treasure: [],
      loot: ['Strong Arm'],
    },
  },
  SILVERLET: {
    name: 'Silverlet',
    type: ARMOR_TYPES.ACCESSORY,
    bits: 7000,
    stats: { DEF: 11 },
    wear: [WEAR_CLASSES.MALE, WEAR_CLASSES.FEMALE, WEAR_CLASSES.NOBILITY],
    description: [],
    sources: {
      shop: ['Kirov'],
      treasure: ['Qlon Cave'],
      loot: ['Shadow'],
    },
  },
  MANGOSH: {
    name: 'Mangosh',
    type: ARMOR_TYPES.ACCESSORY,
    bits: 21000,
    stats: { DEF: 12, SKL: 20 },
    wear: [WEAR_CLASSES.MALE, WEAR_CLASSES.FEMALE, WEAR_CLASSES.NOBILITY],
    description: ['Counter-rate up'],
    sources: {
      shop: [],
      treasure: [],
      loot: ['Devil Armor'],
    },
  },
  ROSE_BROOCH: {
    name: 'Rose Brooch',
    type: ARMOR_TYPES.ACCESSORY,
    bits: 7000,
    stats: { DEF: 13 },
    wear: [WEAR_CLASSES.NOBILITY],
    description: [],
    sources: {
      shop: ['Antei'],
      treasure: [],
      loot: ['Shadow', 'Shadow Man'],
    },
  },
  CAPE_OF_DARKNESS: {
    name: 'Cape of Darkness',
    type: ARMOR_TYPES.ACCESSORY,
    bits: 8500,
    stats: { DEF: 13 },
    wear: [WEAR_CLASSES.MALE, WEAR_CLASSES.FEMALE, WEAR_CLASSES.NOBILITY, WEAR_CLASSES.KOBOLD],
    description: [],
    sources: {
      shop: ["Warrior's Village", 'Gregminster #2'],
      treasure: ["Neclord's Castle"],
      loot: ['Ninja'],
    },
  },
  SPEED_RING: {
    name: 'Speed Ring',
    type: ARMOR_TYPES.ACCESSORY,
    bits: 13000,
    stats: { DEF: 13, SPD: 15 },
    wear: [WEAR_CLASSES.MALE, WEAR_CLASSES.FEMALE, WEAR_CLASSES.NOBILITY, WEAR_CLASSES.KOBOLD],
    description: [],
    sources: {
      shop: [],
      treasure: [],
      loot: ['Mirage'],
    },
  },
  WING_BOOTS: {
    name: 'Wing Boots',
    type: ARMOR_TYPES.ACCESSORY,
    bits: 10200,
    stats: { DEF: 14, SPD: 10 },
    wear: [WEAR_CLASSES.FEMALE],
    description: [],
    sources: {
      shop: ['Gregminster #1'],
      treasure: [],
      loot: ['Ninja'],
    },
  },
  POWER_RING: {
    name: 'Power Ring',
    type: ARMOR_TYPES.ACCESSORY,
    bits: 14000,
    stats: { DEF: 14, PWR: 20 },
    wear: [WEAR_CLASSES.MALE, WEAR_CLASSES.FEMALE, WEAR_CLASSES.NOBILITY, WEAR_CLASSES.KOBOLD],
    description: [],
    sources: {
      shop: [],
      treasure: ['Gregminster Palace'],
      loot: ['Colossus'],
    },
  },
  GUARD_RING: {
    name: 'Guard Ring',
    type: ARMOR_TYPES.ACCESSORY,
    bits: 8500,
    stats: { DEF: 15 },
    wear: [WEAR_CLASSES.MALE, WEAR_CLASSES.FEMALE, WEAR_CLASSES.NOBILITY, WEAR_CLASSES.KOBOLD],
    description: [],
    sources: {
      shop: ['Antei', 'Gregminster #2'],
      treasure: ['Shasarazade'],
      loot: ['Grave Master'],
    },
  },
  POWER_GLOVES: {
    name: 'Power Gloves',
    type: ARMOR_TYPES.ACCESSORY,
    bits: 20000,
    stats: { DEF: 16, PWR: 15 },
    wear: [WEAR_CLASSES.MALE, WEAR_CLASSES.FEMALE, WEAR_CLASSES.NOBILITY],
    description: [],
    sources: {
      shop: [],
      treasure: ["Dragon's Den"],
      loot: ['Wyvern'],
    },
  },
  SILVER_NECKLACE: {
    name: 'Silver Necklace',
    type: ARMOR_TYPES.ACCESSORY,
    bits: 6000,
    stats: { DEF: 17 },
    wear: [WEAR_CLASSES.KOBOLD],
    description: [],
    sources: {
      shop: ['Kirov'],
      treasure: ['Soniere'],
      loot: ['Demon Hound'],
    },
  },
  GOLDLET: {
    name: 'Goldlet',
    type: ARMOR_TYPES.ACCESSORY,
    bits: 19000,
    stats: { DEF: 18 },
    wear: [WEAR_CLASSES.MALE, WEAR_CLASSES.FEMALE, WEAR_CLASSES.NOBILITY],
    description: [],
    sources: {
      shop: [],
      treasure: ["Dragon's Den"],
      loot: ['Gigantes'],
    },
  },
  EARTH_BOOTS: {
    name: 'Earth Boots',
    type: ARMOR_TYPES.ACCESSORY,
    bits: 22000,
    stats: { DEF: 18 },
    wear: [WEAR_CLASSES.MALE, WEAR_CLASSES.KOBOLD],
    description: [],
    sources: {
      shop: [],
      treasure: ["Neclord's Castle"],
      loot: ['Phantom'],
    },
  },
  CRIMSON_CAPE: {
    name: 'Crimson Cape',
    type: ARMOR_TYPES.ACCESSORY,
    bits: 32000,
    stats: { DEF: 21 },
    wear: [WEAR_CLASSES.MALE, WEAR_CLASSES.FEMALE, WEAR_CLASSES.NOBILITY, WEAR_CLASSES.KOBOLD],
    description: [],
    sources: {
      shop: [],
      treasure: ['Qlon Cave'],
      loot: ['Ninja Master'],
    },
  },
  GOLD_NECKLACE: {
    name: 'Gold Necklace',
    type: ARMOR_TYPES.ACCESSORY,
    bits: 17000,
    stats: { DEF: 25 },
    wear: [WEAR_CLASSES.KOBOLD],
    description: [],
    sources: {
      shop: [],
      treasure: ['Seek Valley'],
      loot: ['Kerberos'],
    },
  },
};
