import { RUNES } from './Magic/Runes.js';
import { ARMOR, WEAR_CLASSES } from './Armor.js';
import { ITEMS } from './Items.js';
import { RANGE } from './Constants.js';
import { CHARACTER_KEYS } from './Keys.js';

/** @typedef {import('./Magic/Runes.js').Rune} Rune */
/** @typedef {import('./Armor.js').WearClass} WearClass */
/** @typedef {import('./Battle/Character.js').InventoryEntry} InventoryEntry */
/** @typedef {import('./Battle/Combatant.js').CombatantStatBlock} CombatantStatBlock */
/** @typedef {import('./Battle/Character.js').CharacterGrowths} CharacterGrowths */
/** @typedef {import('./Constants.js').Range} Range */
/** @typedef {import('./Keys.js').CharacterKey} CharacterKey */

/**
 * @typedef {Object} CharacterWeaponRef
 * @property {number} id - Index into the WEAPONS table.
 * @property {number} lvl
 */

/**
 * @typedef {Object} CharacterData
 * @property {string} name
 * @property {number} id - The game's roster ID.
 * @property {Range} range
 * @property {Rune} rune
 * @property {boolean} isRuneLocked
 * @property {boolean} counterEligible
 * @property {CharacterWeaponRef} weapon
 * @property {WearClass[]} wearClasses
 * @property {InventoryEntry[]} inventory - Armor is equipped from here (see the `armor`/
 *   `isArmorLocked` getters in Battle/Character.js), same as items; there's no separate
 *   armor slot storage.
 * @property {{initial: CombatantStatBlock, growths: CharacterGrowths}} stats
 */

/** @satisfies {Record<CharacterKey, CharacterData>} */
const CHARACTERS = {
  [CHARACTER_KEYS.MCDOHL]: {
    name: 'McDohl',
    id: 8,
    range: RANGE.MEDIUM,
    rune: RUNES.NONE,
    isRuneLocked: false,
    counterEligible: true,
    weapon: {
      id: 1,
      lvl: 1,
    },
    wearClasses: [WEAR_CLASSES.CAP, WEAR_CLASSES.LIGHT_ARMOR, WEAR_CLASSES.MALE],
    inventory: [
      { item: ARMOR.BANDANNA, equipped: true, slot: 'HEAD' },
      { item: ARMOR.TUNIC, equipped: true, slot: 'BODY' },
      { item: ARMOR.GLOVES, equipped: true, slot: 'ACCESSORY_1' },
      { item: ARMOR.BOOTS, equipped: true, slot: 'ACCESSORY_2' },
      { item: ITEMS.MEDICINE },
    ],
    stats: {
      initial: {
        HP: 17,
        PWR: 13,
        SKL: 22,
        DEF: 18,
        SPD: 15,
        MGC: 12,
        LUK: 16,
      },
      growths: {
        PWR: 6,
        SKL: 7,
        DEF: 5,
        SPD: 7,
        MGC: 6,
        LUK: 6,
      },
    },
  },
  [CHARACTER_KEYS.ALEN]: {
    name: 'Alen',
    id: 48,
    range: RANGE.SHORT,
    rune: RUNES.RAGE,
    isRuneLocked: true,
    counterEligible: true,
    weapon: {
      id: 42,
      lvl: 7,
    },
    wearClasses: [
      WEAR_CLASSES.HELMET,
      WEAR_CLASSES.LIGHT_ARMOR,
      WEAR_CLASSES.SHIELD,
      WEAR_CLASSES.MALE,
    ],
    inventory: [
      { item: ARMOR.LEATHER_ARMOR, equipped: true, slot: 'BODY' },
      { item: ARMOR.STEEL_SHIELD, equipped: true, slot: 'SHIELD' },
    ],
    stats: {
      initial: {
        HP: 25,
        PWR: 17,
        SKL: 15,
        DEF: 16,
        SPD: 11,
        MGC: 15,
        LUK: 13,
      },
      growths: {
        PWR: 6,
        SKL: 3,
        DEF: 5,
        SPD: 4,
        MGC: 5,
        LUK: 4,
      },
    },
  },
  [CHARACTER_KEYS.ANJI]: {
    name: 'Anji',
    id: 11,
    range: RANGE.MEDIUM,
    rune: RUNES.NONE,
    isRuneLocked: false,
    counterEligible: true,
    weapon: {
      id: 46,
      lvl: 7,
    },
    wearClasses: [WEAR_CLASSES.CAP, WEAR_CLASSES.VEST, WEAR_CLASSES.MALE],
    inventory: [
      { item: ARMOR.BANDANNA, equipped: true, slot: 'HEAD' },
      { item: ARMOR.LEATHER_COAT, equipped: true, slot: 'BODY' },
    ],
    stats: {
      initial: {
        HP: 24,
        PWR: 18,
        SKL: 17,
        DEF: 9,
        SPD: 15,
        MGC: 7,
        LUK: 9,
      },
      growths: {
        PWR: 6,
        SKL: 5,
        DEF: 3,
        SPD: 5,
        MGC: 2,
        LUK: 2,
      },
    },
  },
  [CHARACTER_KEYS.ANTONIO]: {
    name: 'Antonio',
    id: 101,
    range: RANGE.MEDIUM,
    rune: RUNES.NONE,
    isRuneLocked: false,
    counterEligible: true,
    weapon: {
      id: 68,
      lvl: 2,
    },
    wearClasses: [WEAR_CLASSES.CAP, WEAR_CLASSES.VEST, WEAR_CLASSES.SHIELD, WEAR_CLASSES.MALE],
    inventory: [
      { item: ARMOR.TUNIC, equipped: true, slot: 'BODY' },
      { item: ARMOR.GLOVES, equipped: true, slot: 'ACCESSORY_1' },
    ],
    stats: {
      initial: {
        HP: 18,
        PWR: 16,
        SKL: 17,
        DEF: 12,
        SPD: 13,
        MGC: 5,
        LUK: 9,
      },
      growths: {
        PWR: 3,
        SKL: 3,
        DEF: 3,
        SPD: 4,
        MGC: 1,
        LUK: 3,
      },
    },
  },
  [CHARACTER_KEYS.BLACKMAN]: {
    name: 'Blackman',
    id: 73,
    range: RANGE.MEDIUM,
    rune: RUNES.NONE,
    isRuneLocked: false,
    counterEligible: true,
    weapon: {
      id: 58,
      lvl: 3,
    },
    wearClasses: [WEAR_CLASSES.CAP, WEAR_CLASSES.HEAVY_ARMOR, WEAR_CLASSES.MALE],
    inventory: [
      { item: ARMOR.LEATHER_COAT, equipped: true, slot: 'BODY' },
    ],
    stats: {
      initial: {
        HP: 28,
        PWR: 16,
        SKL: 9,
        DEF: 18,
        SPD: 8,
        MGC: 5,
        LUK: 7,
      },
      growths: {
        PWR: 5,
        SKL: 3,
        DEF: 6,
        SPD: 3,
        MGC: 1,
        LUK: 3,
      },
    },
  },
  [CHARACTER_KEYS.CAMILLE]: {
    name: 'Camille',
    id: 3,
    range: RANGE.MEDIUM,
    rune: RUNES.NONE,
    isRuneLocked: false,
    counterEligible: true,
    weapon: {
      id: 6,
      lvl: 4,
    },
    wearClasses: [WEAR_CLASSES.CAP, WEAR_CLASSES.LIGHT_ARMOR, WEAR_CLASSES.FEMALE],
    inventory: [
      { item: ARMOR.BANDANNA, equipped: true, slot: 'HEAD' },
      { item: ARMOR.TUNIC, equipped: true, slot: 'BODY' },
      { item: ITEMS.MEDICINE },
    ],
    stats: {
      initial: {
        HP: 20,
        PWR: 13,
        SKL: 19,
        DEF: 12,
        SPD: 18,
        MGC: 13,
        LUK: 12,
      },
      growths: {
        PWR: 5,
        SKL: 8,
        DEF: 4,
        SPD: 5,
        MGC: 5,
        LUK: 3,
      },
    },
  },
  [CHARACTER_KEYS.CLEO]: {
    name: 'Cleo',
    id: 1,
    range: RANGE.LONG,
    rune: RUNES.NONE,
    isRuneLocked: false,
    counterEligible: false,
    weapon: {
      id: 4,
      lvl: 1,
    },
    wearClasses: [WEAR_CLASSES.HELMET, WEAR_CLASSES.LIGHT_ARMOR, WEAR_CLASSES.FEMALE],
    inventory: [
      { item: ARMOR.TUNIC, equipped: true, slot: 'BODY' },
      { item: ARMOR.CIRCLET, equipped: true, slot: 'ACCESSORY_1' },
      { item: ITEMS.MEDICINE },
    ],
    stats: {
      initial: {
        HP: 20,
        PWR: 12,
        SKL: 20,
        DEF: 15,
        SPD: 12,
        MGC: 21,
        LUK: 20,
      },
      growths: {
        PWR: 5,
        SKL: 6,
        DEF: 5,
        SPD: 6,
        MGC: 6,
        LUK: 2,
      },
    },
  },
  [CHARACTER_KEYS.CLIVE]: {
    name: 'Clive',
    id: 53,
    range: RANGE.LONG,
    rune: RUNES.NONE,
    isRuneLocked: false,
    counterEligible: true,
    weapon: {
      id: 74,
      lvl: 13,
    },
    wearClasses: [WEAR_CLASSES.CAP, WEAR_CLASSES.LIGHT_ARMOR, WEAR_CLASSES.MALE],
    inventory: [
      { item: ARMOR.MAGIC_ROBE, equipped: true, slot: 'BODY' },
      { item: ARMOR.CAPE, equipped: true, slot: 'ACCESSORY_1' },
    ],
    stats: {
      initial: {
        HP: 24,
        PWR: 16,
        SKL: 22,
        DEF: 9,
        SPD: 17,
        MGC: 5,
        LUK: 6,
      },
      growths: {
        PWR: 6,
        SKL: 8,
        DEF: 3,
        SPD: 6,
        MGC: 2,
        LUK: 1,
      },
    },
  },
  [CHARACTER_KEYS.CROWLEY]: {
    name: 'Crowley',
    id: 64,
    range: RANGE.SHORT,
    rune: RUNES.CYCLONE,
    isRuneLocked: false,
    counterEligible: true,
    weapon: {
      id: 76,
      lvl: 2,
    },
    wearClasses: [WEAR_CLASSES.CAP, WEAR_CLASSES.ROBE, WEAR_CLASSES.MALE],
    inventory: [
      { item: ARMOR.MASTER_ROBE, equipped: true, slot: 'BODY', locked: true },
      { item: ARMOR.EMBLEM, equipped: true, slot: 'ACCESSORY_1', locked: true },
    ],
    stats: {
      initial: {
        HP: 16,
        PWR: 7,
        SKL: 6,
        DEF: 5,
        SPD: 9,
        MGC: 27,
        LUK: 13,
      },
      growths: {
        PWR: 2,
        SKL: 3,
        DEF: 1,
        SPD: 5,
        MGC: 8,
        LUK: 3,
      },
    },
  },
  [CHARACTER_KEYS.EIKEI]: {
    name: 'Eikei',
    id: 66,
    range: RANGE.SHORT,
    rune: RUNES.DOUBLE_BEAT,
    isRuneLocked: false,
    counterEligible: true,
    weapon: {
      id: 64,
      lvl: 6,
    },
    wearClasses: [WEAR_CLASSES.CAP, WEAR_CLASSES.VEST, WEAR_CLASSES.MALE],
    inventory: [
      { item: ARMOR.KARATE_UNIFORM, equipped: true, slot: 'BODY' },
    ],
    stats: {
      initial: {
        HP: 26,
        PWR: 16,
        SKL: 19,
        DEF: 17,
        SPD: 13,
        MGC: 2,
        LUK: 7,
      },
      growths: {
        PWR: 5,
        SKL: 4,
        DEF: 5,
        SPD: 2,
        MGC: 0,
        LUK: 3,
      },
    },
  },
  [CHARACTER_KEYS.EILEEN]: {
    name: 'Eileen',
    id: 0,
    range: RANGE.LONG,
    rune: RUNES.EARTH,
    isRuneLocked: false,
    counterEligible: false,
    weapon: {
      id: 17,
      lvl: 4,
    },
    wearClasses: [WEAR_CLASSES.CAP, WEAR_CLASSES.ROBE, WEAR_CLASSES.FEMALE],
    inventory: [
      { item: ARMOR.ROBE, equipped: true, slot: 'BODY' },
      { item: ARMOR.STAR_EARRINGS, equipped: true, slot: 'ACCESSORY_1', locked: true },
    ],
    stats: {
      initial: {
        HP: 15,
        PWR: 9,
        SKL: 12,
        DEF: 11,
        SPD: 15,
        MGC: 17,
        LUK: 15,
      },
      growths: {
        PWR: 2,
        SKL: 4,
        DEF: 2,
        SPD: 6,
        MGC: 7,
        LUK: 5,
      },
    },
  },
  [CHARACTER_KEYS.FLIK]: {
    name: 'Flik',
    id: 17,
    range: RANGE.SHORT,
    rune: RUNES.LIGHTNING,
    isRuneLocked: false,
    counterEligible: true,
    weapon: {
      id: 11,
      lvl: 9,
    },
    wearClasses: [
      WEAR_CLASSES.CAP,
      WEAR_CLASSES.LIGHT_ARMOR,
      WEAR_CLASSES.SHIELD,
      WEAR_CLASSES.MALE,
    ],
    inventory: [
      { item: ARMOR.BANDANNA, equipped: true, slot: 'HEAD' },
      { item: ARMOR.BRASS_ARMOR, equipped: true, slot: 'BODY' },
      { item: ARMOR.WOODEN_SHIELD, equipped: true, slot: 'SHIELD' },
      { item: ARMOR.CAPE, equipped: true, slot: 'ACCESSORY_1' },
    ],
    stats: {
      initial: {
        HP: 24,
        PWR: 17,
        SKL: 16,
        DEF: 13,
        SPD: 16,
        MGC: 15,
        LUK: 14,
      },
      growths: {
        PWR: 6,
        SKL: 6,
        DEF: 4,
        SPD: 6,
        MGC: 5,
        LUK: 4,
      },
    },
  },
  [CHARACTER_KEYS.FU_SU_LU]: {
    name: 'Fu Su Lu',
    id: 65,
    range: RANGE.SHORT,
    rune: RUNES.NONE,
    isRuneLocked: false,
    counterEligible: true,
    weapon: {
      id: 49,
      lvl: 6,
    },
    wearClasses: [WEAR_CLASSES.HELMET, WEAR_CLASSES.VEST, WEAR_CLASSES.MALE],
    inventory: [
      { item: ARMOR.LEATHER_COAT, equipped: true, slot: 'BODY' },
      { item: ARMOR.FUR_CAPE, equipped: true, slot: 'ACCESSORY_1' },
    ],
    stats: {
      initial: {
        HP: 35,
        PWR: 30,
        SKL: 5,
        DEF: 22,
        SPD: 3,
        MGC: 1,
        LUK: 2,
      },
      growths: {
        PWR: 8,
        SKL: 1,
        DEF: 6,
        SPD: 1,
        MGC: 0,
        LUK: 1,
      },
    },
  },
  [CHARACTER_KEYS.FUKIEN]: {
    name: 'Fukien',
    id: 18,
    range: RANGE.SHORT,
    rune: RUNES.RESURRECTION,
    isRuneLocked: true,
    counterEligible: true,
    weapon: {
      id: 27,
      lvl: 9,
    },
    wearClasses: [WEAR_CLASSES.CAP, WEAR_CLASSES.VEST, WEAR_CLASSES.MALE],
    inventory: [
      { item: ARMOR.LEATHER_COAT, equipped: true, slot: 'BODY' },
    ],
    stats: {
      initial: {
        HP: 16,
        PWR: 8,
        SKL: 12,
        DEF: 9,
        SPD: 12,
        MGC: 10,
        LUK: 20,
      },
      growths: {
        PWR: 2,
        SKL: 3,
        DEF: 4,
        SPD: 4,
        MGC: 6,
        LUK: 5,
      },
    },
  },
  [CHARACTER_KEYS.FUMA]: {
    name: 'Fuma',
    id: 55,
    range: RANGE.LONG,
    rune: RUNES.NONE,
    isRuneLocked: false,
    counterEligible: false,
    weapon: {
      id: 53,
      lvl: 11,
    },
    wearClasses: [WEAR_CLASSES.CAP, WEAR_CLASSES.VEST, WEAR_CLASSES.MALE],
    inventory: [
      { item: ARMOR.NINJA_SUIT, equipped: true, slot: 'BODY' },
    ],
    stats: {
      initial: {
        HP: 17,
        PWR: 14,
        SKL: 16,
        DEF: 11,
        SPD: 17,
        MGC: 5,
        LUK: 13,
      },
      growths: {
        PWR: 5,
        SKL: 5,
        DEF: 5,
        SPD: 6,
        MGC: 1,
        LUK: 3,
      },
    },
  },
  [CHARACTER_KEYS.FUTCH]: {
    name: 'Futch',
    id: 19,
    range: RANGE.MEDIUM,
    rune: RUNES.NONE,
    isRuneLocked: false,
    counterEligible: true,
    weapon: {
      id: 28,
      lvl: 9,
    },
    wearClasses: [
      WEAR_CLASSES.HELMET,
      WEAR_CLASSES.LIGHT_ARMOR,
      WEAR_CLASSES.SHIELD,
      WEAR_CLASSES.MALE,
    ],
    inventory: [
      { item: ARMOR.HALF_HELMET, equipped: true, slot: 'HEAD' },
      { item: ARMOR.LEATHER_ARMOR, equipped: true, slot: 'BODY' },
    ],
    stats: {
      initial: {
        HP: 16,
        PWR: 14,
        SKL: 13,
        DEF: 12,
        SPD: 17,
        MGC: 10,
        LUK: 15,
      },
      growths: {
        PWR: 5,
        SKL: 4,
        DEF: 5,
        SPD: 6,
        MGC: 2,
        LUK: 6,
      },
    },
  },
  [CHARACTER_KEYS.GEN]: {
    name: 'Gen',
    id: 20,
    range: RANGE.SHORT,
    rune: RUNES.NONE,
    isRuneLocked: false,
    counterEligible: true,
    weapon: {
      id: 22,
      lvl: 9,
    },
    wearClasses: [WEAR_CLASSES.CAP, WEAR_CLASSES.LIGHT_ARMOR, WEAR_CLASSES.MALE],
    inventory: [
      { item: ARMOR.HEADBAND, equipped: true, slot: 'HEAD' },
      { item: ARMOR.KARATE_UNIFORM, equipped: true, slot: 'BODY' },
    ],
    stats: {
      initial: {
        HP: 27,
        PWR: 19,
        SKL: 13,
        DEF: 17,
        SPD: 15,
        MGC: 2,
        LUK: 18,
      },
      growths: {
        PWR: 6,
        SKL: 5,
        DEF: 4,
        SPD: 4,
        MGC: 2,
        LUK: 4,
      },
    },
  },
  [CHARACTER_KEYS.GON]: {
    name: 'Gon',
    id: 80,
    range: RANGE.SHORT,
    rune: RUNES.NONE,
    isRuneLocked: false,
    counterEligible: true,
    weapon: {
      id: 50,
      lvl: 7,
    },
    wearClasses: [
      WEAR_CLASSES.HELMET,
      WEAR_CLASSES.LIGHT_ARMOR,
      WEAR_CLASSES.SHIELD,
      WEAR_CLASSES.KOBOLD,
    ],
    inventory: [
      { item: ARMOR.HEADBAND, equipped: true, slot: 'HEAD' },
      { item: ARMOR.LEATHER_COAT, equipped: true, slot: 'BODY' },
    ],
    stats: {
      initial: {
        HP: 17,
        PWR: 13,
        SKL: 14,
        DEF: 16,
        SPD: 11,
        MGC: 12,
        LUK: 27,
      },
      growths: {
        PWR: 4,
        SKL: 4,
        DEF: 5,
        SPD: 3,
        MGC: 2,
        LUK: 8,
      },
    },
  },
  [CHARACTER_KEYS.GREMIO]: {
    name: 'Gremio',
    id: 2,
    range: RANGE.MEDIUM,
    rune: RUNES.NONE,
    isRuneLocked: false,
    counterEligible: true,
    weapon: {
      id: 2,
      lvl: 1,
    },
    wearClasses: [WEAR_CLASSES.CAP, WEAR_CLASSES.LIGHT_ARMOR, WEAR_CLASSES.MALE],
    inventory: [
      { item: ARMOR.LEATHER_COAT, equipped: true, slot: 'BODY' },
      { item: ARMOR.CAPE, equipped: true, slot: 'ACCESSORY_1' },
      { item: ITEMS.MEDICINE },
    ],
    stats: {
      initial: {
        HP: 22,
        PWR: 17,
        SKL: 12,
        DEF: 16,
        SPD: 10,
        MGC: 7,
        LUK: 10,
      },
      growths: {
        PWR: 13,
        SKL: 5,
        DEF: 6,
        SPD: 3,
        MGC: 2,
        LUK: 5,
      },
    },
  },
  [CHARACTER_KEYS.GRENSEAL]: {
    name: 'Grenseal',
    id: 49,
    range: RANGE.SHORT,
    rune: RUNES.THUNDER,
    isRuneLocked: true,
    counterEligible: true,
    weapon: {
      id: 43,
      lvl: 7,
    },
    wearClasses: [
      WEAR_CLASSES.HELMET,
      WEAR_CLASSES.LIGHT_ARMOR,
      WEAR_CLASSES.SHIELD,
      WEAR_CLASSES.MALE,
    ],
    inventory: [
      { item: ARMOR.LEATHER_ARMOR, equipped: true, slot: 'BODY' },
      { item: ARMOR.STEEL_SHIELD, equipped: true, slot: 'SHIELD' },
    ],
    stats: {
      initial: {
        HP: 21,
        PWR: 14,
        SKL: 12,
        DEF: 16,
        SPD: 12,
        MGC: 15,
        LUK: 9,
      },
      growths: {
        PWR: 5,
        SKL: 4,
        DEF: 5,
        SPD: 5,
        MGC: 6,
        LUK: 3,
      },
    },
  },
  [CHARACTER_KEYS.GRIFFITH]: {
    name: 'Griffith',
    id: 42,
    range: RANGE.SHORT,
    rune: RUNES.NONE,
    isRuneLocked: false,
    counterEligible: true,
    weapon: {
      id: 35,
      lvl: 8,
    },
    wearClasses: [
      WEAR_CLASSES.HELMET,
      WEAR_CLASSES.LIGHT_ARMOR,
      WEAR_CLASSES.SHIELD,
      WEAR_CLASSES.MALE,
    ],
    inventory: [
      { item: ARMOR.LEATHER_ARMOR, equipped: true, slot: 'BODY' },
    ],
    stats: {
      initial: {
        HP: 21,
        PWR: 15,
        SKL: 12,
        DEF: 16,
        SPD: 12,
        MGC: 11,
        LUK: 13,
      },
      growths: {
        PWR: 5,
        SKL: 3,
        DEF: 4,
        SPD: 3,
        MGC: 2,
        LUK: 3,
      },
    },
  },
  [CHARACTER_KEYS.HELLION]: {
    name: 'Hellion',
    id: 59,
    range: RANGE.SHORT,
    rune: RUNES.MOTHER_EARTH,
    isRuneLocked: true,
    counterEligible: true,
    weapon: {
      id: 67,
      lvl: 3,
    },
    wearClasses: [WEAR_CLASSES.CAP, WEAR_CLASSES.ROBE, WEAR_CLASSES.FEMALE],
    inventory: [
      { item: ARMOR.GUARD_ROBE, equipped: true, slot: 'BODY' },
    ],
    stats: {
      initial: {
        HP: 20,
        PWR: 2,
        SKL: 2,
        DEF: 5,
        SPD: 4,
        MGC: 23,
        LUK: 13,
      },
      growths: {
        PWR: 1,
        SKL: 1,
        DEF: 3,
        SPD: 3,
        MGC: 7,
        LUK: 4,
      },
    },
  },
  [CHARACTER_KEYS.HIX]: {
    name: 'Hix',
    id: 63,
    range: RANGE.SHORT,
    rune: RUNES.NONE,
    isRuneLocked: false,
    counterEligible: true,
    weapon: {
      id: 31,
      lvl: 10,
    },
    wearClasses: [
      WEAR_CLASSES.HELMET,
      WEAR_CLASSES.LIGHT_ARMOR,
      WEAR_CLASSES.SHIELD,
      WEAR_CLASSES.MALE,
    ],
    inventory: [
      { item: ARMOR.HALF_HELMET, equipped: true, slot: 'HEAD' },
      { item: ARMOR.LEATHER_ARMOR, equipped: true, slot: 'BODY' },
      { item: ARMOR.WOODEN_SHIELD, equipped: true, slot: 'SHIELD' },
      { item: ARMOR.BOOTS, equipped: true, slot: 'ACCESSORY_1' },
    ],
    stats: {
      initial: {
        HP: 24,
        PWR: 17,
        SKL: 15,
        DEF: 13,
        SPD: 16,
        MGC: 9,
        LUK: 21,
      },
      growths: {
        PWR: 5,
        SKL: 5,
        DEF: 4,
        SPD: 5,
        MGC: 3,
        LUK: 7,
      },
    },
  },
  [CHARACTER_KEYS.HUMPHREY]: {
    name: 'Humphrey',
    id: 21,
    range: RANGE.SHORT,
    rune: RUNES.NONE,
    isRuneLocked: false,
    counterEligible: true,
    weapon: {
      id: 10,
      lvl: 7,
    },
    wearClasses: [WEAR_CLASSES.HELMET, WEAR_CLASSES.HEAVY_ARMOR, WEAR_CLASSES.MALE],
    inventory: [
      { item: ARMOR.BRASS_ARMOR, equipped: true, slot: 'BODY' },
      { item: ARMOR.CAPE, equipped: true, slot: 'ACCESSORY_1' },
    ],
    stats: {
      initial: {
        HP: 35,
        PWR: 22,
        SKL: 15,
        DEF: 19,
        SPD: 7,
        MGC: 2,
        LUK: 9,
      },
      growths: {
        PWR: 6,
        SKL: 3,
        DEF: 7,
        SPD: 2,
        MGC: 1,
        LUK: 3,
      },
    },
  },
  [CHARACTER_KEYS.JUPPO]: {
    name: 'Juppo',
    id: 39,
    range: RANGE.LONG,
    rune: RUNES.TRICK,
    isRuneLocked: true,
    counterEligible: false,
    weapon: {
      id: 19,
      lvl: 4,
    },
    wearClasses: [WEAR_CLASSES.CAP, WEAR_CLASSES.VEST, WEAR_CLASSES.MALE],
    inventory: [
      { item: ARMOR.POINTED_HAT, equipped: true, slot: 'HEAD' },
      { item: ARMOR.TUNIC, equipped: true, slot: 'BODY' },
    ],
    stats: {
      initial: {
        HP: 20,
        PWR: 9,
        SKL: 21,
        DEF: 15,
        SPD: 13,
        MGC: 17,
        LUK: 8,
      },
      growths: {
        PWR: 3,
        SKL: 7,
        DEF: 4,
        SPD: 4,
        MGC: 4,
        LUK: 6,
      },
    },
  },
  [CHARACTER_KEYS.KAGE]: {
    name: 'Kage',
    id: 22,
    range: RANGE.LONG,
    rune: RUNES.NONE,
    isRuneLocked: false,
    counterEligible: false,
    weapon: {
      id: 44,
      lvl: 9,
    },
    wearClasses: [WEAR_CLASSES.CAP, WEAR_CLASSES.VEST, WEAR_CLASSES.MALE],
    inventory: [
      { item: ARMOR.KARATE_UNIFORM, equipped: true, slot: 'BODY' },
    ],
    stats: {
      initial: {
        HP: 20,
        PWR: 13,
        SKL: 17,
        DEF: 11,
        SPD: 21,
        MGC: 9,
        LUK: 8,
      },
      growths: {
        PWR: 4,
        SKL: 6,
        DEF: 5,
        SPD: 7,
        MGC: 3,
        LUK: 3,
      },
    },
  },
  [CHARACTER_KEYS.KAI]: {
    name: 'Kai',
    id: 91,
    range: RANGE.MEDIUM,
    rune: RUNES.HAZY,
    isRuneLocked: true,
    counterEligible: true,
    weapon: {
      id: 63,
      lvl: 8,
    },
    wearClasses: [WEAR_CLASSES.CAP, WEAR_CLASSES.VEST, WEAR_CLASSES.MALE],
    inventory: [
      { item: ARMOR.HEADBAND, equipped: true, slot: 'HEAD' },
      { item: ARMOR.KARATE_UNIFORM, equipped: true, slot: 'BODY' },
    ],
    stats: {
      initial: {
        HP: 24,
        PWR: 19,
        SKL: 15,
        DEF: 16,
        SPD: 15,
        MGC: 3,
        LUK: 13,
      },
      growths: {
        PWR: 6,
        SKL: 3,
        DEF: 4,
        SPD: 2,
        MGC: 1,
        LUK: 3,
      },
    },
  },
  [CHARACTER_KEYS.KAMANDOL]: {
    name: 'Kamandol',
    id: 67,
    range: RANGE.SHORT,
    rune: RUNES.NONE,
    isRuneLocked: false,
    counterEligible: true,
    weapon: {
      id: 23,
      lvl: 3,
    },
    wearClasses: [WEAR_CLASSES.HELMET, WEAR_CLASSES.VEST, WEAR_CLASSES.MALE],
    inventory: [
      { item: ARMOR.GUARD_ROBE, equipped: true, slot: 'BODY' },
    ],
    stats: {
      initial: {
        HP: 24,
        PWR: 11,
        SKL: 21,
        DEF: 9,
        SPD: 11,
        MGC: 8,
        LUK: 9,
      },
      growths: {
        PWR: 4,
        SKL: 7,
        DEF: 2,
        SPD: 3,
        MGC: 3,
        LUK: 2,
      },
    },
  },
  [CHARACTER_KEYS.KANAK]: {
    name: 'Kanak',
    id: 43,
    range: RANGE.MEDIUM,
    rune: RUNES.NONE,
    isRuneLocked: false,
    counterEligible: true,
    weapon: {
      id: 48,
      lvl: 4,
    },
    wearClasses: [WEAR_CLASSES.CAP, WEAR_CLASSES.LIGHT_ARMOR, WEAR_CLASSES.MALE],
    inventory: [
      { item: ARMOR.LEATHER_COAT, equipped: true, slot: 'BODY' },
    ],
    stats: {
      initial: {
        HP: 25,
        PWR: 14,
        SKL: 15,
        DEF: 13,
        SPD: 17,
        MGC: 1,
        LUK: 3,
      },
      growths: {
        PWR: 5,
        SKL: 5,
        DEF: 4,
        SPD: 6,
        MGC: 0,
        LUK: 2,
      },
    },
  },
  [CHARACTER_KEYS.KASIM]: {
    name: 'Kasim',
    id: 16,
    range: RANGE.SHORT,
    rune: RUNES.NONE,
    isRuneLocked: false,
    counterEligible: true,
    weapon: {
      id: 36,
      lvl: 13,
    },
    wearClasses: [WEAR_CLASSES.HELMET, WEAR_CLASSES.LIGHT_ARMOR, WEAR_CLASSES.MALE],
    inventory: [
      { item: ARMOR.NINJA_SUIT, equipped: true, slot: 'BODY' },
      { item: ARMOR.GAUNTLET, equipped: true, slot: 'ACCESSORY_1' },
    ],
    stats: {
      initial: {
        HP: 24,
        PWR: 23,
        SKL: 13,
        DEF: 17,
        SPD: 9,
        MGC: 5,
        LUK: 11,
      },
      growths: {
        PWR: 7,
        SKL: 4,
        DEF: 6,
        SPD: 3,
        MGC: 1,
        LUK: 2,
      },
    },
  },
  [CHARACTER_KEYS.KASUMI]: {
    name: 'Kasumi',
    id: 23,
    range: RANGE.LONG,
    rune: RUNES.SHRIKE,
    isRuneLocked: true,
    counterEligible: true,
    weapon: {
      id: 25,
      lvl: 6,
    },
    wearClasses: [WEAR_CLASSES.CAP, WEAR_CLASSES.VEST, WEAR_CLASSES.FEMALE],
    inventory: [
      { item: ARMOR.HEADBAND, equipped: true, slot: 'HEAD' },
      { item: ARMOR.KARATE_UNIFORM, equipped: true, slot: 'BODY' },
    ],
    stats: {
      initial: {
        HP: 24,
        PWR: 16,
        SKL: 19,
        DEF: 13,
        SPD: 24,
        MGC: 13,
        LUK: 15,
      },
      growths: {
        PWR: 5,
        SKL: 6,
        DEF: 4,
        SPD: 8,
        MGC: 4,
        LUK: 3,
      },
    },
  },
  [CHARACTER_KEYS.KESSLER]: {
    name: 'Kessler',
    id: 40,
    range: RANGE.MEDIUM,
    rune: RUNES.NONE,
    isRuneLocked: false,
    counterEligible: true,
    weapon: {
      id: 12,
      lvl: 9,
    },
    wearClasses: [WEAR_CLASSES.CAP, WEAR_CLASSES.HEAVY_ARMOR, WEAR_CLASSES.MALE],
    inventory: [
      { item: ARMOR.LEATHER_COAT, equipped: true, slot: 'BODY' },
    ],
    stats: {
      initial: {
        HP: 26,
        PWR: 15,
        SKL: 16,
        DEF: 13,
        SPD: 12,
        MGC: 10,
        LUK: 11,
      },
      growths: {
        PWR: 5,
        SKL: 5,
        DEF: 4,
        SPD: 3,
        MGC: 2,
        LUK: 3,
      },
    },
  },
  [CHARACTER_KEYS.KIMBERLY]: {
    name: 'Kimberly',
    id: 45,
    range: RANGE.SHORT,
    rune: RUNES.NONE,
    isRuneLocked: false,
    counterEligible: true,
    weapon: {
      id: 24,
      lvl: 8,
    },
    wearClasses: [WEAR_CLASSES.CAP, WEAR_CLASSES.LIGHT_ARMOR, WEAR_CLASSES.FEMALE],
    inventory: [
      { item: ARMOR.LEATHER_COAT, equipped: true, slot: 'BODY' },
      { item: ARMOR.WOODEN_SHOES, equipped: true, slot: 'ACCESSORY_1' },
    ],
    stats: {
      initial: {
        HP: 26,
        PWR: 13,
        SKL: 19,
        DEF: 11,
        SPD: 21,
        MGC: 11,
        LUK: 13,
      },
      growths: {
        PWR: 4,
        SKL: 6,
        DEF: 4,
        SPD: 5,
        MGC: 2,
        LUK: 5,
      },
    },
  },
  [CHARACTER_KEYS.KIRKE]: {
    name: 'Kirke',
    id: 81,
    range: RANGE.SHORT,
    rune: RUNES.NONE,
    isRuneLocked: false,
    counterEligible: true,
    weapon: {
      id: 60,
      lvl: 5,
    },
    wearClasses: [WEAR_CLASSES.CAP, WEAR_CLASSES.LIGHT_ARMOR, WEAR_CLASSES.MALE],
    inventory: [
      { item: ARMOR.LEATHER_COAT, equipped: true, slot: 'BODY' },
    ],
    stats: {
      initial: {
        HP: 20,
        PWR: 14,
        SKL: 17,
        DEF: 13,
        SPD: 12,
        MGC: 10,
        LUK: 2,
      },
      growths: {
        PWR: 5,
        SKL: 4,
        DEF: 4,
        SPD: 3,
        MGC: 2,
        LUK: 0,
      },
    },
  },
  [CHARACTER_KEYS.KIRKIS]: {
    name: 'Kirkis',
    id: 4,
    range: RANGE.LONG,
    rune: RUNES.NONE,
    isRuneLocked: false,
    counterEligible: false,
    weapon: {
      id: 20,
      lvl: 5,
    },
    wearClasses: [WEAR_CLASSES.CAP, WEAR_CLASSES.LIGHT_ARMOR, WEAR_CLASSES.MALE],
    inventory: [
      { item: ARMOR.BANDANNA, equipped: true, slot: 'HEAD' },
      { item: ARMOR.BRASS_ARMOR, equipped: true, slot: 'BODY' },
    ],
    stats: {
      initial: {
        HP: 20,
        PWR: 13,
        SKL: 21,
        DEF: 12,
        SPD: 15,
        MGC: 11,
        LUK: 12,
      },
      growths: {
        PWR: 5,
        SKL: 8,
        DEF: 5,
        SPD: 6,
        MGC: 5,
        LUK: 3,
      },
    },
  },
  [CHARACTER_KEYS.KREUTZ]: {
    name: 'Kreutz',
    id: 74,
    range: RANGE.SHORT,
    rune: RUNES.NONE,
    isRuneLocked: false,
    counterEligible: true,
    weapon: {
      id: 59,
      lvl: 9,
    },
    wearClasses: [
      WEAR_CLASSES.HELMET,
      WEAR_CLASSES.HEAVY_ARMOR,
      WEAR_CLASSES.SHIELD,
      WEAR_CLASSES.MALE,
    ],
    inventory: [
      { item: ARMOR.HALF_ARMOR, equipped: true, slot: 'BODY' },
      { item: ARMOR.STEEL_SHIELD, equipped: true, slot: 'SHIELD' },
    ],
    stats: {
      initial: {
        HP: 27,
        PWR: 19,
        SKL: 17,
        DEF: 18,
        SPD: 3,
        MGC: 2,
        LUK: 10,
      },
      growths: {
        PWR: 6,
        SKL: 3,
        DEF: 6,
        SPD: 1,
        MGC: 1,
        LUK: 1,
      },
    },
  },
  [CHARACTER_KEYS.KRIN]: {
    name: 'Krin',
    id: 15,
    range: RANGE.LONG,
    rune: RUNES.NONE,
    isRuneLocked: false,
    counterEligible: false,
    weapon: {
      id: 18,
      lvl: 2,
    },
    wearClasses: [WEAR_CLASSES.CAP, WEAR_CLASSES.VEST, WEAR_CLASSES.MALE],
    inventory: [
      { item: ARMOR.TUNIC, equipped: true, slot: 'BODY' },
      { item: ITEMS.ESCAPE_TALISMAN },
    ],
    stats: {
      initial: {
        HP: 13,
        PWR: 3,
        SKL: 12,
        DEF: 2,
        SPD: 25,
        MGC: 4,
        LUK: 6,
      },
      growths: {
        PWR: 3,
        SKL: 6,
        DEF: 2,
        SPD: 8,
        MGC: 1,
        LUK: 1,
      },
    },
  },
  [CHARACTER_KEYS.KUROMIMI]: {
    name: 'Kuromimi',
    id: 14,
    range: RANGE.SHORT,
    rune: RUNES.NONE,
    isRuneLocked: false,
    counterEligible: true,
    weapon: {
      id: 41,
      lvl: 6,
    },
    wearClasses: [
      WEAR_CLASSES.HELMET,
      WEAR_CLASSES.LIGHT_ARMOR,
      WEAR_CLASSES.SHIELD,
      WEAR_CLASSES.KOBOLD,
    ],
    inventory: [
      { item: ARMOR.HEADBAND, equipped: true, slot: 'HEAD' },
      { item: ARMOR.BRASS_ARMOR, equipped: true, slot: 'BODY' },
      { item: ARMOR.WOODEN_SHIELD, equipped: true, slot: 'SHIELD' },
      { item: ITEMS.MEDICINE },
    ],
    stats: {
      initial: {
        HP: 18,
        PWR: 15,
        SKL: 12,
        DEF: 12,
        SPD: 9,
        MGC: 5,
        LUK: 13,
      },
      growths: {
        PWR: 5,
        SKL: 4,
        DEF: 5,
        SPD: 5,
        MGC: 2,
        LUK: 5,
      },
    },
  },
  [CHARACTER_KEYS.KWANDA]: {
    name: 'Kwanda',
    id: 25,
    range: RANGE.MEDIUM,
    rune: RUNES.NONE,
    isRuneLocked: false,
    counterEligible: true,
    weapon: {
      id: 32,
      lvl: 6,
    },
    wearClasses: [
      WEAR_CLASSES.HELMET,
      WEAR_CLASSES.HEAVY_ARMOR,
      WEAR_CLASSES.SHIELD,
      WEAR_CLASSES.MALE,
    ],
    inventory: [
      { item: ARMOR.HALF_HELMET, equipped: true, slot: 'HEAD' },
      { item: ARMOR.LEATHER_ARMOR, equipped: true, slot: 'BODY' },
    ],
    stats: {
      initial: {
        HP: 26,
        PWR: 18,
        SKL: 9,
        DEF: 25,
        SPD: 5,
        MGC: 3,
        LUK: 7,
      },
      growths: {
        PWR: 6,
        SKL: 3,
        DEF: 8,
        SPD: 2,
        MGC: 1,
        LUK: 3,
      },
    },
  },
  [CHARACTER_KEYS.LEONARDO]: {
    name: 'Leonardo',
    id: 41,
    range: RANGE.MEDIUM,
    rune: RUNES.NONE,
    isRuneLocked: false,
    counterEligible: true,
    weapon: {
      id: 47,
      lvl: 5,
    },
    wearClasses: [WEAR_CLASSES.HELMET, WEAR_CLASSES.LIGHT_ARMOR, WEAR_CLASSES.MALE],
    inventory: [
      { item: ARMOR.TUNIC, equipped: true, slot: 'BODY' },
    ],
    stats: {
      initial: {
        HP: 26,
        PWR: 17,
        SKL: 7,
        DEF: 13,
        SPD: 15,
        MGC: 5,
        LUK: 8,
      },
      growths: {
        PWR: 6,
        SKL: 3,
        DEF: 4,
        SPD: 4,
        MGC: 1,
        LUK: 1,
      },
    },
  },
  [CHARACTER_KEYS.LEPANT]: {
    name: 'Lepant',
    id: 30,
    range: RANGE.SHORT,
    rune: RUNES.NONE,
    isRuneLocked: false,
    counterEligible: true,
    weapon: {
      id: 16,
      lvl: 5,
    },
    wearClasses: [
      WEAR_CLASSES.CAP,
      WEAR_CLASSES.LIGHT_ARMOR,
      WEAR_CLASSES.SHIELD,
      WEAR_CLASSES.MALE,
    ],
    inventory: [
      { item: ARMOR.BRASS_ARMOR, equipped: true, slot: 'BODY' },
      { item: ARMOR.WOODEN_SHIELD, equipped: true, slot: 'SHIELD' },
      { item: ITEMS.MEDICINE },
    ],
    stats: {
      initial: {
        HP: 24,
        PWR: 21,
        SKL: 18,
        DEF: 16,
        SPD: 11,
        MGC: 12,
        LUK: 9,
      },
      growths: {
        PWR: 5,
        SKL: 5,
        DEF: 4,
        SPD: 4,
        MGC: 3,
        LUK: 4,
      },
    },
  },
  [CHARACTER_KEYS.LESTER]: {
    name: 'Lester',
    id: 102,
    range: RANGE.MEDIUM,
    rune: RUNES.NONE,
    isRuneLocked: false,
    counterEligible: true,
    weapon: {
      id: 69,
      lvl: 3,
    },
    wearClasses: [WEAR_CLASSES.CAP, WEAR_CLASSES.VEST, WEAR_CLASSES.SHIELD, WEAR_CLASSES.MALE],
    inventory: [
      { item: ARMOR.LEATHER_COAT, equipped: true, slot: 'BODY' },
    ],
    stats: {
      initial: {
        HP: 14,
        PWR: 17,
        SKL: 18,
        DEF: 13,
        SPD: 14,
        MGC: 6,
        LUK: 10,
      },
      growths: {
        PWR: 4,
        SKL: 4,
        DEF: 3,
        SPD: 5,
        MGC: 1,
        LUK: 5,
      },
    },
  },
  [CHARACTER_KEYS.LIUKAN]: {
    name: 'Liukan',
    id: 7,
    range: RANGE.SHORT,
    rune: RUNES.NONE,
    isRuneLocked: false,
    counterEligible: true,
    weapon: {
      id: 21,
      lvl: 2,
    },
    wearClasses: [WEAR_CLASSES.CAP, WEAR_CLASSES.ROBE, WEAR_CLASSES.SHIELD, WEAR_CLASSES.MALE],
    inventory: [
      { item: ARMOR.GUARD_ROBE, equipped: true, slot: 'BODY' },
      { item: ITEMS.MEDICINE },
      { item: ITEMS.MEDICINE },
      { item: ITEMS.MEGA_MEDICINE },
      { item: ITEMS.MEGA_MEDICINE },
      { item: ITEMS.SACRIFICIAL_BUDDHA },
    ],
    stats: {
      initial: {
        HP: 16,
        PWR: 9,
        SKL: 18,
        DEF: 7,
        SPD: 11,
        MGC: 13,
        LUK: 16,
      },
      growths: {
        PWR: 3,
        SKL: 7,
        DEF: 3,
        SPD: 4,
        MGC: 3,
        LUK: 5,
      },
    },
  },
  [CHARACTER_KEYS.LORELAI]: {
    name: 'Lorelai',
    id: 47,
    range: RANGE.LONG,
    rune: RUNES.NONE,
    isRuneLocked: false,
    counterEligible: false,
    weapon: {
      id: 54,
      lvl: 5,
    },
    wearClasses: [
      WEAR_CLASSES.HELMET,
      WEAR_CLASSES.LIGHT_ARMOR,
      WEAR_CLASSES.SHIELD,
      WEAR_CLASSES.FEMALE,
    ],
    inventory: [
      { item: ARMOR.HEADBAND, equipped: true, slot: 'HEAD' },
      { item: ARMOR.TUNIC, equipped: true, slot: 'BODY' },
      { item: ITEMS.MEDICINE },
    ],
    stats: {
      initial: {
        HP: 20,
        PWR: 17,
        SKL: 25,
        DEF: 13,
        SPD: 9,
        MGC: 7,
        LUK: 15,
      },
      growths: {
        PWR: 5,
        SKL: 7,
        DEF: 4,
        SPD: 3,
        MGC: 2,
        LUK: 2,
      },
    },
  },
  [CHARACTER_KEYS.LOTTE]: {
    name: 'Lotte',
    id: 56,
    range: RANGE.SHORT,
    rune: RUNES.EARTH,
    isRuneLocked: false,
    counterEligible: true,
    weapon: {
      id: 52,
      lvl: 4,
    },
    wearClasses: [WEAR_CLASSES.CAP, WEAR_CLASSES.LIGHT_ARMOR, WEAR_CLASSES.FEMALE],
    inventory: [
      { item: ARMOR.GUARD_ROBE, equipped: true, slot: 'BODY' },
    ],
    stats: {
      initial: {
        HP: 16,
        PWR: 12,
        SKL: 14,
        DEF: 13,
        SPD: 16,
        MGC: 18,
        LUK: 11,
      },
      growths: {
        PWR: 3,
        SKL: 4,
        DEF: 3,
        SPD: 5,
        MGC: 6,
        LUK: 4,
      },
    },
  },
  [CHARACTER_KEYS.LUC]: {
    name: 'Luc',
    id: 26,
    range: RANGE.SHORT,
    rune: RUNES.WIND,
    isRuneLocked: false,
    counterEligible: true,
    weapon: {
      id: 15,
      lvl: 3,
    },
    wearClasses: [WEAR_CLASSES.CAP, WEAR_CLASSES.ROBE, WEAR_CLASSES.MALE],
    inventory: [
      { item: ARMOR.GUARD_ROBE, equipped: true, slot: 'BODY', locked: true },
      { item: ARMOR.SPEED_RING, equipped: true, slot: 'ACCESSORY_1', locked: true },
    ],
    stats: {
      initial: {
        HP: 13,
        PWR: 3,
        SKL: 7,
        DEF: 2,
        SPD: 16,
        MGC: 27,
        LUK: 6,
      },
      growths: {
        PWR: 0,
        SKL: 5,
        DEF: 1,
        SPD: 5,
        MGC: 8,
        LUK: 1,
      },
    },
  },
  [CHARACTER_KEYS.MAAS]: {
    name: 'Maas',
    id: 70,
    range: RANGE.MEDIUM,
    rune: RUNES.NONE,
    isRuneLocked: false,
    counterEligible: true,
    weapon: {
      id: 70,
      lvl: 3,
    },
    wearClasses: [WEAR_CLASSES.CAP, WEAR_CLASSES.LIGHT_ARMOR, WEAR_CLASSES.MALE],
    inventory: [
      { item: ARMOR.LEATHER_COAT, equipped: true, slot: 'BODY' },
    ],
    stats: {
      initial: {
        HP: 20,
        PWR: 13,
        SKL: 15,
        DEF: 14,
        SPD: 12,
        MGC: 10,
        LUK: 15,
      },
      growths: {
        PWR: 4,
        SKL: 5,
        DEF: 4,
        SPD: 4,
        MGC: 2,
        LUK: 4,
      },
    },
  },
  [CHARACTER_KEYS.MACE]: {
    name: 'Mace',
    id: 71,
    range: RANGE.MEDIUM,
    rune: RUNES.NONE,
    isRuneLocked: false,
    counterEligible: true,
    weapon: {
      id: 73,
      lvl: 15,
    },
    wearClasses: [WEAR_CLASSES.CAP, WEAR_CLASSES.LIGHT_ARMOR, WEAR_CLASSES.MALE],
    inventory: [
      { item: ARMOR.LEATHER_ARMOR, equipped: true, slot: 'BODY' },
    ],
    stats: {
      initial: {
        HP: 27,
        PWR: 16,
        SKL: 21,
        DEF: 17,
        SPD: 13,
        MGC: 10,
        LUK: 15,
      },
      growths: {
        PWR: 6,
        SKL: 6,
        DEF: 6,
        SPD: 5,
        MGC: 3,
        LUK: 5,
      },
    },
  },
  [CHARACTER_KEYS.MEESE]: {
    name: 'Meese',
    id: 69,
    range: RANGE.MEDIUM,
    rune: RUNES.NONE,
    isRuneLocked: false,
    counterEligible: true,
    weapon: {
      id: 71,
      lvl: 9,
    },
    wearClasses: [WEAR_CLASSES.CAP, WEAR_CLASSES.LIGHT_ARMOR, WEAR_CLASSES.MALE],
    inventory: [
      { item: ARMOR.LEATHER_COAT, equipped: true, slot: 'BODY' },
    ],
    stats: {
      initial: {
        HP: 20,
        PWR: 13,
        SKL: 15,
        DEF: 14,
        SPD: 12,
        MGC: 10,
        LUK: 15,
      },
      growths: {
        PWR: 4,
        SKL: 5,
        DEF: 4,
        SPD: 4,
        MGC: 2,
        LUK: 4,
      },
    },
  },
  [CHARACTER_KEYS.MEG]: {
    name: 'Meg',
    id: 76,
    range: RANGE.LONG,
    rune: RUNES.NONE,
    isRuneLocked: false,
    counterEligible: false,
    weapon: {
      id: 61,
      lvl: 6,
    },
    wearClasses: [WEAR_CLASSES.CAP, WEAR_CLASSES.VEST, WEAR_CLASSES.FEMALE],
    inventory: [
      { item: ARMOR.GUARD_ROBE, equipped: true, slot: 'BODY', locked: true },
    ],
    stats: {
      initial: {
        HP: 16,
        PWR: 11,
        SKL: 17,
        DEF: 13,
        SPD: 12,
        MGC: 9,
        LUK: 25,
      },
      growths: {
        PWR: 4,
        SKL: 5,
        DEF: 4,
        SPD: 4,
        MGC: 3,
        LUK: 8,
      },
    },
  },
  [CHARACTER_KEYS.MILIA]: {
    name: 'Milia',
    id: 29,
    range: RANGE.MEDIUM,
    rune: RUNES.NONE,
    isRuneLocked: false,
    counterEligible: true,
    weapon: {
      id: 29,
      lvl: 9,
    },
    wearClasses: [
      WEAR_CLASSES.HELMET,
      WEAR_CLASSES.LIGHT_ARMOR,
      WEAR_CLASSES.SHIELD,
      WEAR_CLASSES.FEMALE,
    ],
    inventory: [
      { item: ARMOR.LEATHER_ARMOR, equipped: true, slot: 'BODY' },
      { item: ARMOR.WOODEN_SHIELD, equipped: true, slot: 'SHIELD' },
    ],
    stats: {
      initial: {
        HP: 27,
        PWR: 18,
        SKL: 12,
        DEF: 14,
        SPD: 9,
        MGC: 3,
        LUK: 7,
      },
      growths: {
        PWR: 6,
        SKL: 3,
        DEF: 6,
        SPD: 3,
        MGC: 1,
        LUK: 4,
      },
    },
  },
  [CHARACTER_KEYS.MILICH]: {
    name: 'Milich',
    id: 28,
    range: RANGE.SHORT,
    rune: RUNES.NONE,
    isRuneLocked: false,
    counterEligible: true,
    weapon: {
      id: 34,
      lvl: 6,
    },
    wearClasses: [
      WEAR_CLASSES.CAP,
      WEAR_CLASSES.LIGHT_ARMOR,
      WEAR_CLASSES.SHIELD,
      WEAR_CLASSES.NOBILITY,
    ],
    inventory: [
      { item: ARMOR.POINTED_HAT, equipped: true, slot: 'HEAD' },
      { item: ARMOR.GUARD_ROBE, equipped: true, slot: 'BODY' },
      { item: ARMOR.ROSE_BROOCH, equipped: true, slot: 'ACCESSORY_1', locked: true },
    ],
    stats: {
      initial: {
        HP: 24,
        PWR: 17,
        SKL: 15,
        DEF: 17,
        SPD: 16,
        MGC: 20,
        LUK: 7,
      },
      growths: {
        PWR: 5,
        SKL: 4,
        DEF: 5,
        SPD: 4,
        MGC: 6,
        LUK: 1,
      },
    },
  },
  [CHARACTER_KEYS.MINA]: {
    name: 'Mina',
    id: 61,
    range: RANGE.SHORT,
    rune: RUNES.NONE,
    isRuneLocked: false,
    counterEligible: true,
    weapon: {
      id: 57,
      lvl: 6,
    },
    wearClasses: [WEAR_CLASSES.CAP, WEAR_CLASSES.LIGHT_ARMOR, WEAR_CLASSES.FEMALE],
    inventory: [
      { item: ARMOR.MAGIC_ROBE, equipped: true, slot: 'BODY' },
      { item: ARMOR.TOE_SHOES, equipped: true, slot: 'ACCESSORY_1', locked: true },
    ],
    stats: {
      initial: {
        HP: 16,
        PWR: 6,
        SKL: 13,
        DEF: 11,
        SPD: 15,
        MGC: 17,
        LUK: 22,
      },
      growths: {
        PWR: 2,
        SKL: 4,
        DEF: 4,
        SPD: 4,
        MGC: 6,
        LUK: 6,
      },
    },
  },
  [CHARACTER_KEYS.MOOSE]: {
    name: 'Moose',
    id: 72,
    range: RANGE.MEDIUM,
    rune: RUNES.NONE,
    isRuneLocked: false,
    counterEligible: true,
    weapon: {
      id: 72,
      lvl: 12,
    },
    wearClasses: [WEAR_CLASSES.CAP, WEAR_CLASSES.LIGHT_ARMOR, WEAR_CLASSES.MALE],
    inventory: [
      { item: ARMOR.LEATHER_COAT, equipped: true, slot: 'BODY' },
    ],
    stats: {
      initial: {
        HP: 20,
        PWR: 13,
        SKL: 15,
        DEF: 14,
        SPD: 12,
        MGC: 10,
        LUK: 15,
      },
      growths: {
        PWR: 4,
        SKL: 6,
        DEF: 4,
        SPD: 4,
        MGC: 2,
        LUK: 4,
      },
    },
  },
  [CHARACTER_KEYS.MORGAN]: {
    name: 'Morgan',
    id: 52,
    range: RANGE.SHORT,
    rune: RUNES.COUNTER,
    isRuneLocked: false,
    counterEligible: true,
    weapon: {
      id: 55,
      lvl: 6,
    },
    wearClasses: [WEAR_CLASSES.CAP, WEAR_CLASSES.VEST, WEAR_CLASSES.MALE],
    inventory: [
      { item: ARMOR.HEADBAND, equipped: true, slot: 'HEAD' },
      { item: ARMOR.KARATE_UNIFORM, equipped: true, slot: 'BODY' },
    ],
    stats: {
      initial: {
        HP: 24,
        PWR: 19,
        SKL: 9,
        DEF: 16,
        SPD: 7,
        MGC: 1,
        LUK: 12,
      },
      growths: {
        PWR: 6,
        SKL: 3,
        DEF: 5,
        SPD: 2,
        MGC: 0,
        LUK: 1,
      },
    },
  },
  [CHARACTER_KEYS.MOSE]: {
    name: 'Mose',
    id: 5,
    range: RANGE.MEDIUM,
    rune: RUNES.NONE,
    isRuneLocked: false,
    counterEligible: true,
    weapon: {
      id: 26,
      lvl: 8,
    },
    wearClasses: [WEAR_CLASSES.HELMET, WEAR_CLASSES.LIGHT_ARMOR, WEAR_CLASSES.MALE],
    inventory: [
      { item: ARMOR.BRASS_ARMOR, equipped: true, slot: 'BODY' },
    ],
    stats: {
      initial: {
        HP: 24,
        PWR: 15,
        SKL: 16,
        DEF: 13,
        SPD: 12,
        MGC: 10,
        LUK: 17,
      },
      growths: {
        PWR: 5,
        SKL: 5,
        DEF: 5,
        SPD: 4,
        MGC: 1,
        LUK: 3,
      },
    },
  },
  [CHARACTER_KEYS.ODESSA]: {
    name: 'Odessa',
    id: 109,
    range: RANGE.LONG,
    rune: RUNES.WIND,
    isRuneLocked: true,
    counterEligible: false,
    weapon: {
      id: 78,
      lvl: 5,
    },
    wearClasses: [WEAR_CLASSES.CAP, WEAR_CLASSES.LIGHT_ARMOR, WEAR_CLASSES.FEMALE],
    inventory: [
      { item: ARMOR.HEAD_GEAR, equipped: true, slot: 'HEAD', locked: true },
      { item: ARMOR.TUNIC, equipped: true, slot: 'BODY' },
      { item: ITEMS.MEDICINE },
    ],
    stats: {
      initial: {
        HP: 24,
        PWR: 13,
        SKL: 21,
        DEF: 12,
        SPD: 18,
        MGC: 10,
        LUK: 18,
      },
      growths: {
        PWR: 5,
        SKL: 8,
        DEF: 5,
        SPD: 8,
        MGC: 7,
        LUK: 6,
      },
    },
  },
  [CHARACTER_KEYS.PAHN]: {
    name: 'Pahn',
    id: 6,
    range: RANGE.SHORT,
    rune: RUNES.BOAR,
    isRuneLocked: true,
    counterEligible: true,
    weapon: {
      id: 3,
      lvl: 1,
    },
    wearClasses: [WEAR_CLASSES.CAP, WEAR_CLASSES.VEST, WEAR_CLASSES.MALE],
    inventory: [
      { item: ARMOR.HEADBAND, equipped: true, slot: 'HEAD' },
      { item: ARMOR.TUNIC, equipped: true, slot: 'BODY' },
      { item: ARMOR.GLOVES, equipped: true, slot: 'ACCESSORY_1' },
    ],
    stats: {
      initial: {
        HP: 25,
        PWR: 25,
        SKL: 17,
        DEF: 18,
        SPD: 10,
        MGC: 3,
        LUK: 15,
      },
      growths: {
        PWR: 7,
        SKL: 5,
        DEF: 6,
        SPD: 2,
        MGC: 0,
        LUK: 4,
      },
    },
  },
  [CHARACTER_KEYS.PESMERGA]: {
    name: 'Pesmerga',
    id: 107,
    range: RANGE.SHORT,
    rune: RUNES.NONE,
    isRuneLocked: false,
    counterEligible: true,
    weapon: {
      id: 75,
      lvl: 7,
    },
    wearClasses: [
      WEAR_CLASSES.HELMET,
      WEAR_CLASSES.HEAVY_ARMOR,
      WEAR_CLASSES.SHIELD,
      WEAR_CLASSES.MALE,
    ],
    inventory: [
      { item: ARMOR.HALF_HELMET, equipped: true, slot: 'HEAD' },
      { item: ARMOR.DRAGON_ARMOR, equipped: true, slot: 'BODY', locked: true },
      { item: ARMOR.STEEL_SHIELD, equipped: true, slot: 'SHIELD' },
    ],
    stats: {
      initial: {
        HP: 26,
        PWR: 22,
        SKL: 7,
        DEF: 17,
        SPD: 6,
        MGC: 3,
        LUK: 1,
      },
      growths: {
        PWR: 8,
        SKL: 2,
        DEF: 6,
        SPD: 3,
        MGC: 1,
        LUK: 0,
      },
    },
  },
  [CHARACTER_KEYS.QUINCY]: {
    name: 'Quincy',
    id: 68,
    range: RANGE.LONG,
    rune: RUNES.NONE,
    isRuneLocked: false,
    counterEligible: false,
    weapon: {
      id: 56,
      lvl: 6,
    },
    wearClasses: [WEAR_CLASSES.CAP, WEAR_CLASSES.VEST, WEAR_CLASSES.MALE],
    inventory: [
      { item: ARMOR.GUARD_ROBE, equipped: true, slot: 'BODY' },
      { item: ARMOR.FEATHER, equipped: true, slot: 'ACCESSORY_1' },
    ],
    stats: {
      initial: {
        HP: 20,
        PWR: 13,
        SKL: 27,
        DEF: 16,
        SPD: 13,
        MGC: 5,
        LUK: 14,
      },
      growths: {
        PWR: 4,
        SKL: 8,
        DEF: 5,
        SPD: 5,
        MGC: 1,
        LUK: 5,
      },
    },
  },
  [CHARACTER_KEYS.RONNIE]: {
    name: 'Ronnie',
    id: 13,
    range: RANGE.SHORT,
    rune: RUNES.HATE,
    isRuneLocked: true,
    counterEligible: true,
    weapon: {
      id: 40,
      lvl: 7,
    },
    wearClasses: [WEAR_CLASSES.CAP, WEAR_CLASSES.VEST, WEAR_CLASSES.FEMALE],
    inventory: [
      { item: ARMOR.HEADBAND, equipped: true, slot: 'HEAD' },
      { item: ARMOR.KARATE_UNIFORM, equipped: true, slot: 'BODY' },
    ],
    stats: {
      initial: {
        HP: 24,
        PWR: 17,
        SKL: 13,
        DEF: 16,
        SPD: 9,
        MGC: 1,
        LUK: 7,
      },
      growths: {
        PWR: 6,
        SKL: 4,
        DEF: 6,
        SPD: 4,
        MGC: 0,
        LUK: 3,
      },
    },
  },
  [CHARACTER_KEYS.RUBI]: {
    name: 'Rubi',
    id: 51,
    range: RANGE.LONG,
    rune: RUNES.NONE,
    isRuneLocked: false,
    counterEligible: false,
    weapon: {
      id: 51,
      lvl: 6,
    },
    wearClasses: [WEAR_CLASSES.CAP, WEAR_CLASSES.LIGHT_ARMOR, WEAR_CLASSES.MALE],
    inventory: [
      { item: ARMOR.BANDANNA, equipped: true, slot: 'HEAD' },
      { item: ARMOR.BRASS_ARMOR, equipped: true, slot: 'BODY' },
    ],
    stats: {
      initial: {
        HP: 20,
        PWR: 14,
        SKL: 13,
        DEF: 12,
        SPD: 17,
        MGC: 18,
        LUK: 1,
      },
      growths: {
        PWR: 5,
        SKL: 6,
        DEF: 4,
        SPD: 6,
        MGC: 6,
        LUK: 0,
      },
    },
  },
  [CHARACTER_KEYS.SANSUKE]: {
    name: 'Sansuke',
    id: 95,
    range: RANGE.SHORT,
    rune: RUNES.NONE,
    isRuneLocked: false,
    counterEligible: true,
    weapon: {
      id: 66,
      lvl: 5,
    },
    wearClasses: [WEAR_CLASSES.CAP, WEAR_CLASSES.VEST, WEAR_CLASSES.MALE],
    inventory: [
      { item: ARMOR.TUNIC, equipped: true, slot: 'BODY' },
    ],
    stats: {
      initial: {
        HP: 20,
        PWR: 11,
        SKL: 13,
        DEF: 15,
        SPD: 12,
        MGC: 4,
        LUK: 8,
      },
      growths: {
        PWR: 3,
        SKL: 5,
        DEF: 5,
        SPD: 4,
        MGC: 1,
        LUK: 4,
      },
    },
  },
  [CHARACTER_KEYS.SARAH]: {
    name: 'Sarah',
    id: 54,
    range: RANGE.LONG,
    rune: RUNES.NONE,
    isRuneLocked: false,
    counterEligible: false,
    weapon: {
      id: 62,
      lvl: 2,
    },
    wearClasses: [WEAR_CLASSES.CAP, WEAR_CLASSES.VEST, WEAR_CLASSES.FEMALE],
    inventory: [
      { item: ARMOR.TUNIC, equipped: true, slot: 'BODY' },
    ],
    stats: {
      initial: {
        HP: 20,
        PWR: 17,
        SKL: 11,
        DEF: 19,
        SPD: 13,
        MGC: 16,
        LUK: 8,
      },
      growths: {
        PWR: 5,
        SKL: 3,
        DEF: 5,
        SPD: 3,
        MGC: 4,
        LUK: 2,
      },
    },
  },
  [CHARACTER_KEYS.SERGEI]: {
    name: 'Sergei',
    id: 92,
    range: RANGE.SHORT,
    rune: RUNES.NONE,
    isRuneLocked: false,
    counterEligible: true,
    weapon: {
      id: 65,
      lvl: 4,
    },
    wearClasses: [WEAR_CLASSES.CAP, WEAR_CLASSES.LIGHT_ARMOR, WEAR_CLASSES.MALE],
    inventory: [
      { item: ARMOR.ROBE, equipped: true, slot: 'BODY' },
      { item: ARMOR.GLOVES, equipped: true, slot: 'ACCESSORY_1' },
    ],
    stats: {
      initial: {
        HP: 20,
        PWR: 7,
        SKL: 17,
        DEF: 16,
        SPD: 9,
        MGC: 11,
        LUK: 13,
      },
      growths: {
        PWR: 2,
        SKL: 6,
        DEF: 6,
        SPD: 3,
        MGC: 2,
        LUK: 2,
      },
    },
  },
  [CHARACTER_KEYS.SHEENA]: {
    name: 'Sheena',
    id: 62,
    range: RANGE.SHORT,
    rune: RUNES.LIGHTNING,
    isRuneLocked: true,
    counterEligible: true,
    weapon: {
      id: 45,
      lvl: 6,
    },
    wearClasses: [WEAR_CLASSES.CAP, WEAR_CLASSES.LIGHT_ARMOR, WEAR_CLASSES.MALE],
    inventory: [
      { item: ARMOR.TUNIC, equipped: true, slot: 'BODY' },
    ],
    stats: {
      initial: {
        HP: 20,
        PWR: 16,
        SKL: 14,
        DEF: 15,
        SPD: 12,
        MGC: 15,
        LUK: 13,
      },
      growths: {
        PWR: 5,
        SKL: 4,
        DEF: 5,
        SPD: 6,
        MGC: 6,
        LUK: 6,
      },
    },
  },
  [CHARACTER_KEYS.SONYA]: {
    name: 'Sonya',
    id: 10,
    range: RANGE.SHORT,
    rune: RUNES.WATER,
    isRuneLocked: false,
    counterEligible: true,
    weapon: {
      id: 37,
      lvl: 11,
    },
    wearClasses: [
      WEAR_CLASSES.HELMET,
      WEAR_CLASSES.LIGHT_ARMOR,
      WEAR_CLASSES.SHIELD,
      WEAR_CLASSES.FEMALE,
    ],
    inventory: [
      { item: ARMOR.LEATHER_ARMOR, equipped: true, slot: 'BODY' },
      { item: ARMOR.CRIMSON_CAPE, equipped: true, slot: 'ACCESSORY_1', locked: true },
    ],
    stats: {
      initial: {
        HP: 20,
        PWR: 16,
        SKL: 17,
        DEF: 13,
        SPD: 21,
        MGC: 18,
        LUK: 15,
      },
      growths: {
        PWR: 6,
        SKL: 5,
        DEF: 4,
        SPD: 7,
        MGC: 5,
        LUK: 3,
      },
    },
  },
  [CHARACTER_KEYS.STALLION]: {
    name: 'Stallion',
    id: 75,
    range: RANGE.LONG,
    rune: RUNES.TRUE_HOLY,
    isRuneLocked: true,
    counterEligible: false,
    weapon: {
      id: 39,
      lvl: 6,
    },
    wearClasses: [WEAR_CLASSES.CAP, WEAR_CLASSES.LIGHT_ARMOR, WEAR_CLASSES.MALE],
    inventory: [
      { item: ARMOR.BRASS_ARMOR, equipped: true, slot: 'BODY' },
      { item: ARMOR.WING_BOOTS, equipped: true, slot: 'ACCESSORY_1', locked: true },
      { item: ITEMS.ESCAPE_TALISMAN },
    ],
    stats: {
      initial: {
        HP: 16,
        PWR: 14,
        SKL: 9,
        DEF: 13,
        SPD: 19,
        MGC: 10,
        LUK: 13,
      },
      growths: {
        PWR: 3,
        SKL: 6,
        DEF: 5,
        SPD: 8,
        MGC: 4,
        LUK: 4,
      },
    },
  },
  [CHARACTER_KEYS.SYDONIA]: {
    name: 'Sydonia',
    id: 31,
    range: RANGE.LONG,
    rune: RUNES.NONE,
    isRuneLocked: false,
    counterEligible: false,
    weapon: {
      id: 9,
      lvl: 6,
    },
    wearClasses: [WEAR_CLASSES.CAP, WEAR_CLASSES.VEST, WEAR_CLASSES.MALE],
    inventory: [
      { item: ARMOR.BANDANNA, equipped: true, slot: 'HEAD' },
      { item: ARMOR.LEATHER_COAT, equipped: true, slot: 'BODY' },
    ],
    stats: {
      initial: {
        HP: 18,
        PWR: 17,
        SKL: 22,
        DEF: 9,
        SPD: 22,
        MGC: 7,
        LUK: 5,
      },
      growths: {
        PWR: 4,
        SKL: 6,
        DEF: 3,
        SPD: 6,
        MGC: 3,
        LUK: 2,
      },
    },
  },
  [CHARACTER_KEYS.SYLVINA]: {
    name: 'Sylvina',
    id: 9,
    range: RANGE.LONG,
    rune: RUNES.NONE,
    isRuneLocked: false,
    counterEligible: false,
    weapon: {
      id: 38,
      lvl: 5,
    },
    wearClasses: [WEAR_CLASSES.CAP, WEAR_CLASSES.ROBE, WEAR_CLASSES.FEMALE],
    inventory: [
      { item: ARMOR.ROBE, equipped: true, slot: 'BODY' },
      { item: ITEMS.MEDICINE },
    ],
    stats: {
      initial: {
        HP: 16,
        PWR: 9,
        SKL: 13,
        DEF: 8,
        SPD: 15,
        MGC: 17,
        LUK: 22,
      },
      growths: {
        PWR: 3,
        SKL: 5,
        DEF: 4,
        SPD: 6,
        MGC: 5,
        LUK: 6,
      },
    },
  },
  [CHARACTER_KEYS.TAI_HO]: {
    name: 'Tai Ho',
    id: 32,
    range: RANGE.MEDIUM,
    rune: RUNES.NONE,
    isRuneLocked: false,
    counterEligible: true,
    weapon: {
      id: 13,
      lvl: 3,
    },
    wearClasses: [WEAR_CLASSES.CAP, WEAR_CLASSES.VEST, WEAR_CLASSES.MALE],
    inventory: [
      { item: ARMOR.HEADBAND, equipped: true, slot: 'HEAD' },
      { item: ARMOR.TUNIC, equipped: true, slot: 'BODY' },
      { item: ITEMS.MEDICINE },
    ],
    stats: {
      initial: {
        HP: 24,
        PWR: 21,
        SKL: 14,
        DEF: 12,
        SPD: 11,
        MGC: 10,
        LUK: 12,
      },
      growths: {
        PWR: 6,
        SKL: 7,
        DEF: 3,
        SPD: 5,
        MGC: 1,
        LUK: 4,
      },
    },
  },
  [CHARACTER_KEYS.TENGAAR]: {
    name: 'Tengaar',
    id: 33,
    range: RANGE.LONG,
    rune: RUNES.NONE,
    isRuneLocked: false,
    counterEligible: false,
    weapon: {
      id: 30,
      lvl: 7,
    },
    wearClasses: [WEAR_CLASSES.CAP, WEAR_CLASSES.ROBE, WEAR_CLASSES.FEMALE],
    inventory: [
      { item: ARMOR.GUARD_ROBE, equipped: true, slot: 'BODY' },
      { item: ARMOR.GUARD_RING, equipped: true, slot: 'ACCESSORY_1' },
    ],
    stats: {
      initial: {
        HP: 19,
        PWR: 10,
        SKL: 16,
        DEF: 12,
        SPD: 12,
        MGC: 19,
        LUK: 8,
      },
      growths: {
        PWR: 3,
        SKL: 6,
        DEF: 4,
        SPD: 5,
        MGC: 7,
        LUK: 2,
      },
    },
  },
  [CHARACTER_KEYS.TED]: {
    name: 'Ted',
    id: 108,
    range: RANGE.LONG,
    rune: RUNES.UNKNOWN,
    isRuneLocked: true,
    counterEligible: false,
    weapon: {
      id: 77,
      lvl: 3,
    },
    wearClasses: [WEAR_CLASSES.CAP, WEAR_CLASSES.ROBE, WEAR_CLASSES.MALE],
    inventory: [
      { item: ARMOR.ROBE, equipped: true, slot: 'BODY' },
      { item: ITEMS.MEDICINE },
    ],
    stats: {
      initial: {
        HP: 18,
        PWR: 13,
        SKL: 20,
        DEF: 10,
        SPD: 15,
        MGC: 12,
        LUK: 15,
      },
      growths: {
        PWR: 5,
        SKL: 7,
        DEF: 4,
        SPD: 6,
        MGC: 7,
        LUK: 4,
      },
    },
  },
  [CHARACTER_KEYS.VALERIA]: {
    name: 'Valeria',
    id: 36,
    range: RANGE.SHORT,
    rune: RUNES.FALCON,
    isRuneLocked: true,
    counterEligible: true,
    weapon: {
      id: 33,
      lvl: 7,
    },
    wearClasses: [
      WEAR_CLASSES.HELMET,
      WEAR_CLASSES.LIGHT_ARMOR,
      WEAR_CLASSES.SHIELD,
      WEAR_CLASSES.FEMALE,
    ],
    inventory: [
      { item: ARMOR.BRASS_ARMOR, equipped: true, slot: 'BODY' },
      { item: ARMOR.WOODEN_SHIELD, equipped: true, slot: 'SHIELD' },
      { item: ITEMS.MEDICINE },
    ],
    stats: {
      initial: {
        HP: 26,
        PWR: 16,
        SKL: 17,
        DEF: 11,
        SPD: 20,
        MGC: 15,
        LUK: 12,
      },
      growths: {
        PWR: 6,
        SKL: 4,
        DEF: 6,
        SPD: 3,
        MGC: 3,
        LUK: 4,
      },
    },
  },
  [CHARACTER_KEYS.VARKAS]: {
    name: 'Varkas',
    id: 12,
    range: RANGE.MEDIUM,
    rune: RUNES.NONE,
    isRuneLocked: false,
    counterEligible: true,
    weapon: {
      id: 8,
      lvl: 5,
    },
    wearClasses: [WEAR_CLASSES.HELMET, WEAR_CLASSES.HEAVY_ARMOR, WEAR_CLASSES.MALE],
    inventory: [
      { item: ARMOR.BRASS_ARMOR, equipped: true, slot: 'BODY' },
      { item: ARMOR.LEGGINGS, equipped: true, slot: 'ACCESSORY_1' },
    ],
    stats: {
      initial: {
        HP: 30,
        PWR: 21,
        SKL: 9,
        DEF: 14,
        SPD: 12,
        MGC: 7,
        LUK: 11,
      },
      growths: {
        PWR: 6,
        SKL: 3,
        DEF: 5,
        SPD: 3,
        MGC: 1,
        LUK: 2,
      },
    },
  },
  [CHARACTER_KEYS.VIKTOR]: {
    name: 'Viktor',
    id: 35,
    range: RANGE.SHORT,
    rune: RUNES.NONE,
    isRuneLocked: false,
    counterEligible: true,
    weapon: {
      id: 5,
      lvl: 3,
    },
    wearClasses: [WEAR_CLASSES.CAP, WEAR_CLASSES.LIGHT_ARMOR, WEAR_CLASSES.MALE],
    inventory: [
      { item: ARMOR.LEATHER_COAT, equipped: true, slot: 'BODY' },
      { item: ARMOR.BOOTS, equipped: true, slot: 'ACCESSORY_1' },
    ],
    stats: {
      initial: {
        HP: 26,
        PWR: 15,
        SKL: 9,
        DEF: 10,
        SPD: 5,
        MGC: 7,
        LUK: 11,
      },
      growths: {
        PWR: 9,
        SKL: 2,
        DEF: 7,
        SPD: 5,
        MGC: 3,
        LUK: 4,
      },
    },
  },
  [CHARACTER_KEYS.WARREN]: {
    name: 'Warren',
    id: 37,
    range: RANGE.MEDIUM,
    rune: RUNES.NONE,
    isRuneLocked: false,
    counterEligible: true,
    weapon: {
      id: 7,
      lvl: 12,
    },
    wearClasses: [WEAR_CLASSES.HELMET, WEAR_CLASSES.LIGHT_ARMOR, WEAR_CLASSES.MALE],
    inventory: [
      { item: ARMOR.HALF_HELMET, equipped: true, slot: 'HEAD' },
      { item: ARMOR.LEATHER_ARMOR, equipped: true, slot: 'BODY' },
    ],
    stats: {
      initial: {
        HP: 24,
        PWR: 17,
        SKL: 16,
        DEF: 16,
        SPD: 12,
        MGC: 10,
        LUK: 11,
      },
      growths: {
        PWR: 5,
        SKL: 4,
        DEF: 5,
        SPD: 3,
        MGC: 2,
        LUK: 3,
      },
    },
  },
  [CHARACTER_KEYS.YAM_KOO]: {
    name: 'Yam Koo',
    id: 38,
    range: RANGE.MEDIUM,
    rune: RUNES.NONE,
    isRuneLocked: false,
    counterEligible: true,
    weapon: {
      id: 14,
      lvl: 3,
    },
    wearClasses: [WEAR_CLASSES.CAP, WEAR_CLASSES.VEST, WEAR_CLASSES.MALE],
    inventory: [
      { item: ARMOR.TUNIC, equipped: true, slot: 'BODY' },
    ],
    stats: {
      initial: {
        HP: 20,
        PWR: 15,
        SKL: 17,
        DEF: 11,
        SPD: 19,
        MGC: 8,
        LUK: 15,
      },
      growths: {
        PWR: 5,
        SKL: 6,
        DEF: 3,
        SPD: 6,
        MGC: 2,
        LUK: 4,
      },
    },
  },
};

export default CHARACTERS;
